window.PACK_arts = {
  id:'arts', name:'Arts & Culture', emoji:'🎭',
  words:[
    {it:'l\'arte',en:'art',cat:'Arts',ipa:'/ˈlar.te/',ex:'L\'arte italiana è famosa nel mondo.',exEn:'Italian art is famous worldwide.'},
    {it:'il museo',en:'the museum',cat:'Arts',ipa:'/il muˈzɛː.o/',ex:'Il museo è aperto.',exEn:'The museum is open.'},
    {it:'la galleria',en:'the gallery',cat:'Arts',ipa:'/la galleˈriː.a/',ex:'La galleria degli Uffizi.',exEn:'The Uffizi gallery.'},
    {it:'il quadro',en:'the painting / picture',cat:'Arts',ipa:'/il ˈkwaː.dro/',ex:'Questo quadro è del Rinascimento.',exEn:'This painting is from the Renaissance.'},
    {it:'la scultura',en:'the sculpture',cat:'Arts',ipa:'/la skulˈtuː.ra/',ex:'Una scultura di Michelangelo.',exEn:'A sculpture by Michelangelo.'},
    {it:'il pittore',en:'the painter',cat:'Arts',ipa:'/il pitˈtoː.re/',ex:'Leonardo era un grande pittore.',exEn:'Leonardo was a great painter.'},
    {it:'lo scultore',en:'the sculptor',cat:'Arts',ipa:'/lo skulˈtoː.re/',ex:'Michelangelo era un grande scultore.',exEn:'Michelangelo was a great sculptor.'},
    {it:'la musica classica',en:'classical music',cat:'Arts',ipa:'/la ˈmuː.zi.ka ˈklas.si.ka/',ex:'Amo la musica classica.',exEn:'I love classical music.'},
    {it:'l\'opera',en:'opera',cat:'Arts',ipa:'/ˈloː.pe.ra/',ex:'La Scala è famosa per l\'opera.',exEn:'La Scala is famous for opera.'},
    {it:'il cantante',en:'the singer',cat:'Arts',ipa:'/il kanˈtan.te/',ex:'È un cantante lirico.',exEn:'He\'s an opera singer.'},
    {it:'il musicista',en:'the musician',cat:'Arts',ipa:'/il muziˈtʃis.ta/',ex:'Suona come un musicista professionista.',exEn:'He plays like a professional musician.'},
    {it:'lo strumento',en:'the instrument',cat:'Arts',ipa:'/lo struˈmɛn.to/',ex:'Suoni uno strumento?',exEn:'Do you play an instrument?'},
    {it:'il pianoforte',en:'the piano',cat:'Arts',ipa:'/il pjanoˈfor.te/',ex:'Suono il pianoforte.',exEn:'I play the piano.'},
    {it:'la chitarra',en:'the guitar',cat:'Arts',ipa:'/la kiˈtar.ra/',ex:'Suono la chitarra classica.',exEn:'I play classical guitar.'},
    {it:'il violino',en:'the violin',cat:'Arts',ipa:'/il vjoˈliː.no/',ex:'Il violino è difficile.',exEn:'The violin is difficult.'},
    {it:'il teatro',en:'the theatre',cat:'Arts',ipa:'/il teˈaː.tro/',ex:'Vado spesso a teatro.',exEn:'I often go to the theatre.'},
    {it:'lo spettacolo',en:'the show / performance',cat:'Arts',ipa:'/lo spetˈtaː.ko.lo/',ex:'Lo spettacolo inizia alle otto.',exEn:'The show starts at eight.'},
    {it:'l\'attore',en:'the actor',cat:'Arts',ipa:'/latˈtoː.re/',ex:'È un grande attore.',exEn:'He\'s a great actor.'},
    {it:'l\'attrice',en:'the actress',cat:'Arts',ipa:'/latˈtriː.tʃe/',ex:'È una famosa attrice italiana.',exEn:'She\'s a famous Italian actress.'},
    {it:'il regista',en:'the director',cat:'Arts',ipa:'/il reˈdʒis.ta/',ex:'Fellini era un grande regista.',exEn:'Fellini was a great director.'},
    {it:'il film',en:'the film / movie',cat:'Arts',ipa:'/il film/',ex:'Hai visto questo film?',exEn:'Have you seen this film?'},
    {it:'la commedia',en:'comedy / play',cat:'Arts',ipa:'/la komˈmɛː.dja/',ex:'Preferisco la commedia alla tragedia.',exEn:'I prefer comedy to tragedy.'},
    {it:'la tragedia',en:'tragedy',cat:'Arts',ipa:'/la traˈdʒɛː.dja/',ex:'È una tragedia greca.',exEn:'It\'s a Greek tragedy.'},
    {it:'il balletto',en:'ballet',cat:'Arts',ipa:'/il balˈlɛt.to/',ex:'Vado a vedere il balletto.',exEn:'I\'m going to see the ballet.'},
    {it:'la danza',en:'dance',cat:'Arts',ipa:'/la ˈdan.tsa/',ex:'Pratico la danza classica.',exEn:'I do classical dance.'},
    {it:'la letteratura',en:'literature',cat:'Arts',ipa:'/la lettˈteraˈtuː.ra/',ex:'La letteratura italiana è ricca.',exEn:'Italian literature is rich.'},
    {it:'il romanzo',en:'the novel',cat:'Arts',ipa:'/il roˈman.tso/',ex:'Leggo un romanzo.',exEn:'I\'m reading a novel.'},
    {it:'la poesia',en:'poetry / poem',cat:'Arts',ipa:'/la poeˈziː.a/',ex:'Dante scrisse poesie famose.',exEn:'Dante wrote famous poems.'},
    {it:'il poeta',en:'the poet',cat:'Arts',ipa:'/il poˈɛː.ta/',ex:'Dante è il più grande poeta italiano.',exEn:'Dante is Italy\'s greatest poet.'},
    {it:'l\'autore',en:'the author',cat:'Arts',ipa:'/lawˈtoː.re/',ex:'Chi è l\'autore di questo libro?',exEn:'Who is the author of this book?'},
    {it:'la fotografia',en:'photography',cat:'Arts',ipa:'/la fotografˈiː.a/',ex:'La fotografia è la mia passione.',exEn:'Photography is my passion.'},
    {it:'l\'architettura',en:'architecture',cat:'Arts',ipa:'/larkitetˈtuː.ra/',ex:'Roma ha un\'architettura meravigliosa.',exEn:'Rome has marvellous architecture.'},
    {it:'il Rinascimento',en:'the Renaissance',cat:'Arts',ipa:'/il rinaʃʃiˈmɛn.to/',ex:'Il Rinascimento ha avuto inizio a Firenze.',exEn:'The Renaissance began in Florence.'},
    {it:'il patrimonio',en:'heritage',cat:'Arts',ipa:'/il patriˈmoː.njo/',ex:'Il patrimonio culturale italiano.',exEn:'The Italian cultural heritage.'},
    {it:'la tradizione',en:'tradition',cat:'Arts',ipa:'/la traditˈtsjoː.ne/',ex:'Una tradizione antica.',exEn:'An ancient tradition.'},
    {it:'la cultura',en:'culture',cat:'Arts',ipa:'/la kulˈtuː.ra/',ex:'La cultura italiana è ricchissima.',exEn:'Italian culture is very rich.'},
    {it:'il festival',en:'festival',cat:'Arts',ipa:'/il feˈstiː.val/',ex:'Il Festival di Venezia.',exEn:'The Venice Festival.'},
    {it:'la mostra',en:'the exhibition',cat:'Arts',ipa:'/la ˈmɔs.tra/',ex:'La mostra apre domani.',exEn:'The exhibition opens tomorrow.'},
    {it:'il capolavoro',en:'the masterpiece',cat:'Arts',ipa:'/il kapolaˈvoː.ro/',ex:'La Gioconda è un capolavoro.',exEn:'The Mona Lisa is a masterpiece.'},
    {it:'affrescare',en:'to fresco',cat:'Arts',ipa:'/afresˈkaː.re/',ex:'Michelangelo affresca la Cappella Sistina.',exEn:'Michelangelo frescoes the Sistine Chapel.'},
    {it:'la Cappella Sistina',en:'the Sistine Chapel',cat:'Arts',ipa:'/la kapˈpɛl.la sisˈtiː.na/',ex:'La Cappella Sistina è stupenda.',exEn:'The Sistine Chapel is stunning.'},
    {it:'il Colosseo',en:'the Colosseum',cat:'Arts',ipa:'/il kolosˈsɛː.o/',ex:'Il Colosseo è a Roma.',exEn:'The Colosseum is in Rome.'},
    {it:'il Duomo',en:'the cathedral',cat:'Arts',ipa:'/il ˈdwɔː.mo/',ex:'Il Duomo di Milano è famoso.',exEn:'Milan Cathedral is famous.'},
    {it:'la fontana',en:'the fountain',cat:'Arts',ipa:'/la fonˈtaː.na/',ex:'La Fontana di Trevi.',exEn:'The Trevi Fountain.'},
    {it:'il mosaico',en:'the mosaic',cat:'Arts',ipa:'/il moˈzaː.i.ko/',ex:'I mosaici di Ravenna sono antichi.',exEn:'The mosaics of Ravenna are ancient.'},
    {it:'la ceramica',en:'ceramics / pottery',cat:'Arts',ipa:'/la tʃeˈraː.mi.ka/',ex:'La ceramica di Faenza.',exEn:'The ceramics of Faenza.'},
    {it:'la pittura',en:'painting (art)',cat:'Arts',ipa:'/la pitˈtuː.ra/',ex:'La pittura murale.',exEn:'Mural painting.'},
    {it:'creativo',en:'creative',cat:'Arts',ipa:'/kreaˈtiː.vo/',ex:'È un artista molto creativo.',exEn:'He\'s a very creative artist.'},
    {it:'ispirato',en:'inspired',cat:'Arts',ipa:'/ispiraˈto/',ex:'Un\'opera ispirata.',exEn:'An inspired work.'},
    {it:'classico',en:'classical / classic',cat:'Arts',ipa:'/ˈklas.si.ko/',ex:'Musica classica italiana.',exEn:'Italian classical music.'},
    {it:'contemporaneo',en:'contemporary',cat:'Arts',ipa:'/kontempoˈraː.neo/',ex:'Arte contemporanea.',exEn:'Contemporary art.'},
  ]
};

window.PACK_arts.words.push(
  {it:'il disegno',en:'drawing',cat:'Arts',ipa:'/il diˈzeɲ.ɲo/',ex:'Un disegno a matita.',exEn:'A pencil drawing.'},
  {it:'dipingere',en:'to paint',cat:'Arts',ipa:'/diˈpin.dʒe.re/',ex:'Dipinge ad acquerello.',exEn:'He paints in watercolour.'},
  {it:'scolpire',en:'to sculpt',cat:'Arts',ipa:'/skolˈpiː.re/',ex:'Scolpisce il marmo.',exEn:'She sculpts marble.'},
  {it:'la tela',en:'canvas',cat:'Arts',ipa:'/la ˈteː.la/',ex:'Dipinge su tela.',exEn:'He paints on canvas.'},
  {it:'il pennello',en:'paintbrush',cat:'Arts',ipa:'/il penˈnɛl.lo/',ex:'Un pennello fine.',exEn:'A fine paintbrush.'},
  {it:'la matita',en:'pencil',cat:'Arts',ipa:'/la maˈtiː.ta/',ex:'Disegna con la matita.',exEn:'She draws with pencil.'},
  {it:'il carboncino',en:'charcoal',cat:'Arts',ipa:'/il karbonˈtʃiː.no/',ex:'Un disegno a carboncino.',exEn:'A charcoal drawing.'},
  {it:'l\'acquarello',en:'watercolour',cat:'Arts',ipa:'/lakwaˈrɛl.lo/',ex:'Un bel acquarello.',exEn:'A beautiful watercolour.'},
  {it:'l\'affresco',en:'fresco',cat:'Arts',ipa:'/lafˈfrɛs.ko/',ex:'Gli affreschi della Cappella Sistina.',exEn:'The Sistine Chapel frescoes.'},
  {it:'il marmo',en:'marble',cat:'Arts',ipa:'/il ˈmar.mo/',ex:'La scultura in marmo.',exEn:'The marble sculpture.'},
  {it:'il bronzo',en:'bronze',cat:'Arts',ipa:'/il ˈbron.dzo/',ex:'Un bronzo antico.',exEn:'An ancient bronze.'},
  {it:'l\'incisione',en:'engraving',cat:'Arts',ipa:'/lintʃiˈzjoː.ne/',ex:'Un\'incisione su rame.',exEn:'An engraving on copper.'},
  {it:'la batteria',en:'drums',cat:'Arts',ipa:'/il batteˈriː.a/',ex:'Suono la batteria.',exEn:'I play the drums.'},
  {it:'il sassofono',en:'saxophone',cat:'Arts',ipa:'/il sasˈsɔː.fo.no/',ex:'Suono il sassofono.',exEn:'I play the saxophone.'},
  {it:'il clarinetto',en:'clarinet',cat:'Arts',ipa:'/il klariˈnɛt.to/',ex:'Suono il clarinetto.',exEn:'I play the clarinet.'},
  {it:'il flauto',en:'flute',cat:'Arts',ipa:'/il ˈflaʊ.to/',ex:'Suono il flauto.',exEn:'I play the flute.'},
  {it:'la tromba',en:'trumpet',cat:'Arts',ipa:'/la ˈtrom.ba/',ex:'Suono la tromba.',exEn:'I play the trumpet.'},
  {it:'il coro',en:'choir',cat:'Arts',ipa:'/il ˈkoː.ro/',ex:'Canto nel coro.',exEn:'I sing in the choir.'},
  {it:'l\'orchestra',en:'orchestra',cat:'Arts',ipa:'/lorˈkɛs.tra/',ex:'L\'orchestra suona bene.',exEn:'The orchestra plays well.'},
  {it:'la sinfonia',en:'symphony',cat:'Arts',ipa:'/la simfoˈniː.a/',ex:'La Quinta Sinfonia.',exEn:'The Fifth Symphony.'},
  {it:'l\'aria',en:'aria',cat:'Arts',ipa:'/ˈlaː.rja/',ex:'Un\'aria di Verdi.',exEn:'A Verdi aria.'},
  {it:'il tenore',en:'tenor',cat:'Arts',ipa:'/il teˈnoː.re/',ex:'Un famoso tenore italiano.',exEn:'A famous Italian tenor.'},
  {it:'il soprano',en:'soprano',cat:'Arts',ipa:'/il soˈpraː.no/',ex:'Una soprano straordinaria.',exEn:'An extraordinary soprano.'},
  {it:'il balletto',en:'ballet',cat:'Arts',ipa:'/il balˈlɛt.to/',ex:'Vado a vedere il balletto.',exEn:'I\'m going to see the ballet.'},
  {it:'la danza contemporanea',en:'contemporary dance',cat:'Arts',ipa:'/la ˈdan.tsa kontempoˈraː.nea/',ex:'La danza contemporanea.',exEn:'Contemporary dance.'},
  {it:'il romanzo',en:'novel',cat:'Arts',ipa:'/il roˈman.tso/',ex:'Leggo un romanzo giallo.',exEn:'I\'m reading a crime novel.'},
  {it:'la poesia',en:'poetry',cat:'Arts',ipa:'/la poeˈziː.a/',ex:'Leggo poesia italiana.',exEn:'I read Italian poetry.'},
  {it:'il poeta',en:'poet',cat:'Arts',ipa:'/il poˈɛː.ta/',ex:'Dante è un grande poeta.',exEn:'Dante is a great poet.'},
  {it:'l\'autore',en:'author',cat:'Arts',ipa:'/lawˈtoː.re/',ex:'Chi è l\'autore?',exEn:'Who is the author?'},
  {it:'la letteratura',en:'literature',cat:'Arts',ipa:'/la letteraˈtuː.ra/',ex:'La letteratura del Novecento.',exEn:'Twentieth-century literature.'},
  {it:'l\'architettura',en:'architecture',cat:'Arts',ipa:'/larkitetˈtuː.ra/',ex:'L\'architettura rinascimentale.',exEn:'Renaissance architecture.'},
  {it:'il capolavoro',en:'masterpiece',cat:'Arts',ipa:'/il kapolaˈvoː.ro/',ex:'La Gioconda è un capolavoro.',exEn:'The Mona Lisa is a masterpiece.'},
  {it:'il Rinascimento',en:'the Renaissance',cat:'Arts',ipa:'/il rinaʃʃiˈmɛn.to/',ex:'Il Rinascimento italiano.',exEn:'The Italian Renaissance.'},
  {it:'il patrimonio',en:'heritage',cat:'Arts',ipa:'/il patriˈmoː.njo/',ex:'Il patrimonio UNESCO.',exEn:'UNESCO heritage.'},
  {it:'la tradizione',en:'tradition',cat:'Arts',ipa:'/la traditˈtsjoː.ne/',ex:'Una tradizione antica.',exEn:'An ancient tradition.'},
  {it:'la mostra',en:'exhibition',cat:'Arts',ipa:'/la ˈmɔs.tra/',ex:'La mostra apre domani.',exEn:'The exhibition opens tomorrow.'},
  {it:'la retrospettiva',en:'retrospective',cat:'Arts',ipa:'/la retrospetˈtiː.va/',ex:'Una retrospettiva di Modigliani.',exEn:'A Modigliani retrospective.'},
  {it:'il Colosseo',en:'the Colosseum',cat:'Arts',ipa:'/il kolosˈsɛː.o/',ex:'Il Colosseo è a Roma.',exEn:'The Colosseum is in Rome.'},
  {it:'il Duomo',en:'the cathedral',cat:'Arts',ipa:'/il ˈdwɔː.mo/',ex:'Il Duomo di Milano.',exEn:'Milan Cathedral.'},
  {it:'la fontana',en:'fountain',cat:'Arts',ipa:'/la fonˈtaː.na/',ex:'La Fontana di Trevi.',exEn:'The Trevi Fountain.'},
  {it:'classico',en:'classical',cat:'Arts',ipa:'/ˈklas.si.ko/',ex:'Musica classica italiana.',exEn:'Italian classical music.'},
  {it:'contemporaneo',en:'contemporary',cat:'Arts',ipa:'/kontempoˈraː.neo/',ex:'Arte contemporanea.',exEn:'Contemporary art.'},
  {it:'astratto',en:'abstract',cat:'Arts',ipa:'/asˈtrat.to/',ex:'Un dipinto astratto.',exEn:'An abstract painting.'},
  {it:'figurativo',en:'figurative',cat:'Arts',ipa:'/fiɡuraˈtiː.vo/',ex:'Arte figurativa.',exEn:'Figurative art.'},
  {it:'impressionismo',en:'impressionism',cat:'Arts',ipa:'/impressjoˈniz.mo/',ex:'L\'impressionismo francese.',exEn:'French impressionism.'},
  {it:'il futurismo',en:'futurism',cat:'Arts',ipa:'/il futuˈriz.mo/',ex:'Il futurismo italiano.',exEn:'Italian futurism.'},
  {it:'il barocco',en:'baroque',cat:'Arts',ipa:'/il baˈrɔk.ko/',ex:'L\'arte barocca.',exEn:'Baroque art.'},
  {it:'il rinascimentale',en:'Renaissance (adj)',cat:'Arts',ipa:'/il rinaʃʃimenˈtaː.le/',ex:'Un palazzo rinascimentale.',exEn:'A Renaissance palace.'},
  {it:'ispirato',en:'inspired',cat:'Arts',ipa:'/ispiraˈto/',ex:'Un\'opera ispirata.',exEn:'An inspired work.'}
);
