window.PACK_body = {
  id:'body', name:'The Human Body', emoji:'🫀',
  words:[
    {it:'il corpo',en:'the body',cat:'Body',ipa:'/il ˈkor.po/',ex:'Il corpo umano è complesso.',exEn:'The human body is complex.'},
    {it:'la testa',en:'the head',cat:'Body',ipa:'/la ˈtɛs.ta/',ex:'Ho mal di testa.',exEn:'I have a headache.'},
    {it:'il viso',en:'the face',cat:'Body',ipa:'/il ˈviː.zo/',ex:'Ha un bel viso.',exEn:'She has a beautiful face.'},
    {it:'i capelli',en:'the hair',cat:'Body',ipa:'/i kaˈpɛl.li/',ex:'Ha i capelli lunghi.',exEn:'She has long hair.'},
    {it:'gli occhi',en:'the eyes',cat:'Body',ipa:'/ʎi ˈɔk.ki/',ex:'Ha gli occhi azzurri.',exEn:'He has blue eyes.'},
    {it:'il naso',en:'the nose',cat:'Body',ipa:'/il ˈnaː.zo/',ex:'Ho il naso chiuso.',exEn:'My nose is blocked.'},
    {it:'la bocca',en:'the mouth',cat:'Body',ipa:'/la ˈbɔk.ka/',ex:'Apri la bocca.',exEn:'Open your mouth.'},
    {it:'i denti',en:'the teeth',cat:'Body',ipa:'/i ˈdɛn.ti/',ex:'Lavati i denti.',exEn:'Brush your teeth.'},
    {it:'le labbra',en:'the lips',cat:'Body',ipa:'/le ˈlab.bra/',ex:'Ha le labbra rosse.',exEn:'She has red lips.'},
    {it:'le orecchie',en:'the ears',cat:'Body',ipa:'/le oˈrɛk.kje/',ex:'Ho mal alle orecchie.',exEn:'My ears hurt.'},
    {it:'il collo',en:'the neck',cat:'Body',ipa:'/il ˈkɔl.lo/',ex:'Ho mal di collo.',exEn:'I have a sore neck.'},
    {it:'le spalle',en:'the shoulders',cat:'Body',ipa:'/le ˈspal.le/',ex:'Ho le spalle tese.',exEn:'My shoulders are tense.'},
    {it:'il petto',en:'the chest',cat:'Body',ipa:'/il ˈpɛt.to/',ex:'Ho un dolore al petto.',exEn:'I have chest pain.'},
    {it:'lo stomaco',en:'the stomach',cat:'Body',ipa:'/lo ˈstoː.ma.ko/',ex:'Ho mal di stomaco.',exEn:'I have a stomach ache.'},
    {it:'la schiena',en:'the back',cat:'Body',ipa:'/la ˈskjeː.na/',ex:'Ho mal di schiena.',exEn:'I have a backache.'},
    {it:'il braccio',en:'the arm',cat:'Body',ipa:'/il ˈbrat.tʃo/',ex:'Mi sono fatto male al braccio.',exEn:'I hurt my arm.'},
    {it:'la mano',en:'the hand',cat:'Body',ipa:'/la ˈmaː.no/',ex:'Lavati le mani.',exEn:'Wash your hands.'},
    {it:'le dita',en:'the fingers',cat:'Body',ipa:'/le ˈdiː.ta/',ex:'Ha le dita lunghe.',exEn:'She has long fingers.'},
    {it:'il pollice',en:'the thumb',cat:'Body',ipa:'/il ˈpɔl.li.tʃe/',ex:'Mi sono fatto male al pollice.',exEn:'I hurt my thumb.'},
    {it:'la gamba',en:'the leg',cat:'Body',ipa:'/la ˈɡam.ba/',ex:'Mi fa male la gamba.',exEn:'My leg hurts.'},
    {it:'il ginocchio',en:'the knee',cat:'Body',ipa:'/il dʒiˈnɔk.kjo/',ex:'Ho male al ginocchio.',exEn:'My knee hurts.'},
    {it:'il piede',en:'the foot',cat:'Body',ipa:'/il ˈpjeː.de/',ex:'Mi fa male il piede.',exEn:'My foot hurts.'},
    {it:'le dita del piede',en:'the toes',cat:'Body',ipa:'/le ˈdiː.ta del ˈpjeː.de/',ex:'Mi fa male un dito del piede.',exEn:'One of my toes hurts.'},
    {it:'il cuore',en:'the heart',cat:'Body',ipa:'/il ˈkwɔː.re/',ex:'Il cuore batte forte.',exEn:'The heart beats strongly.'},
    {it:'il polmone',en:'the lung',cat:'Body',ipa:'/il polˈmoː.ne/',ex:'Fumare fa male ai polmoni.',exEn:'Smoking is bad for the lungs.'},
    {it:'il fegato',en:'the liver',cat:'Body',ipa:'/il ˈfɛː.ɡa.to/',ex:'Ho un problema al fegato.',exEn:'I have a liver problem.'},
    {it:'il rene',en:'the kidney',cat:'Body',ipa:'/il ˈrɛː.ne/',ex:'Il rene filtra il sangue.',exEn:'The kidney filters the blood.'},
    {it:'il cervello',en:'the brain',cat:'Body',ipa:'/il tʃerˈvɛl.lo/',ex:'Il cervello è l\'organo più importante.',exEn:'The brain is the most important organ.'},
    {it:'il sangue',en:'the blood',cat:'Body',ipa:'/il ˈsaŋ.ɡwe/',ex:'Il sangue è rosso.',exEn:'Blood is red.'},
    {it:'le ossa',en:'the bones',cat:'Body',ipa:'/le ˈɔs.sa/',ex:'Le ossa si rompono.',exEn:'Bones break.'},
    {it:'la pelle',en:'the skin',cat:'Body',ipa:'/la ˈpɛl.le/',ex:'Ho la pelle sensibile.',exEn:'I have sensitive skin.'},
    {it:'i muscoli',en:'the muscles',cat:'Body',ipa:'/i ˈmus.ko.li/',ex:'Ho i muscoli doloranti.',exEn:'My muscles are sore.'},
    {it:'il gomito',en:'the elbow',cat:'Body',ipa:'/il ˈɡɔː.mi.to/',ex:'Mi sono fatto male al gomito.',exEn:'I hurt my elbow.'},
    {it:'il polso',en:'the wrist',cat:'Body',ipa:'/il ˈpol.so/',ex:'Ho male al polso.',exEn:'My wrist hurts.'},
    {it:'la caviglia',en:'the ankle',cat:'Body',ipa:'/la kaˈviʎ.ʎa/',ex:'Mi sono storto la caviglia.',exEn:'I twisted my ankle.'},
    {it:'il mento',en:'the chin',cat:'Body',ipa:'/il ˈmɛn.to/',ex:'Ha un mento prominente.',exEn:'He has a prominent chin.'},
    {it:'le guance',en:'the cheeks',cat:'Body',ipa:'/le ˈɡwan.tʃe/',ex:'Ha le guance rosse.',exEn:'She has red cheeks.'},
    {it:'la fronte',en:'the forehead',cat:'Body',ipa:'/la ˈfron.te/',ex:'Ha la fronte sudata.',exEn:'His forehead is sweaty.'},
    {it:'le sopracciglia',en:'the eyebrows',cat:'Body',ipa:'/le soˈprat.tʃiʎ.ʎa/',ex:'Ha le sopracciglia scure.',exEn:'She has dark eyebrows.'},
    {it:'le ciglia',en:'the eyelashes',cat:'Body',ipa:'/le ˈtʃiʎ.ʎa/',ex:'Ha le ciglia lunghe.',exEn:'She has long eyelashes.'},
    {it:'la lingua',en:'the tongue / language',cat:'Body',ipa:'/la ˈliŋ.ɡwa/',ex:'Mi sono morso la lingua.',exEn:'I bit my tongue.'},
    {it:'la gola',en:'the throat',cat:'Body',ipa:'/la ˈɡɔː.la/',ex:'Ho mal di gola.',exEn:'I have a sore throat.'},
    {it:'le unghie',en:'the nails',cat:'Body',ipa:'/le ˈuŋ.ɡje/',ex:'Si è rotta un\'unghia.',exEn:'She broke a nail.'},
    {it:'la barba',en:'the beard',cat:'Body',ipa:'/la ˈbar.ba/',ex:'Ha la barba lunga.',exEn:'He has a long beard.'},
    {it:'i baffi',en:'the moustache',cat:'Body',ipa:'/i ˈbaf.fi/',ex:'Ha i baffi grigi.',exEn:'He has a grey moustache.'},
    {it:'i fianchi',en:'the hips',cat:'Body',ipa:'/i ˈfjaŋ.ki/',ex:'Ha i fianchi larghi.',exEn:'She has wide hips.'},
    {it:'il ventre',en:'the belly / abdomen',cat:'Body',ipa:'/il ˈvɛn.tre/',ex:'Fa male il ventre.',exEn:'The belly hurts.'},
    {it:'le costole',en:'the ribs',cat:'Body',ipa:'/le ˈkɔs.to.le/',ex:'Mi fa male una costola.',exEn:'One of my ribs hurts.'},
    {it:'il tallone',en:'the heel',cat:'Body',ipa:'/il talˈloː.ne/',ex:'Ho male al tallone.',exEn:'My heel hurts.'},
    {it:'la colonna vertebrale',en:'the spine',cat:'Body',ipa:'/la koˈlɔn.na verteˈbraː.le/',ex:'Problemi alla colonna vertebrale.',exEn:'Spine problems.'},
    {it:'il nervo',en:'the nerve',cat:'Body',ipa:'/il ˈnɛr.vo/',ex:'Mi ha toccato un nervo.',exEn:'He touched a nerve.'},
  ]
};

window.PACK_body.words.push(
  {it:'la tempia',en:'temple (head)',cat:'Body',ipa:'/la ˈtɛm.pja/',ex:'Mi fa male la tempia.',exEn:'My temple hurts.'},
  {it:'il cranio',en:'skull',cat:'Body',ipa:'/il ˈkraː.njo/',ex:'Il cranio protegge il cervello.',exEn:'The skull protects the brain.'},
  {it:'la mascella',en:'jaw',cat:'Body',ipa:'/la maˈʃɛl.la/',ex:'Ho male alla mascella.',exEn:'My jaw hurts.'},
  {it:'la gengiva',en:'gum (mouth)',cat:'Body',ipa:'/la dʒenˈdʒiː.va/',ex:'Mi fanno male le gengive.',exEn:'My gums hurt.'},
  {it:'le tonsille',en:'tonsils',cat:'Body',ipa:'/le tonˈsil.le/',ex:'Ho le tonsille infiammate.',exEn:'My tonsils are inflamed.'},
  {it:'il mignolo',en:'little finger / pinky',cat:'Body',ipa:'/il miɲˈɲɔː.lo/',ex:'Mi sono fatto male al mignolo.',exEn:'I hurt my little finger.'},
  {it:'l\'anulare',en:'ring finger',cat:'Body',ipa:'/lanuˈlaː.re/',ex:'L\'anello sull\'anulare.',exEn:'The ring on the ring finger.'},
  {it:'il medio',en:'middle finger',cat:'Body',ipa:'/il ˈmɛː.djo/',ex:'Il medio è il dito più lungo.',exEn:'The middle finger is the longest.'},
  {it:'l\'indice',en:'index finger',cat:'Body',ipa:'/linˈdiː.tʃe/',ex:'Punta con l\'indice.',exEn:'Point with your index finger.'},
  {it:'la nocca',en:'knuckle',cat:'Body',ipa:'/la ˈnɔk.ka/',ex:'Si è fatto male alle nocche.',exEn:'He hurt his knuckles.'},
  {it:'il palmo',en:'palm',cat:'Body',ipa:'/il ˈpal.mo/',ex:'Il palmo della mano.',exEn:'The palm of the hand.'},
  {it:'il polpaccio',en:'calf (leg)',cat:'Body',ipa:'/il polˈpat.tʃo/',ex:'Ho i polpacci doloranti.',exEn:'My calves are sore.'},
  {it:'la coscia',en:'thigh',cat:'Body',ipa:'/la ˈkɔʃ.ʃa/',ex:'Mi fa male la coscia.',exEn:'My thigh hurts.'},
  {it:'il gluteo',en:'buttock / glute',cat:'Body',ipa:'/il ˈɡluː.te.o/',ex:'I glutei sono tesi.',exEn:'The glutes are tight.'},
  {it:'l\'inguine',en:'groin',cat:'Body',ipa:'/ˈliŋ.ɡwi.ne/',ex:'Ho male all\'inguine.',exEn:'My groin hurts.'},
  {it:'il diaframma',en:'diaphragm',cat:'Body',ipa:'/il djaˈfram.ma/',ex:'Il diaframma aiuta la respirazione.',exEn:'The diaphragm helps breathing.'},
  {it:'la cartilagine',en:'cartilage',cat:'Body',ipa:'/la kartiˈlaː.dʒi.ne/',ex:'Ho la cartilagine del ginocchio consumata.',exEn:'I have worn knee cartilage.'},
  {it:'il tendine',en:'tendon',cat:'Body',ipa:'/il ˈtɛn.di.ne/',ex:'Si è rotto il tendine.',exEn:'He ruptured the tendon.'},
  {it:'il legamento',en:'ligament',cat:'Body',ipa:'/il leɡaˈmɛn.to/',ex:'Hai un legamento leso.',exEn:'You have a torn ligament.'},
  {it:'la vertebra',en:'vertebra',cat:'Body',ipa:'/la ˈvɛr.te.bra/',ex:'Una vertebra spostata.',exEn:'A displaced vertebra.'},
  {it:'la vena',en:'vein',cat:'Body',ipa:'/la ˈveː.na/',ex:'Si vede la vena.',exEn:'You can see the vein.'},
  {it:'l\'arteria',en:'artery',cat:'Body',ipa:'/larˈtɛː.rja/',ex:'L\'arteria carotide.',exEn:'The carotid artery.'},
  {it:'la pressione sanguigna',en:'blood pressure',cat:'Body',ipa:'/la presˈsjoː.ne saŋˈɡwiɲ.ɲa/',ex:'La pressione sanguigna alta.',exEn:'High blood pressure.'},
  {it:'il polso',en:'pulse',cat:'Body',ipa:'/il ˈpol.so/',ex:'Il polso è regolare.',exEn:'The pulse is regular.'},
  {it:'la respirazione',en:'breathing',cat:'Body',ipa:'/la respiraˈtsjoː.ne/',ex:'La respirazione è affannosa.',exEn:'Breathing is laboured.'},
  {it:'la digestione',en:'digestion',cat:'Body',ipa:'/la didʒesˈtjoː.ne/',ex:'Ho problemi di digestione.',exEn:'I have digestion problems.'},
  {it:'il metabolismo',en:'metabolism',cat:'Body',ipa:'/il metabolˈiz.mo/',ex:'Ho un metabolismo lento.',exEn:'I have a slow metabolism.'},
  {it:'la cicatrice',en:'scar',cat:'Body',ipa:'/la tʃikaˈtriː.tʃe/',ex:'Ho una cicatrice sul ginocchio.',exEn:'I have a scar on my knee.'},
  {it:'il bruciore',en:'burning sensation',cat:'Body',ipa:'/il bruˈtʃoː.re/',ex:'Sento un bruciore.',exEn:'I feel a burning sensation.'},
  {it:'il prurito',en:'itching',cat:'Body',ipa:'/il pruˈriː.to/',ex:'Ho un forte prurito.',exEn:'I have a strong itch.'},
  {it:'gonfiore',en:'swelling',cat:'Body',ipa:'/ɡonˈfjoː.re/',ex:'C\'è gonfiore alla caviglia.',exEn:'There\'s swelling at the ankle.'},
  {it:'la coordinazione',en:'coordination',cat:'Body',ipa:'/la koordinatˈtsjoː.ne/',ex:'Ha buona coordinazione.',exEn:'She has good coordination.'},
  {it:'l\'equilibrio',en:'balance',cat:'Body',ipa:'/lekwiˈliː.brjo/',ex:'Ha perso l\'equilibrio.',exEn:'He lost his balance.'},
  {it:'i riflessi',en:'reflexes',cat:'Body',ipa:'/i riˈflɛs.si/',ex:'Ha i riflessi pronti.',exEn:'He has quick reflexes.'},
  {it:'la forza',en:'strength',cat:'Body',ipa:'/la ˈfor.tsa/',ex:'Ha molta forza.',exEn:'She has great strength.'},
  {it:'la flessibilità',en:'flexibility',cat:'Body',ipa:'/la flesibiliˈta/',ex:'Lavoro sulla flessibilità.',exEn:'I work on my flexibility.'},
  {it:'la resistenza',en:'endurance',cat:'Body',ipa:'/la resiˈstɛn.tsa/',ex:'La mia resistenza fisica.',exEn:'My physical endurance.'},
  {it:'la velocità',en:'speed',cat:'Body',ipa:'/la velotʃiˈta/',ex:'Ha una velocità incredibile.',exEn:'He has incredible speed.'},
  {it:'l\'altezza',en:'height',cat:'Body',ipa:'/lalˈtɛt.tsa/',ex:'Qual è la tua altezza?',exEn:'What is your height?'},
  {it:'il peso',en:'weight',cat:'Body',ipa:'/il ˈpeː.zo/',ex:'Qual è il tuo peso?',exEn:'What is your weight?'},
  {it:'la sudorazione',en:'sweating',cat:'Body',ipa:'/la sudoraˈtsjoː.ne/',ex:'La sudorazione eccessiva.',exEn:'Excessive sweating.'},
  {it:'il battito cardiaco',en:'heartbeat',cat:'Body',ipa:'/il ˈbat.ti.to karˈdjaː.ko/',ex:'Il battito cardiaco accelera.',exEn:'The heartbeat accelerates.'},
  {it:'la febbre',en:'fever / temperature',cat:'Body',ipa:'/la ˈfɛb.bre/',ex:'Ha trentanove di febbre.',exEn:'She has a temperature of 39.'},
  {it:'la statura',en:'stature / build',cat:'Body',ipa:'/la staˈtuː.ra/',ex:'Ha una statura media.',exEn:'He has an average build.'},
  {it:'il fisico',en:'physique',cat:'Body',ipa:'/il ˈfiː.zi.ko/',ex:'Ha un bel fisico.',exEn:'He has a nice physique.'},
  {it:'magro',en:'thin / slim',cat:'Body',ipa:'/ˈmaː.ɡro/',ex:'È molto magro.',exEn:'He is very thin.'},
  {it:'robusto',en:'sturdy / robust',cat:'Body',ipa:'/roˈbus.to/',ex:'Ha un fisico robusto.',exEn:'He has a sturdy build.'},
  {it:'sano',en:'healthy',cat:'Body',ipa:'/ˈsaː.no/',ex:'È sano come un pesce.',exEn:'He is as fit as a fiddle.'},
  {it:'in forma',en:'in shape',cat:'Body',ipa:'/in ˈfor.ma/',ex:'Sei in gran forma!',exEn:'You\'re in great shape!'},
  {it:'fuori forma',en:'out of shape',cat:'Body',ipa:'/ˈfwɔː.ri ˈfor.ma/',ex:'Mi sento fuori forma.',exEn:'I feel out of shape.'}
);
