window.PACK_food = {
  id:'food', name:'At the Restaurant', emoji:'🍝',
  words:[
    {it:'il menu',en:'the menu',cat:'Food',ipa:'/il ˈmɛ.nu/',ex:'Posso avere il menu?',exEn:'Can I have the menu?'},
    {it:'il conto',en:'the bill / check',cat:'Food',ipa:'/il ˈkɔn.to/',ex:'Il conto, per favore.',exEn:'The bill, please.'},
    {it:'acqua',en:'water',cat:'Food',ipa:'/ˈak.kwa/',ex:'Un\'acqua naturale, grazie.',exEn:'Still water, thank you.'},
    {it:'vino',en:'wine',cat:'Food',ipa:'/ˈviː.no/',ex:'Un bicchiere di vino rosso.',exEn:'A glass of red wine.'},
    {it:'pane',en:'bread',cat:'Food',ipa:'/ˈpaː.ne/',ex:'Il pane è fresco.',exEn:'The bread is fresh.'},
    {it:'pasta',en:'pasta',cat:'Food',ipa:'/ˈpas.ta/',ex:'La pasta è deliziosa!',exEn:'The pasta is delicious!'},
    {it:'carne',en:'meat',cat:'Food',ipa:'/ˈkar.ne/',ex:'Non mangio carne.',exEn:'I don\'t eat meat.'},
    {it:'pesce',en:'fish',cat:'Food',ipa:'/ˈpeʃ.ʃe/',ex:'Il pesce del giorno è buono.',exEn:'The fish of the day is good.'},
    {it:'dolce',en:'dessert / sweet',cat:'Food',ipa:'/ˈdɔl.tʃe/',ex:'Quale dolce avete?',exEn:'What desserts do you have?'},
    {it:'caffè',en:'coffee',cat:'Food',ipa:'/kafˈfɛ/',ex:'Un caffè ristretto, per favore.',exEn:'A short espresso, please.'},
    {it:'formaggio',en:'cheese',cat:'Food',ipa:'/forˈmad.dʒo/',ex:'Il formaggio italiano è famoso.',exEn:'Italian cheese is famous.'},
    {it:'verdura',en:'vegetables',cat:'Food',ipa:'/verˈduː.ra/',ex:'Vorrei più verdura.',exEn:'I\'d like more vegetables.'},
    {it:'frutta',en:'fruit',cat:'Food',ipa:'/ˈfrut.ta/',ex:'La frutta è fresca oggi.',exEn:'The fruit is fresh today.'},
    {it:'antipasto',en:'starter / appetizer',cat:'Food',ipa:'/ˌan.tiˈpas.to/',ex:'Come antipasto prendo le olive.',exEn:'As a starter I\'ll have the olives.'},
    {it:'bistecca',en:'steak',cat:'Food',ipa:'/bisˈtek.ka/',ex:'La bistecca è al sangue.',exEn:'The steak is rare.'},
    {it:'pizza',en:'pizza',cat:'Food',ipa:'/ˈpit.tsa/',ex:'La pizza napoletana è la migliore.',exEn:'Neapolitan pizza is the best.'},
    {it:'il primo',en:'first course',cat:'Food',ipa:'/il ˈpriː.mo/',ex:'Come primo prendo la pasta.',exEn:'For the first course I\'ll have pasta.'},
    {it:'il secondo',en:'main course',cat:'Food',ipa:'/il seˈkɔn.do/',ex:'Come secondo, la bistecca.',exEn:'For the main, the steak.'},
    {it:'il contorno',en:'side dish',cat:'Food',ipa:'/il konˈtor.no/',ex:'Che contorno prende?',exEn:'What side dish will you have?'},
    {it:'l\'insalata',en:'salad',cat:'Food',ipa:'/linˈsa.laː.ta/',ex:'Un\'insalata mista, per favore.',exEn:'A mixed salad, please.'},
    {it:'la minestra',en:'soup',cat:'Food',ipa:'/la miˈnes.tra/',ex:'La minestra è calda.',exEn:'The soup is hot.'},
    {it:'il risotto',en:'risotto',cat:'Food',ipa:'/il riˈzɔt.to/',ex:'Il risotto ai funghi è ottimo.',exEn:'The mushroom risotto is excellent.'},
    {it:'gli spaghetti',en:'spaghetti',cat:'Food',ipa:'/ʎi spaˈɡet.ti/',ex:'Gli spaghetti alla carbonara sono buoni.',exEn:'Spaghetti carbonara is good.'},
    {it:'il tiramisù',en:'tiramisu',cat:'Food',ipa:'/il tiramiˈsuː/',ex:'Il tiramisù è il mio dolce preferito.',exEn:'Tiramisu is my favourite dessert.'},
    {it:'il gelato',en:'ice cream',cat:'Food',ipa:'/il dʒeˈlaː.to/',ex:'Un gelato al cioccolato, per favore.',exEn:'A chocolate ice cream, please.'},
    {it:'la birra',en:'beer',cat:'Food',ipa:'/la ˈbir.ra/',ex:'Una birra alla spina, grazie.',exEn:'A draught beer, please.'},
    {it:'il succo',en:'juice',cat:'Food',ipa:'/il ˈsuk.ko/',ex:'Un succo d\'arancia, per favore.',exEn:'An orange juice, please.'},
    {it:'il tè',en:'tea',cat:'Food',ipa:'/il tɛ/',ex:'Un tè al latte, grazie.',exEn:'A tea with milk, please.'},
    {it:'l\'olio',en:'oil',cat:'Food',ipa:'/ˈlɔː.ljo/',ex:'Posso avere l\'olio d\'oliva?',exEn:'Can I have the olive oil?'},
    {it:'il sale',en:'salt',cat:'Food',ipa:'/il ˈsaː.le/',ex:'Puoi passarmi il sale?',exEn:'Can you pass me the salt?'},
    {it:'il pepe',en:'pepper',cat:'Food',ipa:'/il ˈpeː.pe/',ex:'Un po\' di pepe, grazie.',exEn:'A little pepper, please.'},
    {it:'il burro',en:'butter',cat:'Food',ipa:'/il ˈbur.ro/',ex:'Pane e burro, per favore.',exEn:'Bread and butter, please.'},
    {it:'le uova',en:'eggs',cat:'Food',ipa:'/le ˈwɔː.va/',ex:'Uova strapazzate per colazione.',exEn:'Scrambled eggs for breakfast.'},
    {it:'il pollo',en:'chicken',cat:'Food',ipa:'/il ˈpɔl.lo/',ex:'Il pollo arrosto è ottimo.',exEn:'The roast chicken is excellent.'},
    {it:'il maiale',en:'pork',cat:'Food',ipa:'/il maˈjaː.le/',ex:'La porchetta è maiale arrosto.',exEn:'Porchetta is roast pork.'},
    {it:'l\'agnello',en:'lamb',cat:'Food',ipa:'/laɲˈɲɛl.lo/',ex:'L\'agnello alla griglia è buono.',exEn:'Grilled lamb is good.'},
    {it:'i funghi',en:'mushrooms',cat:'Food',ipa:'/i ˈfuŋ.ɡi/',ex:'I funghi porcini sono deliziosi.',exEn:'Porcini mushrooms are delicious.'},
    {it:'i pomodori',en:'tomatoes',cat:'Food',ipa:'/i pomoˈdoː.ri/',ex:'I pomodori sono freschi.',exEn:'The tomatoes are fresh.'},
    {it:'le olive',en:'olives',cat:'Food',ipa:'/le ˈoː.li.ve/',ex:'Le olive nere sono ottime.',exEn:'Black olives are excellent.'},
    {it:'il prosciutto',en:'ham / prosciutto',cat:'Food',ipa:'/il proˈʃut.to/',ex:'Prosciutto crudo di Parma.',exEn:'Parma raw ham.'},
    {it:'la mozzarella',en:'mozzarella',cat:'Food',ipa:'/la mottsaˈrɛl.la/',ex:'Mozzarella di bufala fresca.',exEn:'Fresh buffalo mozzarella.'},
    {it:'il parmigiano',en:'parmesan',cat:'Food',ipa:'/il parmiˈdʒaː.no/',ex:'Parmigiano reggiano sul risotto.',exEn:'Parmesan on the risotto.'},
    {it:'la cipolla',en:'onion',cat:'Food',ipa:'/la tʃiˈpɔl.la/',ex:'La cipolla rossa è dolce.',exEn:'Red onion is sweet.'},
    {it:'l\'aglio',en:'garlic',cat:'Food',ipa:'/ˈlaʎ.ʎo/',ex:'L\'aglio dà sapore al sugo.',exEn:'Garlic gives flavour to the sauce.'},
    {it:'il basilico',en:'basil',cat:'Food',ipa:'/il baˈziː.li.ko/',ex:'Basilico fresco sulla pizza.',exEn:'Fresh basil on the pizza.'},
    {it:'la colazione',en:'breakfast',cat:'Food',ipa:'/la kolatˈtsjoː.ne/',ex:'La colazione è inclusa.',exEn:'Breakfast is included.'},
    {it:'il pranzo',en:'lunch',cat:'Food',ipa:'/il ˈpran.dzo/',ex:'Il pranzo è alle tredici.',exEn:'Lunch is at one o\'clock.'},
    {it:'la cena',en:'dinner',cat:'Food',ipa:'/la ˈtʃeː.na/',ex:'La cena è alle venti.',exEn:'Dinner is at eight.'},
    {it:'prenotare',en:'to book / reserve',cat:'Food',ipa:'/prenoˈtaː.re/',ex:'Vorrei prenotare un tavolo.',exEn:'I\'d like to book a table.'},
    {it:'il tavolo',en:'the table',cat:'Food',ipa:'/il ˈtaː.vo.lo/',ex:'Un tavolo per due, per favore.',exEn:'A table for two, please.'},
    {it:'il cameriere',en:'the waiter',cat:'Food',ipa:'/il kameˈrjeː.re/',ex:'Il cameriere è molto gentile.',exEn:'The waiter is very kind.'},
    {it:'ordinare',en:'to order',cat:'Food',ipa:'/ordiˈnaː.re/',ex:'Siete pronti per ordinare?',exEn:'Are you ready to order?'},
    {it:'la porzione',en:'the portion',cat:'Food',ipa:'/la porˈtsjoː.ne/',ex:'La porzione è molto grande.',exEn:'The portion is very large.'},
    {it:'l\'aperitivo',en:'aperitif',cat:'Food',ipa:'/laperiˈtiː.vo/',ex:'Prendiamo un aperitivo prima?',exEn:'Shall we have an aperitif first?'},
    {it:'senza',en:'without',cat:'Food',ipa:'/ˈsen.tsa/',ex:'Senza glutine, per favore.',exEn:'Without gluten, please.'},
    {it:'allergia',en:'allergy',cat:'Food',ipa:'/allerˈdʒiː.a/',ex:'Ho un\'allergia alle noci.',exEn:'I have a nut allergy.'},
    {it:'vegetariano',en:'vegetarian',cat:'Food',ipa:'/vedʒetaˈrjaː.no/',ex:'Avete piatti vegetariani?',exEn:'Do you have vegetarian dishes?'},
    {it:'vegano',en:'vegan',cat:'Food',ipa:'/veˈɡaː.no/',ex:'Sono vegano.',exEn:'I am vegan.'},
    {it:'delizioso',en:'delicious',cat:'Food',ipa:'/deliˈtsjoː.zo/',ex:'Questo è delizioso!',exEn:'This is delicious!'},
    {it:'caldo',en:'hot / warm',cat:'Food',ipa:'/ˈkal.do/',ex:'Il caffè è caldo.',exEn:'The coffee is hot.'},
    {it:'freddo',en:'cold',cat:'Food',ipa:'/ˈfrɛd.do/',ex:'L\'acqua è fredda.',exEn:'The water is cold.'},
    {it:'piccante',en:'spicy',cat:'Food',ipa:'/pikˈkan.te/',ex:'È molto piccante!',exEn:'It\'s very spicy!'},
    {it:'la torta',en:'cake',cat:'Food',ipa:'/la ˈtor.ta/',ex:'Una fetta di torta al cioccolato.',exEn:'A slice of chocolate cake.'},
    {it:'il cornetto',en:'croissant',cat:'Food',ipa:'/il korˈnet.to/',ex:'Un cornetto e un caffè.',exEn:'A croissant and a coffee.'},
    {it:'la spremuta',en:'fresh-squeezed juice',cat:'Food',ipa:'/la spreˈmuː.ta/',ex:'Una spremuta d\'arancia.',exEn:'A fresh orange juice.'},
    {it:'il coperto',en:'cover charge',cat:'Food',ipa:'/il koˈpɛr.to/',ex:'Il coperto è due euro.',exEn:'The cover charge is two euros.'},
    {it:'la mancia',en:'tip / gratuity',cat:'Food',ipa:'/la ˈman.tʃa/',ex:'Lasciamo la mancia?',exEn:'Shall we leave a tip?'},
    {it:'lo scontrino',en:'receipt',cat:'Food',ipa:'/lo skonˈtriː.no/',ex:'Posso avere lo scontrino?',exEn:'Can I have the receipt?'},
    {it:'la zuppa',en:'thick soup / stew',cat:'Food',ipa:'/la ˈdzup.pa/',ex:'Una zuppa di legumi.',exEn:'A legume soup.'},
    {it:'il riso',en:'rice',cat:'Food',ipa:'/il ˈriː.zo/',ex:'Il riso è cotto bene.',exEn:'The rice is well cooked.'},
    {it:'la farina',en:'flour',cat:'Food',ipa:'/la faˈriː.na/',ex:'Farina di grano duro.',exEn:'Durum wheat flour.'},
    {it:'il limone',en:'lemon',cat:'Food',ipa:'/il liˈmoː.ne/',ex:'Un po\' di limone sul pesce.',exEn:'A little lemon on the fish.'},
    {it:'la panna',en:'cream',cat:'Food',ipa:'/la ˈpan.na/',ex:'Panna montata sul dolce.',exEn:'Whipped cream on the dessert.'},
    {it:'il miele',en:'honey',cat:'Food',ipa:'/il ˈmjɛː.le/',ex:'Miele sulla ricotta.',exEn:'Honey on the ricotta.'},
    {it:'lo zucchero',en:'sugar',cat:'Food',ipa:'/lo ˈdzuk.ke.ro/',ex:'Senza zucchero, per favore.',exEn:'Without sugar, please.'},
    {it:'la cioccolata',en:'chocolate',cat:'Food',ipa:'/la tʃokkoˈlaː.ta/',ex:'Una tazza di cioccolata calda.',exEn:'A cup of hot chocolate.'},
    {it:'la focaccia',en:'focaccia bread',cat:'Food',ipa:'/la foˈkat.tʃa/',ex:'La focaccia genovese è ottima.',exEn:'Genoese focaccia is excellent.'},
    {it:'la bruschetta',en:'bruschetta',cat:'Food',ipa:'/la brusˈket.ta/',ex:'Bruschetta al pomodoro.',exEn:'Bruschetta with tomato.'},
    {it:'i frutti di mare',en:'seafood',cat:'Food',ipa:'/i ˈfrut.ti di ˈmaː.re/',ex:'I frutti di mare sono freschi.',exEn:'The seafood is fresh.'},
    {it:'le acciughe',en:'anchovies',cat:'Food',ipa:'/le aˈtʃuː.ɡe/',ex:'Pizza con le acciughe.',exEn:'Pizza with anchovies.'},
    {it:'la ricotta',en:'ricotta',cat:'Food',ipa:'/la riˈkɔt.ta/',ex:'Cannoli con ricotta fresca.',exEn:'Cannoli with fresh ricotta.'},
    {it:'il salame',en:'salami',cat:'Food',ipa:'/il saˈlaː.me/',ex:'Un panino con salame e formaggio.',exEn:'A sandwich with salami and cheese.'},
    {it:'gli gnocchi',en:'gnocchi',cat:'Food',ipa:'/ʎi ˈɲɔk.ki/',ex:'Gnocchi al pomodoro.',exEn:'Gnocchi with tomato sauce.'},
    {it:'la polenta',en:'polenta',cat:'Food',ipa:'/la poˈlɛn.ta/',ex:'Polenta con funghi trifolati.',exEn:'Polenta with sautéed mushrooms.'},
    {it:'il carpaccio',en:'carpaccio',cat:'Food',ipa:'/il karˈpat.tʃo/',ex:'Carpaccio di manzo con rucola.',exEn:'Beef carpaccio with rocket.'},
    {it:'la ribollita',en:'Tuscan bread soup',cat:'Food',ipa:'/la ribolˈliː.ta/',ex:'La ribollita è un piatto toscano.',exEn:'Ribollita is a Tuscan dish.'},
    {it:'fritto',en:'fried',cat:'Food',ipa:'/ˈfrit.to/',ex:'Pesce fritto misto.',exEn:'Mixed fried fish.'},
    {it:'arrosto',en:'roasted',cat:'Food',ipa:'/arˈrɔs.to/',ex:'Pollo arrosto al forno.',exEn:'Oven-roasted chicken.'},
    {it:'alla griglia',en:'grilled',cat:'Food',ipa:'/ˈal.la ˈɡriʎ.ʎa/',ex:'Salmone alla griglia.',exEn:'Grilled salmon.'},
    {it:'al vapore',en:'steamed',cat:'Food',ipa:'/al vaˈpoː.re/',ex:'Verdure al vapore.',exEn:'Steamed vegetables.'},
  ]
};

window.PACK_food.words.push(
  {it:'la zucca',en:'pumpkin / squash',cat:'Food',ipa:'/la ˈdzuk.ka/',ex:'La zuppa di zucca è buona.',exEn:'Pumpkin soup is good.'},
  {it:'il cavolfiore',en:'cauliflower',cat:'Food',ipa:'/il kavolˈfjoː.re/',ex:'Il cavolfiore al forno.',exEn:'Baked cauliflower.'},
  {it:'i broccoli',en:'broccoli',cat:'Food',ipa:'/i ˈbrɔk.ko.li/',ex:'I broccoli sono sani.',exEn:'Broccoli is healthy.'},
  {it:'gli spinaci',en:'spinach',cat:'Food',ipa:'/ʎi spiˈnaː.tʃi/',ex:'Gli spinaci al burro.',exEn:'Spinach with butter.'},
  {it:'le melanzane',en:'aubergine / eggplant',cat:'Food',ipa:'/le melanˈdzaː.ne/',ex:'Melanzane alla parmigiana.',exEn:'Aubergine parmigiana.'},
  {it:'il peperone',en:'bell pepper',cat:'Food',ipa:'/il pepeˈroː.ne/',ex:'Peperoni rossi e gialli.',exEn:'Red and yellow peppers.'},
  {it:'il cetriolo',en:'cucumber',cat:'Food',ipa:'/il tʃetriˈɔː.lo/',ex:'Un cetriolo fresco.',exEn:'A fresh cucumber.'},
  {it:'l\'avocado',en:'avocado',cat:'Food',ipa:'/lavoˈkaː.do/',ex:'Guacamole all\'avocado.',exEn:'Avocado guacamole.'},
  {it:'la fragola',en:'strawberry',cat:'Food',ipa:'/la ˈfraː.ɡo.la/',ex:'Le fragole con panna.',exEn:'Strawberries with cream.'},
  {it:'il lampone',en:'raspberry',cat:'Food',ipa:'/il lamˈpoː.ne/',ex:'Marmellata di lamponi.',exEn:'Raspberry jam.'}
);
