window.PACK_work = {
  id:'work', name:'Work & Business', emoji:'💼',
  words:[
    {it:'il lavoro',en:'work / job',cat:'Work',ipa:'/il laˈvoː.ro/',ex:'Come va il lavoro?',exEn:'How is work going?'},
    {it:'l\'ufficio',en:'the office',cat:'Work',ipa:'/lufˈfiː.tʃo/',ex:'Lavoro in ufficio.',exEn:'I work in an office.'},
    {it:'l\'azienda',en:'the company / firm',cat:'Work',ipa:'/latˈtsjen.da/',ex:'Lavoro per una grande azienda.',exEn:'I work for a big company.'},
    {it:'il capo',en:'the boss',cat:'Work',ipa:'/il ˈkaː.po/',ex:'Il mio capo è molto esigente.',exEn:'My boss is very demanding.'},
    {it:'il collega',en:'the colleague',cat:'Work',ipa:'/il kolˈleː.ɡa/',ex:'I miei colleghi sono simpatici.',exEn:'My colleagues are friendly.'},
    {it:'il dipendente',en:'the employee',cat:'Work',ipa:'/il dipenˈdɛn.te/',ex:'L\'azienda ha cento dipendenti.',exEn:'The company has a hundred employees.'},
    {it:'il datore di lavoro',en:'the employer',cat:'Work',ipa:'/il daˈtoː.re di laˈvoː.ro/',ex:'Il mio datore di lavoro è generoso.',exEn:'My employer is generous.'},
    {it:'lo stipendio',en:'the salary',cat:'Work',ipa:'/lo stiˈpɛn.djo/',ex:'Lo stipendio è buono.',exEn:'The salary is good.'},
    {it:'la busta paga',en:'the payslip',cat:'Work',ipa:'/la ˈbus.ta ˈpaː.ɡa/',ex:'Ho ricevuto la busta paga.',exEn:'I received my payslip.'},
    {it:'la riunione',en:'the meeting',cat:'Work',ipa:'/la rjuˈnjoː.ne/',ex:'Ho una riunione alle dieci.',exEn:'I have a meeting at ten.'},
    {it:'la scadenza',en:'the deadline',cat:'Work',ipa:'/la skaˈdɛn.tsa/',ex:'La scadenza è venerdì.',exEn:'The deadline is Friday.'},
    {it:'il progetto',en:'the project',cat:'Work',ipa:'/il proˈdʒɛt.to/',ex:'Lavoro su un progetto importante.',exEn:'I\'m working on an important project.'},
    {it:'il contratto',en:'the contract',cat:'Work',ipa:'/il konˈtrat.to/',ex:'Ho firmato il contratto.',exEn:'I signed the contract.'},
    {it:'il curriculum',en:'the CV / résumé',cat:'Work',ipa:'/il kuˈrik.ku.lum/',ex:'Ho mandato il curriculum.',exEn:'I sent my CV.'},
    {it:'il colloquio',en:'the job interview',cat:'Work',ipa:'/il kolˈloː.kwjo/',ex:'Ho un colloquio domani.',exEn:'I have an interview tomorrow.'},
    {it:'assumere',en:'to hire',cat:'Work',ipa:'/asˈsuː.me.re/',ex:'L\'azienda assume nuovo personale.',exEn:'The company is hiring new staff.'},
    {it:'licenziare',en:'to fire / dismiss',cat:'Work',ipa:'/litʃenˈtsjaː.re/',ex:'È stato licenziato.',exEn:'He was fired.'},
    {it:'dimettersi',en:'to resign / quit',cat:'Work',ipa:'/diˈmɛt.ter.si/',ex:'Mi sono dimesso.',exEn:'I resigned.'},
    {it:'il sindacato',en:'the trade union',cat:'Work',ipa:'/il sindaˈkaː.to/',ex:'Sono iscritto al sindacato.',exEn:'I\'m a union member.'},
    {it:'lo sciopero',en:'the strike',cat:'Work',ipa:'/lo ˈʃɔː.pe.ro/',ex:'I lavoratori fanno sciopero.',exEn:'The workers are on strike.'},
    {it:'part-time',en:'part-time',cat:'Work',ipa:'/ˌpɑːtˈtaɪm/',ex:'Lavoro part-time.',exEn:'I work part-time.'},
    {it:'a tempo pieno',en:'full-time',cat:'Work',ipa:'/a ˈtɛm.po ˈpjeː.no/',ex:'Cerco un lavoro a tempo pieno.',exEn:'I\'m looking for full-time work.'},
    {it:'il freelance',en:'freelancer',cat:'Work',ipa:'/il ˈfriː.lans/',ex:'Sono un freelance.',exEn:'I\'m a freelancer.'},
    {it:'lavorare da casa',en:'to work from home',cat:'Work',ipa:'/lavoˈraː.re da ˈkaː.za/',ex:'Lavoro da casa il venerdì.',exEn:'I work from home on Fridays.'},
    {it:'il cliente',en:'the client / customer',cat:'Work',ipa:'/il ˈkljeːn.te/',ex:'Il cliente ha sempre ragione.',exEn:'The customer is always right.'},
    {it:'la riunione',en:'the meeting',cat:'Work',ipa:'/la rjuˈnjoː.ne/',ex:'Prenotiamo una sala riunioni.',exEn:'Let\'s book a meeting room.'},
    {it:'la presentazione',en:'the presentation',cat:'Work',ipa:'/la prezentaˈtsjoː.ne/',ex:'Devo fare una presentazione.',exEn:'I need to give a presentation.'},
    {it:'il budget',en:'the budget',cat:'Work',ipa:'/il ˈbad.dʒɛt/',ex:'Il budget è limitato.',exEn:'The budget is limited.'},
    {it:'il fatturato',en:'the turnover / revenue',cat:'Work',ipa:'/il fattuˈraː.to/',ex:'Il fatturato è aumentato.',exEn:'The turnover has increased.'},
    {it:'il profitto',en:'profit',cat:'Work',ipa:'/il proˈfit.to/',ex:'L\'azienda ha fatto profitto.',exEn:'The company made a profit.'},
    {it:'la perdita',en:'the loss',cat:'Work',ipa:'/la ˈpɛr.di.ta/',ex:'Abbiamo registrato una perdita.',exEn:'We recorded a loss.'},
    {it:'la concorrenza',en:'the competition',cat:'Work',ipa:'/la konkorˈrɛn.tsa/',ex:'La concorrenza è forte.',exEn:'The competition is strong.'},
    {it:'il mercato',en:'the market',cat:'Work',ipa:'/il merˈkaː.to/',ex:'Il mercato è in crescita.',exEn:'The market is growing.'},
    {it:'il marketing',en:'marketing',cat:'Work',ipa:'/il ˈmar.ke.tiŋ/',ex:'Lavoro nel marketing.',exEn:'I work in marketing.'},
    {it:'le vendite',en:'sales',cat:'Work',ipa:'/le ˈvɛn.di.te/',ex:'Le vendite sono aumentate.',exEn:'Sales have increased.'},
    {it:'la contabilità',en:'accounting',cat:'Work',ipa:'/la kontabiliˈta/',ex:'Faccio la contabilità.',exEn:'I do the accounting.'},
    {it:'le risorse umane',en:'human resources / HR',cat:'Work',ipa:'/le riˈzor.se uˈmaː.ne/',ex:'Parla con le risorse umane.',exEn:'Speak to HR.'},
    {it:'il reparto',en:'the department',cat:'Work',ipa:'/il reˈpar.to/',ex:'Lavoro nel reparto vendite.',exEn:'I work in the sales department.'},
    {it:'la sede',en:'the headquarters',cat:'Work',ipa:'/la ˈseː.de/',ex:'La sede è a Milano.',exEn:'The headquarters is in Milan.'},
    {it:'la filiale',en:'the branch (office)',cat:'Work',ipa:'/la fiˈljaː.le/',ex:'La filiale di Roma.',exEn:'The Rome branch.'},
    {it:'l\'imprenditore',en:'the entrepreneur',cat:'Work',ipa:'/limprendiˈtoː.re/',ex:'È un giovane imprenditore.',exEn:'He is a young entrepreneur.'},
    {it:'la startup',en:'the startup',cat:'Work',ipa:'/la ˈstar.tap/',ex:'Ha fondato una startup.',exEn:'He founded a startup.'},
    {it:'il socio',en:'the business partner',cat:'Work',ipa:'/il ˈsoː.tʃo/',ex:'Il mio socio d\'affari.',exEn:'My business partner.'},
    {it:'l\'investimento',en:'the investment',cat:'Work',ipa:'/linvestiˈmɛn.to/',ex:'È un buon investimento.',exEn:'It\'s a good investment.'},
    {it:'la fiera',en:'the trade fair',cat:'Work',ipa:'/la ˈfjeː.ra/',ex:'Andiamo alla fiera.',exEn:'We\'re going to the trade fair.'},
    {it:'il networking',en:'networking',cat:'Work',ipa:'/il ˈnet.wɜr.kiŋ/',ex:'È importante fare networking.',exEn:'Networking is important.'},
    {it:'in pensione',en:'retired',cat:'Work',ipa:'/in penˈsjoː.ne/',ex:'Mio padre è in pensione.',exEn:'My father is retired.'},
    {it:'la pensione',en:'pension / retirement',cat:'Work',ipa:'/la penˈsjoː.ne/',ex:'Vado in pensione a sessantacinque anni.',exEn:'I retire at sixty-five.'},
    {it:'disoccupato',en:'unemployed',cat:'Work',ipa:'/dizokku ˈpaː.to/',ex:'Sono disoccupato.',exEn:'I am unemployed.'},
    {it:'la formazione',en:'training / education',cat:'Work',ipa:'/la formatˈtsjoː.ne/',ex:'Faccio un corso di formazione.',exEn:'I\'m doing a training course.'},
    {it:'la promozione',en:'promotion',cat:'Work',ipa:'/la promotˈtsjoː.ne/',ex:'Ho avuto una promozione!',exEn:'I got a promotion!'},
  ]
};

window.PACK_work.words.push(
  {it:'il settore',en:'sector / industry',cat:'Work',ipa:'/il setˈtoː.re/',ex:'Lavoro nel settore sanitario.',exEn:'I work in the healthcare sector.'},
  {it:'l\'industria',en:'industry',cat:'Work',ipa:'/linˈdus.trja/',ex:'L\'industria automobilistica.',exEn:'The car industry.'},
  {it:'la fabbrica',en:'factory',cat:'Work',ipa:'/la ˈfab.bri.ka/',ex:'Lavoro in fabbrica.',exEn:'I work in a factory.'},
  {it:'l\'artigiano',en:'craftsman',cat:'Work',ipa:'/lartiˈdʒaː.no/',ex:'È un artigiano del legno.',exEn:'He\'s a wood craftsman.'},
  {it:'la professione',en:'profession',cat:'Work',ipa:'/la profesˈsjoː.ne/',ex:'Qual è la tua professione?',exEn:'What is your profession?'},
  {it:'il medico',en:'doctor',cat:'Work',ipa:'/il ˈmɛː.di.ko/',ex:'Sono medico.',exEn:'I\'m a doctor.'},
  {it:'l\'avvocato',en:'lawyer',cat:'Work',ipa:'/lavvoˈkaː.to/',ex:'È avvocato.',exEn:'She\'s a lawyer.'},
  {it:'l\'ingegnere',en:'engineer',cat:'Work',ipa:'/lindʒeˈɲeː.re/',ex:'È ingegnere civile.',exEn:'He\'s a civil engineer.'},
  {it:'l\'architetto',en:'architect',cat:'Work',ipa:'/larkiˈtɛt.to/',ex:'È architetto.',exEn:'She\'s an architect.'},
  {it:'l\'insegnante',en:'teacher',cat:'Work',ipa:'/linseˈɲan.te/',ex:'È insegnante di italiano.',exEn:'She\'s an Italian teacher.'},
  {it:'il giornalista',en:'journalist',cat:'Work',ipa:'/il dʒornaˈlis.ta/',ex:'È giornalista investigativo.',exEn:'He\'s an investigative journalist.'},
  {it:'il cuoco',en:'cook / chef',cat:'Work',ipa:'/il ˈkwɔː.ko/',ex:'È un ottimo cuoco.',exEn:'He\'s an excellent cook.'},
  {it:'il contabile',en:'accountant',cat:'Work',ipa:'/il konˈtaː.bi.le/',ex:'È un bravo contabile.',exEn:'He\'s a good accountant.'},
  {it:'il programmatore',en:'programmer',cat:'Work',ipa:'/il programmaˈtoː.re/',ex:'È programmatore.',exEn:'He\'s a programmer.'},
  {it:'il consulente',en:'consultant',cat:'Work',ipa:'/il konsuˈlɛn.te/',ex:'Sono consulente aziendale.',exEn:'I\'m a business consultant.'},
  {it:'l\'operaio',en:'worker / labourer',cat:'Work',ipa:'/loperˈaː.jo/',ex:'Lavora come operaio.',exEn:'He works as a labourer.'},
  {it:'il dirigente',en:'manager / executive',cat:'Work',ipa:'/il diriˈdʒɛn.te/',ex:'È dirigente d\'azienda.',exEn:'He\'s a company executive.'},
  {it:'la conferenza',en:'conference',cat:'Work',ipa:'/la konfeˈrɛn.tsa/',ex:'Una conferenza internazionale.',exEn:'An international conference.'},
  {it:'il seminario',en:'seminar',cat:'Work',ipa:'/il semiˈnaː.rjo/',ex:'Partecipo a un seminario.',exEn:'I\'m attending a seminar.'},
  {it:'l\'offerta di lavoro',en:'job offer',cat:'Work',ipa:'/lofˈfɛr.ta di laˈvoː.ro/',ex:'Ho ricevuto un\'offerta di lavoro.',exEn:'I received a job offer.'},
  {it:'il periodo di prova',en:'probation period',cat:'Work',ipa:'/il peˈrjoː.do di ˈprɔː.va/',ex:'Sono in periodo di prova.',exEn:'I\'m on probation.'},
  {it:'il turno di lavoro',en:'work shift',cat:'Work',ipa:'/il ˈtur.no di laˈvoː.ro/',ex:'Lavoro a turni.',exEn:'I work shifts.'},
  {it:'le ferie',en:'annual leave',cat:'Work',ipa:'/le ˈfeː.rje/',ex:'Ho due settimane di ferie.',exEn:'I have two weeks of annual leave.'},
  {it:'il congedo parentale',en:'parental leave',cat:'Work',ipa:'/il konˈdʒeː.do parentˈaː.le/',ex:'Sono in congedo parentale.',exEn:'I\'m on parental leave.'},
  {it:'l\'aumento di stipendio',en:'pay rise',cat:'Work',ipa:'/lawˈmɛn.to di stipˈɛndjo/',ex:'Ho chiesto un aumento.',exEn:'I asked for a pay rise.'},
  {it:'il bonus',en:'bonus',cat:'Work',ipa:'/il ˈboː.nus/',ex:'Ho ricevuto un bonus.',exEn:'I received a bonus.'},
  {it:'la trasferta',en:'business trip',cat:'Work',ipa:'/la trasˈfɛr.ta/',ex:'Vado in trasferta.',exEn:'I\'m going on a business trip.'},
  {it:'lo smart working',en:'remote working',cat:'Work',ipa:'/lo smɑːrt ˈwɜːkɪŋ/',ex:'Faccio smart working.',exEn:'I work remotely.'},
  {it:'il burnout',en:'burnout',cat:'Work',ipa:'/il ˈbɜːn.awt/',ex:'Ho avuto un burnout.',exEn:'I had a burnout.'},
  {it:'la responsabilità',en:'responsibility',cat:'Work',ipa:'/la responsabiliˈta/',ex:'Ho grandi responsabilità.',exEn:'I have great responsibilities.'},
  {it:'l\'obiettivo',en:'goal / objective',cat:'Work',ipa:'/lɔbˈjɛt.ti.vo/',ex:'Raggiungo l\'obiettivo.',exEn:'I achieve the goal.'},
  {it:'la scadenza',en:'deadline',cat:'Work',ipa:'/la skaˈdɛn.tsa/',ex:'La scadenza è domani.',exEn:'The deadline is tomorrow.'},
  {it:'il verbale',en:'minutes (of a meeting)',cat:'Work',ipa:'/il verˈbaː.le/',ex:'Scrivo il verbale.',exEn:'I write the minutes.'},
  {it:'l\'ordine del giorno',en:'agenda',cat:'Work',ipa:'/ˈlɔr.di.ne del ˈdʒor.no/',ex:'L\'ordine del giorno della riunione.',exEn:'The meeting agenda.'},
  {it:'il rapporto',en:'report',cat:'Work',ipa:'/il rapˈpɔr.to/',ex:'Ho scritto il rapporto.',exEn:'I wrote the report.'},
  {it:'la relazione',en:'report / relationship',cat:'Work',ipa:'/la relatˈtsjoː.ne/',ex:'La relazione trimestrale.',exEn:'The quarterly report.'},
  {it:'la strategia',en:'strategy',cat:'Work',ipa:'/la strateˈdʒiː.a/',ex:'Una nuova strategia aziendale.',exEn:'A new business strategy.'},
  {it:'il piano d\'azione',en:'action plan',cat:'Work',ipa:'/il ˈpjaː.no datˈtsjoː.ne/',ex:'Il piano d\'azione.',exEn:'The action plan.'},
  {it:'il KPI',en:'KPI',cat:'Work',ipa:'/il ˈkeɪ.piː.aɪ/',ex:'Monitoriamo i KPI.',exEn:'We monitor the KPIs.'},
  {it:'il feedback',en:'feedback',cat:'Work',ipa:'/il ˈfiːd.bæk/',ex:'Il feedback è positivo.',exEn:'The feedback is positive.'},
  {it:'la valutazione',en:'evaluation / appraisal',cat:'Work',ipa:'/la valutatˈtsjoː.ne/',ex:'La valutazione annuale.',exEn:'The annual appraisal.'},
  {it:'l\'organico',en:'workforce / staff',cat:'Work',ipa:'/lorˈɡaː.ni.ko/',ex:'L\'organico aziendale.',exEn:'The company workforce.'},
  {it:'il mansionario',en:'job description',cat:'Work',ipa:'/il mansjoˈnaː.rjo/',ex:'Il mansionario del ruolo.',exEn:'The job description.'},
  {it:'il colloquio di lavoro',en:'job interview',cat:'Work',ipa:'/il kolˈloː.kwjo di laˈvoː.ro/',ex:'Ho un colloquio domani.',exEn:'I have a job interview tomorrow.'},
  {it:'la lettera di referenze',en:'reference letter',cat:'Work',ipa:'/la ˈlɛt.te.ra di referˈɛn.tse/',ex:'Ho bisogno di una referenza.',exEn:'I need a reference letter.'},
  {it:'il sindacato',en:'trade union',cat:'Work',ipa:'/il sindaˈkaː.to/',ex:'Sono iscritto al sindacato.',exEn:'I\'m a union member.'},
  {it:'lo sciopero',en:'strike',cat:'Work',ipa:'/lo ˈʃɔː.pe.ro/',ex:'I lavoratori fanno sciopero.',exEn:'The workers are on strike.'},
  {it:'la cassa integrazione',en:'redundancy / furlough scheme',cat:'Work',ipa:'/la ˈkas.sa integraˈtsjoː.ne/',ex:'È in cassa integrazione.',exEn:'He\'s on furlough.'},
  {it:'il licenziamento',en:'dismissal / redundancy',cat:'Work',ipa:'/il litʃentsjaˈmɛn.to/',ex:'Ha ricevuto il licenziamento.',exEn:'He received his dismissal notice.'}
);
