window.PACK_health = {
  id:'health', name:'Health & Medical', emoji:'🏥',
  words:[
    {it:'la salute',en:'health',cat:'Health',ipa:'/la saˈluː.te/',ex:'La salute è la cosa più importante.',exEn:'Health is the most important thing.'},
    {it:'il medico',en:'the doctor',cat:'Health',ipa:'/il ˈmɛː.di.ko/',ex:'Devo andare dal medico.',exEn:'I need to go to the doctor.'},
    {it:'l\'infermiere',en:'the nurse (m)',cat:'Health',ipa:'/linferˈmjeː.re/',ex:'L\'infermiere è molto gentile.',exEn:'The nurse is very kind.'},
    {it:'l\'infermiera',en:'the nurse (f)',cat:'Health',ipa:'/linferˈmjeː.ra/',ex:'L\'infermiera mi ha fatto l\'iniezione.',exEn:'The nurse gave me the injection.'},
    {it:'l\'ospedale',en:'the hospital',cat:'Health',ipa:'/lospɛˈdaː.le/',ex:'Sono stato in ospedale.',exEn:'I was in hospital.'},
    {it:'il pronto soccorso',en:'emergency room / A&E',cat:'Health',ipa:'/il ˈpron.to sokˈkor.so/',ex:'Vai al pronto soccorso!',exEn:'Go to the emergency room!'},
    {it:'la farmacia',en:'the pharmacy',cat:'Health',ipa:'/la farˈmaː.tʃa/',ex:'La farmacia è qui vicino.',exEn:'The pharmacy is nearby.'},
    {it:'la medicina',en:'the medicine / medication',cat:'Health',ipa:'/la mediˈtʃiː.na/',ex:'Prendo la medicina ogni giorno.',exEn:'I take the medicine every day.'},
    {it:'la ricetta',en:'the prescription',cat:'Health',ipa:'/la riˈtʃet.ta/',ex:'Ho bisogno della ricetta.',exEn:'I need the prescription.'},
    {it:'il dolore',en:'the pain',cat:'Health',ipa:'/il doˈloː.re/',ex:'Ho un forte dolore qui.',exEn:'I have a strong pain here.'},
    {it:'fare male',en:'to hurt',cat:'Health',ipa:'/ˈfaː.re ˈmaː.le/',ex:'Mi fa male la schiena.',exEn:'My back hurts.'},
    {it:'la febbre',en:'the fever',cat:'Health',ipa:'/la ˈfɛb.bre/',ex:'Ho la febbre.',exEn:'I have a fever.'},
    {it:'il raffreddore',en:'the cold',cat:'Health',ipa:'/il raffredˈdoː.re/',ex:'Ho il raffreddore.',exEn:'I have a cold.'},
    {it:'l\'influenza',en:'the flu',cat:'Health',ipa:'/linˈflwen.tsa/',ex:'Ho l\'influenza.',exEn:'I have the flu.'},
    {it:'la tosse',en:'the cough',cat:'Health',ipa:'/la ˈtɔs.se/',ex:'Ho la tosse.',exEn:'I have a cough.'},
    {it:'il mal di testa',en:'headache',cat:'Health',ipa:'/il mal di ˈtɛs.ta/',ex:'Ho un forte mal di testa.',exEn:'I have a bad headache.'},
    {it:'la nausea',en:'nausea',cat:'Health',ipa:'/la ˈnaː.u.ze.a/',ex:'Ho la nausea.',exEn:'I feel nauseous.'},
    {it:'il vomito',en:'vomiting',cat:'Health',ipa:'/il ˈvɔː.mi.to/',ex:'Ha avuto il vomito.',exEn:'He had vomiting.'},
    {it:'la diarrea',en:'diarrhoea',cat:'Health',ipa:'/la djarˈrɛː.a/',ex:'Ho la diarrea.',exEn:'I have diarrhoea.'},
    {it:'la stitichezza',en:'constipation',cat:'Health',ipa:'/la stitiˈket.tsa/',ex:'Ho la stitichezza.',exEn:'I have constipation.'},
    {it:'la vertigine',en:'dizziness',cat:'Health',ipa:'/la verˈtiː.dʒi.ne/',ex:'Ho le vertigini.',exEn:'I feel dizzy.'},
    {it:'la stanchezza',en:'fatigue / tiredness',cat:'Health',ipa:'/la staŋˈket.tsa/',ex:'Soffro di stanchezza cronica.',exEn:'I suffer from chronic fatigue.'},
    {it:'l\'allergia',en:'the allergy',cat:'Health',ipa:'/lallerˈdʒiː.a/',ex:'Ho un\'allergia.',exEn:'I have an allergy.'},
    {it:'diabete',en:'diabetes',cat:'Health',ipa:'/djaˈbɛː.te/',ex:'Soffro di diabete.',exEn:'I have diabetes.'},
    {it:'la pressione',en:'blood pressure',cat:'Health',ipa:'/la presˈsjoː.ne/',ex:'Ho la pressione alta.',exEn:'I have high blood pressure.'},
    {it:'la ferita',en:'the wound / injury',cat:'Health',ipa:'/la feˈriː.ta/',ex:'Ho una ferita sulla mano.',exEn:'I have a wound on my hand.'},
    {it:'il taglio',en:'the cut',cat:'Health',ipa:'/il ˈtaʎ.ʎo/',ex:'Mi sono fatto un taglio.',exEn:'I made a cut.'},
    {it:'il livido',en:'the bruise',cat:'Health',ipa:'/il ˈliː.vi.do/',ex:'Ho un livido sul braccio.',exEn:'I have a bruise on my arm.'},
    {it:'la frattura',en:'the fracture / break',cat:'Health',ipa:'/la ˈfrat.tu.ra/',ex:'Ho una frattura al polso.',exEn:'I have a fracture in my wrist.'},
    {it:'la fasciatura',en:'the bandage / dressing',cat:'Health',ipa:'/la faʃˈʃa.tu.ra/',ex:'Metti la fasciatura.',exEn:'Put on the bandage.'},
    {it:'il cerotto',en:'the plaster / bandaid',cat:'Health',ipa:'/il tʃeˈrɔt.to/',ex:'Ho bisogno di un cerotto.',exEn:'I need a plaster.'},
    {it:'l\'iniezione',en:'the injection',cat:'Health',ipa:'/linjeˈtsjoː.ne/',ex:'Devo fare un\'iniezione.',exEn:'I need to have an injection.'},
    {it:'la pillola',en:'the pill / tablet',cat:'Health',ipa:'/la ˈpil.lo.la/',ex:'Prendo la pillola ogni mattina.',exEn:'I take the pill every morning.'},
    {it:'lo sciroppo',en:'the syrup',cat:'Health',ipa:'/lo ʃiˈrɔp.po/',ex:'Sciroppo per la tosse.',exEn:'Cough syrup.'},
    {it:'l\'antibiotico',en:'the antibiotic',cat:'Health',ipa:'/lantiˈbjɔː.ti.ko/',ex:'Il medico mi ha dato un antibiotico.',exEn:'The doctor gave me an antibiotic.'},
    {it:'la visita medica',en:'the medical appointment',cat:'Health',ipa:'/la ˈviː.zi.ta ˈmɛː.di.ka/',ex:'Ho una visita medica domani.',exEn:'I have a medical appointment tomorrow.'},
    {it:'il dentista',en:'the dentist',cat:'Health',ipa:'/il denˈtis.ta/',ex:'Vado dal dentista.',exEn:'I\'m going to the dentist.'},
    {it:'l\'oculista',en:'the optician / eye doctor',cat:'Health',ipa:'/lokuleˈis.ta/',ex:'Ho bisogno dell\'oculista.',exEn:'I need the optician.'},
    {it:'operarsi',en:'to have an operation',cat:'Health',ipa:'/operˈar.si/',ex:'Mi devo operare.',exEn:'I need to have an operation.'},
    {it:'guarire',en:'to recover / heal',cat:'Health',ipa:'/ɡwaˈriː.re/',ex:'Spero di guarire presto.',exEn:'I hope to recover soon.'},
    {it:'stare meglio',en:'to feel better',cat:'Health',ipa:'/ˈstaː.re ˈmɛʎ.ʎo/',ex:'Sto meglio, grazie.',exEn:'I feel better, thank you.'},
    {it:'stare peggio',en:'to feel worse',cat:'Health',ipa:'/ˈstaː.re ˈpɛdʒ.dʒo/',ex:'Sto un po\' peggio.',exEn:'I feel a little worse.'},
    {it:'il riposo',en:'rest',cat:'Health',ipa:'/il riˈpɔː.zo/',ex:'Hai bisogno di riposo.',exEn:'You need rest.'},
    {it:'la dieta',en:'the diet',cat:'Health',ipa:'/la ˈdjeː.ta/',ex:'Sono a dieta.',exEn:'I\'m on a diet.'},
    {it:'fare sport',en:'to do sport / exercise',cat:'Health',ipa:'/ˈfaː.re ˈspɔrt/',ex:'Faccio sport tre volte a settimana.',exEn:'I do sport three times a week.'},
    {it:'non fumare',en:'not to smoke / no smoking',cat:'Health',ipa:'/non fuˈmaː.re/',ex:'Non fumo.',exEn:'I don\'t smoke.'},
    {it:'il gruppo sanguigno',en:'blood type',cat:'Health',ipa:'/il ˈɡrup.po saŋˈɡwiɲ.ɲo/',ex:'Qual è il tuo gruppo sanguigno?',exEn:'What is your blood type?'},
    {it:'incinto',en:'pregnant',cat:'Health',ipa:'/inˈtʃin.to/',ex:'È incinta.',exEn:'She is pregnant.'},
    {it:'l\'ambulanza',en:'the ambulance',cat:'Health',ipa:'/lambuˈlan.tsa/',ex:'Chiamate l\'ambulanza!',exEn:'Call the ambulance!'},
    {it:'urgente',en:'urgent',cat:'Health',ipa:'/urˈdʒɛn.te/',ex:'È urgente!',exEn:'It\'s urgent!'},
    {it:'disabile',en:'disabled',cat:'Health',ipa:'/diˈzaː.bi.le/',ex:'È disabile.',exEn:'He is disabled.'},
  ]
};

window.PACK_health.words.push(
  {it:'il dolore cronico',en:'chronic pain',cat:'Health',ipa:'/il doˈloː.re ˈkrɔː.ni.ko/',ex:'Soffro di dolore cronico.',exEn:'I suffer from chronic pain.'},
  {it:'la malattia',en:'illness / disease',cat:'Health',ipa:'/la malatˈtiː.a/',ex:'È una malattia grave.',exEn:'It\'s a serious illness.'},
  {it:'la diagnosi',en:'diagnosis',cat:'Health',ipa:'/la djaˈɡnɔː.zi/',ex:'La diagnosi è incerta.',exEn:'The diagnosis is uncertain.'},
  {it:'la cura',en:'treatment / cure',cat:'Health',ipa:'/la ˈkuː.ra/',ex:'La cura dura tre mesi.',exEn:'The treatment lasts three months.'},
  {it:'l\'intervento',en:'surgical operation',cat:'Health',ipa:'/linˈtɛr.vɛn.to/',ex:'Ha bisogno di un intervento.',exEn:'He needs an operation.'},
  {it:'il chirurgo',en:'surgeon',cat:'Health',ipa:'/il kiˈrur.ɡo/',ex:'Il chirurgo è bravo.',exEn:'The surgeon is skilled.'},
  {it:'l\'anestesia',en:'anaesthesia',cat:'Health',ipa:'/lanesteˈziː.a/',ex:'L\'anestesia generale.',exEn:'General anaesthesia.'},
  {it:'il check-up',en:'check-up',cat:'Health',ipa:'/il ˈtʃɛk.ʌp/',ex:'Faccio il check-up annuale.',exEn:'I have my annual check-up.'},
  {it:'l\'esame del sangue',en:'blood test',cat:'Health',ipa:'/leˈzaː.me del ˈsaŋ.ɡwe/',ex:'Devo fare l\'esame del sangue.',exEn:'I need a blood test.'},
  {it:'la radiografia',en:'X-ray',cat:'Health',ipa:'/la radjoɡrafˈiː.a/',ex:'Ha fatto una radiografia.',exEn:'He had an X-ray.'},
  {it:'la risonanza magnetica',en:'MRI scan',cat:'Health',ipa:'/la rizoˈnan.tsa maɲˈɲɛː.ti.ka/',ex:'Ho fatto la risonanza.',exEn:'I had the MRI scan.'},
  {it:'la pressione alta',en:'high blood pressure',cat:'Health',ipa:'/la presˈsjoː.ne ˈal.ta/',ex:'Ho la pressione alta.',exEn:'I have high blood pressure.'},
  {it:'il colesterolo',en:'cholesterol',cat:'Health',ipa:'/il kolesˈtɛː.ro.lo/',ex:'Il colesterolo è alto.',exEn:'Cholesterol is high.'},
  {it:'l\'asma',en:'asthma',cat:'Health',ipa:'/ˈlaz.ma/',ex:'Soffro di asma.',exEn:'I suffer from asthma.'},
  {it:'l\'epilessia',en:'epilepsy',cat:'Health',ipa:'/lepiˈlɛs.sja/',ex:'Ha l\'epilessia.',exEn:'He has epilepsy.'},
  {it:'la depressione',en:'depression',cat:'Health',ipa:'/la depresˈsjoː.ne/',ex:'Soffro di depressione.',exEn:'I suffer from depression.'},
  {it:'l\'insonnia',en:'insomnia',cat:'Health',ipa:'/linˈsɔn.nja/',ex:'Soffro di insonnia.',exEn:'I suffer from insomnia.'},
  {it:'la varicella',en:'chickenpox',cat:'Health',ipa:'/la variˈtʃɛl.la/',ex:'Ha la varicella.',exEn:'He has chickenpox.'},
  {it:'il vaccino',en:'vaccine',cat:'Health',ipa:'/il vatˈtʃiː.no/',ex:'Faccio il vaccino.',exEn:'I get vaccinated.'},
  {it:'la prevenzione',en:'prevention',cat:'Health',ipa:'/la prevɛnˈtsjoː.ne/',ex:'La prevenzione è fondamentale.',exEn:'Prevention is fundamental.'},
  {it:'il decorso',en:'course (of illness)',cat:'Health',ipa:'/il deˈkor.so/',ex:'Il decorso della malattia.',exEn:'The course of the illness.'},
  {it:'la remissione',en:'remission',cat:'Health',ipa:'/la remisˈsjoː.ne/',ex:'Il tumore è in remissione.',exEn:'The tumour is in remission.'},
  {it:'la degenza',en:'hospital stay',cat:'Health',ipa:'/la deˈdʒɛn.tsa/',ex:'La degenza dura una settimana.',exEn:'The hospital stay lasts a week.'},
  {it:'le dimissioni',en:'discharge (from hospital)',cat:'Health',ipa:'/le dimisˈsjoː.ni/',ex:'Ho le dimissioni domani.',exEn:'I\'m being discharged tomorrow.'},
  {it:'la convalescenza',en:'convalescence',cat:'Health',ipa:'/la konvaleˈʃɛn.tsa/',ex:'Sono in convalescenza.',exEn:'I\'m convalescing.'},
  {it:'l\'idratazione',en:'hydration',cat:'Health',ipa:'/lidrataˈtsjoː.ne/',ex:'È importante l\'idratazione.',exEn:'Hydration is important.'},
  {it:'lo specialista',en:'specialist',cat:'Health',ipa:'/lo spetʃaˈlis.ta/',ex:'Vedo lo specialista.',exEn:'I\'m seeing the specialist.'},
  {it:'il medico di base',en:'GP / family doctor',cat:'Health',ipa:'/il ˈmɛː.di.ko di ˈbaː.ze/',ex:'Chiamo il medico di base.',exEn:'I\'ll call my GP.'},
  {it:'la donazione di sangue',en:'blood donation',cat:'Health',ipa:'/la donatˈtsjoː.ne di ˈsaŋ.ɡwe/',ex:'Faccio la donazione di sangue.',exEn:'I donate blood.'},
  {it:'il trapianto',en:'transplant',cat:'Health',ipa:'/il traˈpjan.to/',ex:'Aspetta un trapianto.',exEn:'He\'s waiting for a transplant.'},
  {it:'l\'allergia alimentare',en:'food allergy',cat:'Health',ipa:'/lallerˈdʒiː.a alimeˈnta.re/',ex:'Ho un\'allergia alimentare.',exEn:'I have a food allergy.'},
  {it:'l\'intolleranza',en:'intolerance',cat:'Health',ipa:'/lintolleˈran.tsa/',ex:'Intolleranza al lattosio.',exEn:'Lactose intolerance.'},
  {it:'la celiachia',en:'coeliac disease',cat:'Health',ipa:'/la tʃeˈljaː.kja/',ex:'Ha la celiachia.',exEn:'She has coeliac disease.'},
  {it:'il massaggio',en:'massage',cat:'Health',ipa:'/il masˈsadʒ.dʒo/',ex:'Il massaggio rilassa i muscoli.',exEn:'Massage relaxes the muscles.'},
  {it:'la fisioterapia',en:'physiotherapy',cat:'Health',ipa:'/la fizjoˈtɛː.ra.pja/',ex:'Faccio fisioterapia.',exEn:'I\'m doing physiotherapy.'},
  {it:'il fisioterapista',en:'physiotherapist',cat:'Health',ipa:'/il fizjoterapˈis.ta/',ex:'Il fisioterapista è bravo.',exEn:'The physiotherapist is good.'},
  {it:'lo psicologo',en:'psychologist',cat:'Health',ipa:'/lo psiˈkɔː.lo.ɡo/',ex:'Vedo uno psicologo.',exEn:'I see a psychologist.'},
  {it:'lo psichiatra',en:'psychiatrist',cat:'Health',ipa:'/lo psiˈkjaː.tra/',ex:'Lo psichiatra ha prescritto farmaci.',exEn:'The psychiatrist prescribed medication.'},
  {it:'la terapia',en:'therapy',cat:'Health',ipa:'/la teˈraː.pja/',ex:'Faccio terapia.',exEn:'I do therapy.'},
  {it:'la chemioterapia',en:'chemotherapy',cat:'Health',ipa:'/la ˌkiːmjoˈtɛː.ra.pja/',ex:'La chemioterapia è estenuante.',exEn:'Chemotherapy is exhausting.'},
  {it:'la radioterapia',en:'radiotherapy',cat:'Health',ipa:'/la ˌradjoˈtɛː.ra.pja/',ex:'Ha fatto la radioterapia.',exEn:'He underwent radiotherapy.'},
  {it:'il cancro',en:'cancer',cat:'Health',ipa:'/il ˈkaŋ.kro/',ex:'Il cancro al seno.',exEn:'Breast cancer.'},
  {it:'il tumore',en:'tumour',cat:'Health',ipa:'/il tuˈmoː.re/',ex:'Il tumore è benigno.',exEn:'The tumour is benign.'},
  {it:'benigno',en:'benign',cat:'Health',ipa:'/beˈniɲ.ɲo/',ex:'Il tumore è benigno.',exEn:'The tumour is benign.'},
  {it:'maligno',en:'malignant',cat:'Health',ipa:'/maˈliɲ.ɲo/',ex:'È un tumore maligno.',exEn:'It\'s a malignant tumour.'},
  {it:'l\'infarto',en:'heart attack',cat:'Health',ipa:'/linˈfar.to/',ex:'Ha avuto un infarto.',exEn:'He had a heart attack.'},
  {it:'l\'ictus',en:'stroke',cat:'Health',ipa:'/ˈlik.tus/',ex:'Ha avuto un ictus.',exEn:'He had a stroke.'},
  {it:'la frattura ossea',en:'bone fracture',cat:'Health',ipa:'/la ˈfrat.tu.ra ˈɔs.se.a/',ex:'Ha una frattura ossea.',exEn:'He has a bone fracture.'},
  {it:'la lussazione',en:'dislocation',cat:'Health',ipa:'/la lussaˈtsjoː.ne/',ex:'Ho una lussazione alla spalla.',exEn:'I have a dislocated shoulder.'},
  {it:'la distorsione',en:'sprain',cat:'Health',ipa:'/la distorˈsjoː.ne/',ex:'Ho una distorsione alla caviglia.',exEn:'I have a sprained ankle.'}
);
