window.PACK_sports = {
  id:'sports', name:'Sports & Leisure', emoji:'⚽',
  words:[
    {it:'lo sport',en:'sport',cat:'Sport',ipa:'/lo ˈspɔrt/',ex:'Faccio sport ogni giorno.',exEn:'I do sport every day.'},
    {it:'il calcio',en:'football / soccer',cat:'Sport',ipa:'/il ˈkal.tʃo/',ex:'Il calcio è lo sport nazionale.',exEn:'Football is the national sport.'},
    {it:'la partita',en:'the match / game',cat:'Sport',ipa:'/la parˈtiː.ta/',ex:'Guardo la partita.',exEn:'I\'m watching the match.'},
    {it:'la squadra',en:'the team',cat:'Sport',ipa:'/la ˈskwaː.dra/',ex:'La mia squadra ha vinto.',exEn:'My team won.'},
    {it:'il campo',en:'the pitch / field',cat:'Sport',ipa:'/il ˈkam.po/',ex:'Il campo è in erba.',exEn:'The pitch is grass.'},
    {it:'il giocatore',en:'the player',cat:'Sport',ipa:'/il dʒokaˈtoː.re/',ex:'È un ottimo giocatore.',exEn:'He\'s an excellent player.'},
    {it:'l\'allenatore',en:'the coach / trainer',cat:'Sport',ipa:'/lalleˈnaː.to.re/',ex:'L\'allenatore è bravissimo.',exEn:'The coach is excellent.'},
    {it:'l\'arbitro',en:'the referee',cat:'Sport',ipa:'/larˈbiː.tro/',ex:'L\'arbitro ha fischiato.',exEn:'The referee blew the whistle.'},
    {it:'il goal',en:'the goal',cat:'Sport',ipa:'/il ɡoːl/',ex:'Ha segnato un goal!',exEn:'He scored a goal!'},
    {it:'il punteggio',en:'the score',cat:'Sport',ipa:'/il punˈtɛdʒ.dʒo/',ex:'Qual è il punteggio?',exEn:'What\'s the score?'},
    {it:'vincere',en:'to win',cat:'Sport',ipa:'/ˈvin.tʃe.re/',ex:'Abbiamo vinto!',exEn:'We won!'},
    {it:'perdere',en:'to lose',cat:'Sport',ipa:'/ˈpɛr.de.re/',ex:'Abbiamo perso purtroppo.',exEn:'We lost unfortunately.'},
    {it:'pareggiare',en:'to draw / tie',cat:'Sport',ipa:'/paˈrɛdʒ.dʒaː.re/',ex:'La partita è finita in pareggio.',exEn:'The match ended in a draw.'},
    {it:'allenarsi',en:'to train / work out',cat:'Sport',ipa:'/alleˈnar.si/',ex:'Mi alleno tre volte a settimana.',exEn:'I train three times a week.'},
    {it:'la palestra',en:'the gym',cat:'Sport',ipa:'/la paˈlɛs.tra/',ex:'Vado in palestra.',exEn:'I go to the gym.'},
    {it:'il nuoto',en:'swimming',cat:'Sport',ipa:'/il ˈnwɔː.to/',ex:'Pratico il nuoto.',exEn:'I swim.'},
    {it:'la piscina',en:'the swimming pool',cat:'Sport',ipa:'/la piˈʃiː.na/',ex:'Vado in piscina.',exEn:'I go to the pool.'},
    {it:'la corsa',en:'running',cat:'Sport',ipa:'/la ˈkor.sa/',ex:'Faccio la corsa ogni mattina.',exEn:'I go running every morning.'},
    {it:'la bicicletta',en:'cycling / bicycle',cat:'Sport',ipa:'/la bitʃiˈklɛt.ta/',ex:'Faccio bicicletta.',exEn:'I cycle.'},
    {it:'il tennis',en:'tennis',cat:'Sport',ipa:'/il ˈtɛn.nis/',ex:'Gioco a tennis.',exEn:'I play tennis.'},
    {it:'il basket',en:'basketball',cat:'Sport',ipa:'/il ˈbas.kɛt/',ex:'La squadra di basket.',exEn:'The basketball team.'},
    {it:'il nuoto',en:'swimming',cat:'Sport',ipa:'/il ˈnwɔː.to/',ex:'Pratico il nuoto agonistico.',exEn:'I do competitive swimming.'},
    {it:'il campionato',en:'the championship / league',cat:'Sport',ipa:'/il kampjoˈnaː.to/',ex:'Il campionato di Serie A.',exEn:'The Serie A championship.'},
    {it:'la coppa',en:'the cup / trophy',cat:'Sport',ipa:'/la ˈkɔp.pa/',ex:'Hanno vinto la coppa!',exEn:'They won the cup!'},
    {it:'il tifoso',en:'the fan / supporter',cat:'Sport',ipa:'/il tiˈfoː.zo/',ex:'Sono un tifoso della Juve.',exEn:'I\'m a Juventus fan.'},
    {it:'lo stadio',en:'the stadium',cat:'Sport',ipa:'/lo ˈstaː.djo/',ex:'Lo stadio è pieno.',exEn:'The stadium is full.'},
    {it:'la pallavolo',en:'volleyball',cat:'Sport',ipa:'/la pallaˈvɔː.lo/',ex:'Gioco a pallavolo.',exEn:'I play volleyball.'},
    {it:'il nuotatore',en:'the swimmer',cat:'Sport',ipa:'/il nwotaˈtoː.re/',ex:'È un nuotatore professionista.',exEn:'He\'s a professional swimmer.'},
    {it:'l\'atletica',en:'athletics',cat:'Sport',ipa:'/laˈtlɛː.ti.ka/',ex:'Pratico l\'atletica.',exEn:'I do athletics.'},
    {it:'la ginnastica',en:'gymnastics',cat:'Sport',ipa:'/la dʒinˈnas.ti.ka/',ex:'La ginnastica artistica.',exEn:'Artistic gymnastics.'},
    {it:'lo sci',en:'skiing',cat:'Sport',ipa:'/lo ʃiː/',ex:'Vado a sciare in inverno.',exEn:'I go skiing in winter.'},
    {it:'il surf',en:'surfing',cat:'Sport',ipa:'/il sɜːrf/',ex:'Faccio surf.',exEn:'I surf.'},
    {it:'la vela',en:'sailing',cat:'Sport',ipa:'/la ˈveː.la/',ex:'Pratico la vela.',exEn:'I sail.'},
    {it:'il cinema',en:'the cinema',cat:'Leisure',ipa:'/il ˈtʃiː.ne.ma/',ex:'Andiamo al cinema stasera?',exEn:'Shall we go to the cinema tonight?'},
    {it:'il teatro',en:'the theatre',cat:'Leisure',ipa:'/il teˈaː.tro/',ex:'Ho i biglietti per il teatro.',exEn:'I have theatre tickets.'},
    {it:'la musica',en:'music',cat:'Leisure',ipa:'/la ˈmuː.zi.ka/',ex:'Ascolto la musica jazz.',exEn:'I listen to jazz music.'},
    {it:'il concerto',en:'the concert',cat:'Leisure',ipa:'/il konˈtʃɛr.to/',ex:'Vado a un concerto.',exEn:'I\'m going to a concert.'},
    {it:'il festival',en:'the festival',cat:'Leisure',ipa:'/il feˈstiː.val/',ex:'Il festival di musica.',exEn:'The music festival.'},
    {it:'l\'hobby',en:'the hobby',cat:'Leisure',ipa:'/ˈlɔb.bi/',ex:'Il mio hobby è la fotografia.',exEn:'My hobby is photography.'},
    {it:'la lettura',en:'reading',cat:'Leisure',ipa:'/la letˈtuː.ra/',ex:'La lettura è il mio passatempo.',exEn:'Reading is my pastime.'},
    {it:'il viaggio',en:'travel / journey',cat:'Leisure',ipa:'/il ˈvjadʒ.dʒo/',ex:'Il viaggio è stato lungo.',exEn:'The journey was long.'},
    {it:'la gita',en:'the day trip / excursion',cat:'Leisure',ipa:'/la ˈdʒiː.ta/',ex:'Facciamo una gita.',exEn:'Let\'s go on a day trip.'},
    {it:'il parco',en:'the park',cat:'Leisure',ipa:'/il ˈpar.ko/',ex:'Passeggio nel parco.',exEn:'I walk in the park.'},
    {it:'il picnic',en:'the picnic',cat:'Leisure',ipa:'/il ˈpik.nik/',ex:'Facciamo un picnic!',exEn:'Let\'s have a picnic!'},
    {it:'il bar',en:'the café / bar',cat:'Leisure',ipa:'/il bar/',ex:'Ci vediamo al bar.',exEn:'Let\'s meet at the café.'},
    {it:'la discoteca',en:'the nightclub',cat:'Leisure',ipa:'/la diskoˈtɛː.ka/',ex:'Andiamo in discoteca!',exEn:'Let\'s go to the nightclub!'},
    {it:'il ristorante',en:'the restaurant',cat:'Leisure',ipa:'/il ristoˈran.te/',ex:'Ceniamo al ristorante.',exEn:'Let\'s have dinner at a restaurant.'},
    {it:'la passeggiata',en:'the walk / stroll',cat:'Leisure',ipa:'/la pasedˈdʒaː.ta/',ex:'Facciamo una passeggiata.',exEn:'Let\'s go for a walk.'},
    {it:'il riposo',en:'rest / relaxation',cat:'Leisure',ipa:'/il riˈpɔː.zo/',ex:'Ho bisogno di riposo.',exEn:'I need rest.'},
    {it:'divertirsi',en:'to enjoy oneself',cat:'Leisure',ipa:'/diverˈtir.si/',ex:'Mi sono divertito molto.',exEn:'I enjoyed myself a lot.'},
  ]
};

window.PACK_sports.words.push(
  {it:'il campione',en:'champion',cat:'Sport',ipa:'/il kamˈpjoː.ne/',ex:'È il campione del mondo.',exEn:'He\'s the world champion.'},
  {it:'il record',en:'record',cat:'Sport',ipa:'/il ˈreː.kord/',ex:'Ha battuto il record.',exEn:'He broke the record.'},
  {it:'l\'olimpiade',en:'the Olympics',cat:'Sport',ipa:'/loˈlim.pja.de/',ex:'Le Olimpiadi sono ogni quattro anni.',exEn:'The Olympics are every four years.'},
  {it:'la medaglia',en:'medal',cat:'Sport',ipa:'/la meˈdaʎ.ʎa/',ex:'Ha vinto la medaglia d\'oro.',exEn:'She won the gold medal.'},
  {it:'il podio',en:'podium',cat:'Sport',ipa:'/il ˈpɔː.djo/',ex:'È salito sul podio.',exEn:'He got on the podium.'},
  {it:'il professionista',en:'professional',cat:'Sport',ipa:'/il professionˈis.ta/',ex:'È un atleta professionista.',exEn:'He\'s a professional athlete.'},
  {it:'dilettante',en:'amateur',cat:'Sport',ipa:'/diletˈtan.te/',ex:'Sono un dilettante.',exEn:'I\'m an amateur.'},
  {it:'la gara',en:'the race / competition',cat:'Sport',ipa:'/la ˈɡaː.ra/',ex:'Partecipo alla gara.',exEn:'I\'m entering the race.'},
  {it:'il torneo',en:'tournament',cat:'Sport',ipa:'/il torˈnɛː.o/',ex:'Il torneo di tennis.',exEn:'The tennis tournament.'},
  {it:'la finale',en:'the final',cat:'Sport',ipa:'/la fiˈnaː.le/',ex:'Siamo in finale!',exEn:'We\'re in the final!'},
  {it:'la semifinale',en:'semifinal',cat:'Sport',ipa:'/la semifiˈnaː.le/',ex:'Abbiamo vinto la semifinale.',exEn:'We won the semi-final.'},
  {it:'il tiro',en:'shot / throw',cat:'Sport',ipa:'/il ˈtiː.ro/',ex:'Un tiro in porta.',exEn:'A shot at goal.'},
  {it:'il passaggio',en:'pass',cat:'Sport',ipa:'/il pasˈsadʒ.dʒo/',ex:'Un passaggio preciso.',exEn:'A precise pass.'},
  {it:'la difesa',en:'defence',cat:'Sport',ipa:'/la diˈfeː.za/',ex:'La difesa è solida.',exEn:'The defence is solid.'},
  {it:'l\'attacco',en:'attack',cat:'Sport',ipa:'/latˈtak.ko/',ex:'L\'attacco è brillante.',exEn:'The attack is brilliant.'},
  {it:'il portiere',en:'goalkeeper',cat:'Sport',ipa:'/il porˈtjeː.re/',ex:'Il portiere ha parato.',exEn:'The goalkeeper saved it.'},
  {it:'il centrocampista',en:'midfielder',cat:'Sport',ipa:'/il tʃentrokamˈpis.ta/',ex:'Il centrocampista ha segnato.',exEn:'The midfielder scored.'},
  {it:'il ciclismo',en:'cycling',cat:'Sport',ipa:'/il tʃiˈkliz.mo/',ex:'Il ciclismo è popolare.',exEn:'Cycling is popular.'},
  {it:'il nuotatore',en:'swimmer',cat:'Sport',ipa:'/il nwotaˈtoː.re/',ex:'È un nuotatore veloce.',exEn:'He\'s a fast swimmer.'},
  {it:'la maratona',en:'marathon',cat:'Sport',ipa:'/la maˈraː.to.na/',ex:'Corro la maratona.',exEn:'I run the marathon.'},
  {it:'il triathlon',en:'triathlon',cat:'Sport',ipa:'/il triˈatlon/',ex:'Partecipo al triathlon.',exEn:'I\'m doing the triathlon.'},
  {it:'la boxe',en:'boxing',cat:'Sport',ipa:'/la bɔks/',ex:'Pratico la boxe.',exEn:'I do boxing.'},
  {it:'le arti marziali',en:'martial arts',cat:'Sport',ipa:'/le ˈar.ti marˈtsjaː.li/',ex:'Pratico le arti marziali.',exEn:'I do martial arts.'},
  {it:'il golf',en:'golf',cat:'Sport',ipa:'/il ɡɔlf/',ex:'Gioco a golf.',exEn:'I play golf.'},
  {it:'il rugby',en:'rugby',cat:'Sport',ipa:'/il ˈrʌɡ.bi/',ex:'Gioco a rugby.',exEn:'I play rugby.'},
  {it:'la pallacanestro',en:'basketball',cat:'Sport',ipa:'/la pallakaˈnɛs.tro/',ex:'La pallacanestro americana.',exEn:'American basketball.'},
  {it:'l\'equitazione',en:'horse riding / equestrianism',cat:'Sport',ipa:'/lekwi.tatˈtsjoː.ne/',ex:'Pratico l\'equitazione.',exEn:'I go horse riding.'},
  {it:'la scherma',en:'fencing',cat:'Sport',ipa:'/la ˈskɛr.ma/',ex:'La scherma è uno sport elegante.',exEn:'Fencing is an elegant sport.'},
  {it:'il tiro con l\'arco',en:'archery',cat:'Sport',ipa:'/il ˈtiː.ro kon ˈlar.ko/',ex:'Il tiro con l\'arco richiede concentrazione.',exEn:'Archery requires concentration.'},
  {it:'l\'arrampicata',en:'climbing',cat:'Sport',ipa:'/larrampˈiː.kaː.ta/',ex:'L\'arrampicata su roccia.',exEn:'Rock climbing.'},
  {it:'il paracadutismo',en:'skydiving',cat:'Sport',ipa:'/il parakadutˈiz.mo/',ex:'Ho fatto il paracadutismo.',exEn:'I went skydiving.'},
  {it:'il fitness',en:'fitness',cat:'Sport',ipa:'/il ˈfit.nis/',ex:'Faccio fitness ogni mattina.',exEn:'I do fitness every morning.'},
  {it:'lo yoga',en:'yoga',cat:'Sport',ipa:'/lo ˈjoː.ɡa/',ex:'Pratico lo yoga.',exEn:'I do yoga.'},
  {it:'il pilates',en:'pilates',cat:'Sport',ipa:'/il piˈlaː.tes/',ex:'Faccio pilates.',exEn:'I do pilates.'},
  {it:'lo stretching',en:'stretching',cat:'Sport',ipa:'/lo ˈstretʃ.ɪŋ/',ex:'Faccio stretching dopo l\'allenamento.',exEn:'I stretch after the workout.'},
  {it:'il riscaldamento',en:'warm-up',cat:'Sport',ipa:'/il riskaldaˈmɛn.to/',ex:'Il riscaldamento è importante.',exEn:'The warm-up is important.'},
  {it:'il raffreddamento',en:'cool-down',cat:'Sport',ipa:'/il raffredˈdaˈmɛn.to/',ex:'Faccio il raffreddamento.',exEn:'I do the cool-down.'},
  {it:'il personal trainer',en:'personal trainer',cat:'Sport',ipa:'/il ˈpɜːsənl ˈtreɪnər/',ex:'Il mio personal trainer.',exEn:'My personal trainer.'},
  {it:'i pesi',en:'weights',cat:'Sport',ipa:'/i ˈpeː.zi/',ex:'Sollevo i pesi.',exEn:'I lift weights.'},
  {it:'il tapis roulant',en:'treadmill',cat:'Sport',ipa:'/il tapi ruˈlɑ̃/',ex:'Corro sul tapis roulant.',exEn:'I run on the treadmill.'},
  {it:'il cronometro',en:'stopwatch',cat:'Sport',ipa:'/il kroˈnɔː.me.tro/',ex:'Start il cronometro.',exEn:'Start the stopwatch.'},
  {it:'il fischio',en:'whistle',cat:'Sport',ipa:'/il ˈfis.kjo/',ex:'Il fischio dell\'arbitro.',exEn:'The referee\'s whistle.'},
  {it:'il cartellino giallo',en:'yellow card',cat:'Sport',ipa:'/il kartelˈliː.no ˈdʒaɫ.lo/',ex:'Ha preso un cartellino giallo.',exEn:'He got a yellow card.'},
  {it:'il cartellino rosso',en:'red card',cat:'Sport',ipa:'/il kartelˈliː.no ˈrɔs.so/',ex:'È stato espulso con il rosso.',exEn:'He was sent off with a red card.'},
  {it:'il fuorigioco',en:'offside',cat:'Sport',ipa:'/il fwɔˈridʒɔː.ko/',ex:'Era in fuorigioco.',exEn:'He was offside.'},
  {it:'il rigore',en:'penalty',cat:'Sport',ipa:'/il riˈɡɔː.re/',ex:'Ha segnato su rigore.',exEn:'He scored from a penalty.'},
  {it:'l\'angolo',en:'corner kick',cat:'Sport',ipa:'/ˈlaŋ.ɡo.lo/',ex:'Tira un calcio d\'angolo.',exEn:'He takes a corner kick.'},
  {it:'la rimessa',en:'throw-in',cat:'Sport',ipa:'/la riˈmɛs.sa/',ex:'La rimessa laterale.',exEn:'The throw-in.'},
  {it:'il supplementare',en:'extra time',cat:'Sport',ipa:'/il suppleˈmɛn.ta.re/',ex:'Siamo ai supplementari.',exEn:'We\'re in extra time.'},
  {it:'i rigori',en:'penalty shoot-out',cat:'Sport',ipa:'/i riˈɡɔː.ri/',ex:'Vincono ai rigori.',exEn:'They win on penalties.'}
);
