window.PACK_tech = {
  id:'tech', name:'Technology & Media', emoji:'💻',
  words:[
    {it:'il computer',en:'the computer',cat:'Tech',ipa:'/il komˈpjuː.ter/',ex:'Il mio computer è lento.',exEn:'My computer is slow.'},
    {it:'il telefono',en:'the phone',cat:'Tech',ipa:'/il teˈlɛː.fo.no/',ex:'Il mio telefono è scarico.',exEn:'My phone is flat.'},
    {it:'lo smartphone',en:'the smartphone',cat:'Tech',ipa:'/lo ˈsmɑːrt.foʊn/',ex:'Ho perso il mio smartphone.',exEn:'I lost my smartphone.'},
    {it:'il tablet',en:'the tablet',cat:'Tech',ipa:'/il ˈtæb.lɪt/',ex:'Leggo sul tablet.',exEn:'I read on the tablet.'},
    {it:'internet',en:'the internet',cat:'Tech',ipa:'/inˈtɛr.net/',ex:'Ho bisogno di internet.',exEn:'I need the internet.'},
    {it:'il wifi',en:'wifi',cat:'Tech',ipa:'/il ˈwaɪ.faɪ/',ex:'Qual è la password del wifi?',exEn:'What\'s the wifi password?'},
    {it:'la password',en:'the password',cat:'Tech',ipa:'/la ˈpas.wɜrd/',ex:'Ho dimenticato la password.',exEn:'I forgot the password.'},
    {it:'l\'email',en:'the email',cat:'Tech',ipa:'/liˈmeɪl/',ex:'Ti mando una email.',exEn:'I\'ll send you an email.'},
    {it:'il messaggio',en:'the message',cat:'Tech',ipa:'/il mesˈsadʒ.dʒo/',ex:'Ho ricevuto un messaggio.',exEn:'I received a message.'},
    {it:'il sito web',en:'the website',cat:'Tech',ipa:'/il ˈsiː.to wɛb/',ex:'Il sito web è aggiornato.',exEn:'The website is updated.'},
    {it:'l\'applicazione',en:'the app',cat:'Tech',ipa:'/lapplicatˈtsjoː.ne/',ex:'Scarico l\'applicazione.',exEn:'I\'m downloading the app.'},
    {it:'scaricare',en:'to download',cat:'Tech',ipa:'/skariˈkaː.re/',ex:'Scarico il file.',exEn:'I\'m downloading the file.'},
    {it:'caricare',en:'to upload / charge',cat:'Tech',ipa:'/kariˈkaː.re/',ex:'Carico il telefono.',exEn:'I\'m charging my phone.'},
    {it:'il caricatore',en:'the charger',cat:'Tech',ipa:'/il karikaˈtoː.re/',ex:'Hai il caricatore?',exEn:'Do you have the charger?'},
    {it:'la batteria',en:'the battery',cat:'Tech',ipa:'/la batteˈriː.a/',ex:'La batteria è scarica.',exEn:'The battery is flat.'},
    {it:'la schermata',en:'the screen',cat:'Tech',ipa:'/la skerˈmaː.ta/',ex:'La schermata è rotta.',exEn:'The screen is broken.'},
    {it:'cliccare',en:'to click',cat:'Tech',ipa:'/klikˈkaː.re/',ex:'Clicca qui.',exEn:'Click here.'},
    {it:'il collegamento',en:'the link / connection',cat:'Tech',ipa:'/il kolleˈɡaˈmɛn.to/',ex:'Manda il collegamento.',exEn:'Send the link.'},
    {it:'i social media',en:'social media',cat:'Tech',ipa:'/i ˈsoʊ.ʃəl ˈmiː.djə/',ex:'Uso i social media ogni giorno.',exEn:'I use social media every day.'},
    {it:'il profilo',en:'the profile',cat:'Tech',ipa:'/il proˈfiː.lo/',ex:'Il mio profilo è privato.',exEn:'My profile is private.'},
    {it:'seguire',en:'to follow',cat:'Tech',ipa:'/seˈɡwiː.re/',ex:'Seguimi su Instagram.',exEn:'Follow me on Instagram.'},
    {it:'condividere',en:'to share',cat:'Tech',ipa:'/kondiˈviː.de.re/',ex:'Condividi questo post.',exEn:'Share this post.'},
    {it:'il like',en:'the like',cat:'Tech',ipa:'/il laɪk/',ex:'Ha ricevuto molti like.',exEn:'He got many likes.'},
    {it:'il commento',en:'the comment',cat:'Tech',ipa:'/il komˈmɛn.to/',ex:'Ho lasciato un commento.',exEn:'I left a comment.'},
    {it:'il videogioco',en:'the video game',cat:'Tech',ipa:'/il viˈdɛː.o.ˈdʒɔː.ko/',ex:'Gioco ai videogiochi.',exEn:'I play video games.'},
    {it:'la televisione',en:'the television',cat:'Tech',ipa:'/la televˈiː.zjoː.ne/',ex:'Guardo la televisione.',exEn:'I watch television.'},
    {it:'la radio',en:'the radio',cat:'Tech',ipa:'/la ˈraː.djo/',ex:'Ascolto la radio in macchina.',exEn:'I listen to the radio in the car.'},
    {it:'il giornale',en:'the newspaper',cat:'Tech',ipa:'/il dʒorˈnaː.le/',ex:'Leggo il giornale.',exEn:'I read the newspaper.'},
    {it:'la rivista',en:'the magazine',cat:'Tech',ipa:'/la riˈvis.ta/',ex:'Una rivista di moda.',exEn:'A fashion magazine.'},
    {it:'il podcast',en:'the podcast',cat:'Tech',ipa:'/il ˈpɒd.kɑːst/',ex:'Ascolto un podcast.',exEn:'I listen to a podcast.'},
    {it:'la fotografia',en:'the photograph',cat:'Tech',ipa:'/la fotografˈiː.a/',ex:'Faccio fotografie.',exEn:'I take photographs.'},
    {it:'la fotocamera',en:'the camera',cat:'Tech',ipa:'/la fotoˈkaː.me.ra/',ex:'La fotocamera è professionale.',exEn:'The camera is professional.'},
    {it:'il cloud',en:'the cloud',cat:'Tech',ipa:'/il klaʊd/',ex:'Salvo i file nel cloud.',exEn:'I save files in the cloud.'},
    {it:'il backup',en:'the backup',cat:'Tech',ipa:'/il ˈbæk.ʌp/',ex:'Faccio il backup ogni giorno.',exEn:'I do a backup every day.'},
    {it:'il virus',en:'the virus',cat:'Tech',ipa:'/il ˈviː.rus/',ex:'Il computer ha un virus.',exEn:'The computer has a virus.'},
    {it:'il codice',en:'the code',cat:'Tech',ipa:'/il ˈkɔː.di.tʃe/',ex:'Inserisci il codice.',exEn:'Enter the code.'},
    {it:'la stampante',en:'the printer',cat:'Tech',ipa:'/la stamˈpan.te/',ex:'La stampante non funziona.',exEn:'The printer doesn\'t work.'},
    {it:'stampare',en:'to print',cat:'Tech',ipa:'/stamˈpaː.re/',ex:'Devo stampare il documento.',exEn:'I need to print the document.'},
    {it:'il documento',en:'the document / file',cat:'Tech',ipa:'/il dokˈuː.mɛn.to/',ex:'Allego il documento.',exEn:'I\'m attaching the document.'},
    {it:'salvare',en:'to save',cat:'Tech',ipa:'/salˈvaː.re/',ex:'Salva il file!',exEn:'Save the file!'},
    {it:'cancellare',en:'to delete',cat:'Tech',ipa:'/kantʃelˈlaː.re/',ex:'Ho cancellato il file per sbaglio.',exEn:'I deleted the file by mistake.'},
    {it:'aggiornare',en:'to update',cat:'Tech',ipa:'/addʒorˈnaː.re/',ex:'Aggiorna il sistema.',exEn:'Update the system.'},
    {it:'il sistema operativo',en:'the operating system',cat:'Tech',ipa:'/il sisˈteː.ma operaˈtiː.vo/',ex:'Quale sistema operativo usi?',exEn:'Which operating system do you use?'},
    {it:'la tastiera',en:'the keyboard',cat:'Tech',ipa:'/la tasˈtjeː.ra/',ex:'La tastiera è italiana.',exEn:'The keyboard is Italian.'},
    {it:'il mouse',en:'the mouse',cat:'Tech',ipa:'/il maʊs/',ex:'Il mouse non funziona.',exEn:'The mouse doesn\'t work.'},
    {it:'la stampante 3D',en:'3D printer',cat:'Tech',ipa:'/la stamˈpan.te ˈtreː diː/',ex:'Ho una stampante 3D.',exEn:'I have a 3D printer.'},
    {it:'l\'intelligenza artificiale',en:'artificial intelligence',cat:'Tech',ipa:'/lintelˈlidʒɛntsa artifiˈtʃaː.le/',ex:'L\'intelligenza artificiale cambia tutto.',exEn:'Artificial intelligence changes everything.'},
    {it:'il robot',en:'the robot',cat:'Tech',ipa:'/il ˈroː.bot/',ex:'I robot sostituiranno gli umani?',exEn:'Will robots replace humans?'},
    {it:'la connessione',en:'the connection',cat:'Tech',ipa:'/la konnesˈsjoː.ne/',ex:'La connessione è lenta.',exEn:'The connection is slow.'},
    {it:'lo streaming',en:'streaming',cat:'Tech',ipa:'/lo ˈstriː.mɪŋ/',ex:'Guardo lo streaming.',exEn:'I watch streaming.'},
    {it:'la piattaforma',en:'the platform',cat:'Tech',ipa:'/la pjatˈtaː.for.ma/',ex:'Una piattaforma digitale.',exEn:'A digital platform.'},
  ]
};

window.PACK_tech.words.push(
  {it:'il cavo',en:'cable',cat:'Tech',ipa:'/il ˈkaː.vo/',ex:'Il cavo HDMI.',exEn:'The HDMI cable.'},
  {it:'la porta USB',en:'USB port',cat:'Tech',ipa:'/la ˈpɔr.ta uˈɛs.biː/',ex:'La porta USB è rotta.',exEn:'The USB port is broken.'},
  {it:'il disco rigido',en:'hard drive',cat:'Tech',ipa:'/il ˈdis.ko ˈriː.dʒi.do/',ex:'Il disco rigido è pieno.',exEn:'The hard drive is full.'},
  {it:'la memoria',en:'memory',cat:'Tech',ipa:'/la meˈmoː.rja/',ex:'La memoria è insufficiente.',exEn:'The memory is insufficient.'},
  {it:'il monitor',en:'monitor',cat:'Tech',ipa:'/il moˈniː.tor/',ex:'Un monitor ad alta risoluzione.',exEn:'A high-resolution monitor.'},
  {it:'il touchscreen',en:'touchscreen',cat:'Tech',ipa:'/il ˈtʌtʃ.skriːn/',ex:'Ha un touchscreen sensibile.',exEn:'It has a sensitive touchscreen.'},
  {it:'la realtà virtuale',en:'virtual reality',cat:'Tech',ipa:'/la reˈalˈta virˈtwaː.le/',ex:'La realtà virtuale immersiva.',exEn:'Immersive virtual reality.'},
  {it:'l\'algoritmo',en:'algorithm',cat:'Tech',ipa:'/lalˈɡɔː.rit.mo/',ex:'L\'algoritmo dei social media.',exEn:'The social media algorithm.'},
  {it:'il database',en:'database',cat:'Tech',ipa:'/il ˈdeɪ.tə.beɪs/',ex:'Il database è sicuro.',exEn:'The database is secure.'},
  {it:'il server',en:'server',cat:'Tech',ipa:'/il ˈsɜːr.vər/',ex:'Il server è down.',exEn:'The server is down.'},
  {it:'il firewall',en:'firewall',cat:'Tech',ipa:'/il ˈfaɪər.wɔːl/',ex:'Il firewall protegge il sistema.',exEn:'The firewall protects the system.'},
  {it:'la VPN',en:'VPN',cat:'Tech',ipa:'/la viːpiːˈɛn/',ex:'Uso una VPN.',exEn:'I use a VPN.'},
  {it:'l\'interfaccia',en:'interface',cat:'Tech',ipa:'/linterˈfat.tʃa/',ex:'Un\'interfaccia intuitiva.',exEn:'An intuitive interface.'},
  {it:'il browser',en:'browser',cat:'Tech',ipa:'/il ˈbraʊ.zər/',ex:'Quale browser usi?',exEn:'Which browser do you use?'},
  {it:'la notifica',en:'notification',cat:'Tech',ipa:'/la noˈtiː.fi.ka/',ex:'Ho una notifica.',exEn:'I have a notification.'},
  {it:'il bluetooth',en:'bluetooth',cat:'Tech',ipa:'/il ˈbluː.tuːθ/',ex:'Connetti via bluetooth.',exEn:'Connect via bluetooth.'},
  {it:'il GPS',en:'GPS',cat:'Tech',ipa:'/il dʒiːpiːˈɛs/',ex:'Il GPS è acceso.',exEn:'The GPS is on.'},
  {it:'lo smartwatch',en:'smartwatch',cat:'Tech',ipa:'/lo ˈsmɑːrt.wɒtʃ/',ex:'Ho uno smartwatch.',exEn:'I have a smartwatch.'},
  {it:'l\'assistente vocale',en:'voice assistant',cat:'Tech',ipa:'/lassiˈstɛn.te voˈkaː.le/',ex:'L\'assistente vocale risponde.',exEn:'The voice assistant answers.'},
  {it:'il drone',en:'drone',cat:'Tech',ipa:'/il droʊn/',ex:'Un drone di sorveglianza.',exEn:'A surveillance drone.'},
  {it:'la webcam',en:'webcam',cat:'Tech',ipa:'/la ˈwɛb.kæm/',ex:'La webcam funziona?',exEn:'Is the webcam working?'},
  {it:'il microfono',en:'microphone',cat:'Tech',ipa:'/il miˈkrɔː.fo.no/',ex:'Il microfono è acceso.',exEn:'The microphone is on.'},
  {it:'le cuffie',en:'headphones',cat:'Tech',ipa:'/le ˈkuf.fje/',ex:'Le cuffie sono senza filo.',exEn:'The headphones are wireless.'},
  {it:'gli auricolari',en:'earbuds',cat:'Tech',ipa:'/ʎi awriˈkoː.la.ri/',ex:'Gli auricolari bluetooth.',exEn:'Bluetooth earbuds.'},
  {it:'la console di gioco',en:'game console',cat:'Tech',ipa:'/la ˈkon.sole di ˈdʒɔː.ko/',ex:'La console di gioco è nuova.',exEn:'The game console is new.'},
  {it:'il bug',en:'bug (software)',cat:'Tech',ipa:'/il bʌɡ/',ex:'C\'è un bug nel sistema.',exEn:'There\'s a bug in the system.'},
  {it:'il cybercrimine',en:'cybercrime',cat:'Tech',ipa:'/il ˈtʃaɪ.bər.kriː.mi.ne/',ex:'Il cybercrimine aumenta.',exEn:'Cybercrime is increasing.'},
  {it:'la sicurezza informatica',en:'IT security',cat:'Tech',ipa:'/la sikuˈrɛt.tsa informaˈtiː.ka/',ex:'La sicurezza informatica è prioritaria.',exEn:'IT security is a priority.'},
  {it:'l\'aggiornamento',en:'update',cat:'Tech',ipa:'/laddʒornaˈmɛn.to/',ex:'Installa l\'aggiornamento.',exEn:'Install the update.'},
  {it:'il metaverso',en:'metaverse',cat:'Tech',ipa:'/il metaˈvɛr.so/',ex:'Il metaverso è il futuro.',exEn:'The metaverse is the future.'},
  {it:'l\'internet delle cose',en:'Internet of Things',cat:'Tech',ipa:'/linˈtɛr.net ˈdɛl.le ˈkoː.ze/',ex:'L\'Internet delle cose.',exEn:'The Internet of Things.'},
  {it:'la smart home',en:'smart home',cat:'Tech',ipa:'/la smɑːrt hoʊm/',ex:'Ho una smart home.',exEn:'I have a smart home.'},
  {it:'la blockchain',en:'blockchain',cat:'Tech',ipa:'/la ˈblɒk.tʃeɪn/',ex:'La tecnologia blockchain.',exEn:'Blockchain technology.'},
  {it:'la criptovaluta',en:'cryptocurrency',cat:'Tech',ipa:'/la kriptovˈaː.lu.ta/',ex:'Le criptovalute sono volatili.',exEn:'Cryptocurrencies are volatile.'},
  {it:'il machine learning',en:'machine learning',cat:'Tech',ipa:'/il məˈʃiːn ˈlɜːnɪŋ/',ex:'Il machine learning avanzato.',exEn:'Advanced machine learning.'},
  {it:'il big data',en:'big data',cat:'Tech',ipa:'/il bɪɡ ˈdeɪ.tə/',ex:'Il big data è prezioso.',exEn:'Big data is valuable.'},
  {it:'il malware',en:'malware',cat:'Tech',ipa:'/il ˈmæl.wɛər/',ex:'Il malware ha infettato il PC.',exEn:'Malware infected the PC.'},
  {it:'il phishing',en:'phishing',cat:'Tech',ipa:'/il ˈfɪʃ.ɪŋ/',ex:'Un attacco di phishing.',exEn:'A phishing attack.'},
  {it:'la realtà aumentata',en:'augmented reality',cat:'Tech',ipa:'/la reˈalˈta awmentˈaː.ta/',ex:'La realtà aumentata.',exEn:'Augmented reality.'},
  {it:'in rete',en:'online / networked',cat:'Tech',ipa:'/in ˈreː.te/',ex:'Siamo tutti in rete.',exEn:'We\'re all connected online.'},
  {it:'il processore',en:'processor',cat:'Tech',ipa:'/il protʃesˈsoː.re/',ex:'Un processore veloce.',exEn:'A fast processor.'},
  {it:'la scheda grafica',en:'graphics card',cat:'Tech',ipa:'/la ˈskeː.da ˈɡra.fi.ka/',ex:'Una scheda grafica potente.',exEn:'A powerful graphics card.'},
  {it:'la risoluzione',en:'resolution',cat:'Tech',ipa:'/la rizoˈluː.tsjoː.ne/',ex:'Alta risoluzione.',exEn:'High resolution.'},
  {it:'l\'intelligenza artificiale',en:'artificial intelligence',cat:'Tech',ipa:'/lintelˈlidʒɛntsa artifiˈtʃaː.le/',ex:'L\'intelligenza artificiale.',exEn:'Artificial intelligence.'},
  {it:'il chatbot',en:'chatbot',cat:'Tech',ipa:'/il ˈtʃæt.bɒt/',ex:'Un chatbot intelligente.',exEn:'An intelligent chatbot.'},
  {it:'l\'app',en:'the app',cat:'Tech',ipa:'/lap/',ex:'Scarico l\'app.',exEn:'I download the app.'},
  {it:'il QR code',en:'QR code',cat:'Tech',ipa:'/il ˌkjuːˈɑːr koʊd/',ex:'Scansiona il QR code.',exEn:'Scan the QR code.'},
  {it:'la realtà mista',en:'mixed reality',cat:'Tech',ipa:'/la reˈalˈta ˈmis.ta/',ex:'La realtà mista.',exEn:'Mixed reality.'},
  {it:'lo streaming in diretta',en:'live streaming',cat:'Tech',ipa:'/lo ˈstriː.mɪŋ in diˈrɛt.ta/',ex:'Lo streaming in diretta.',exEn:'Live streaming.'}
);
