window.PACK_family = {
  id:'family', name:'Family & Relationships', emoji:'👨‍👩‍👧',
  words:[
    {it:'la famiglia',en:'the family',cat:'Family',ipa:'/la faˈmiʎ.ʎa/',ex:'La mia famiglia è grande.',exEn:'My family is big.'},
    {it:'il padre',en:'the father',cat:'Family',ipa:'/il ˈpaː.dre/',ex:'Mio padre lavora molto.',exEn:'My father works a lot.'},
    {it:'la madre',en:'the mother',cat:'Family',ipa:'/la ˈmaː.dre/',ex:'Mia madre cucina bene.',exEn:'My mother cooks well.'},
    {it:'il figlio',en:'the son',cat:'Family',ipa:'/il ˈfiʎ.ʎo/',ex:'Mio figlio ha cinque anni.',exEn:'My son is five years old.'},
    {it:'la figlia',en:'the daughter',cat:'Family',ipa:'/la ˈfiʎ.ʎa/',ex:'Mia figlia studia medicina.',exEn:'My daughter studies medicine.'},
    {it:'il fratello',en:'the brother',cat:'Family',ipa:'/il fraˈtɛl.lo/',ex:'Ho un fratello maggiore.',exEn:'I have an older brother.'},
    {it:'la sorella',en:'the sister',cat:'Family',ipa:'/la soˈrɛl.la/',ex:'Mia sorella abita a Milano.',exEn:'My sister lives in Milan.'},
    {it:'il nonno',en:'the grandfather',cat:'Family',ipa:'/il ˈnon.no/',ex:'Il nonno racconta storie.',exEn:'Grandfather tells stories.'},
    {it:'la nonna',en:'the grandmother',cat:'Family',ipa:'/la ˈnon.na/',ex:'La nonna fa la pasta.',exEn:'Grandmother makes pasta.'},
    {it:'il nipote',en:'the grandson / nephew',cat:'Family',ipa:'/il niˈpɔː.te/',ex:'Il mio nipote ha tre anni.',exEn:'My grandson is three years old.'},
    {it:'la nipote',en:'the granddaughter / niece',cat:'Family',ipa:'/la niˈpɔː.te/',ex:'La mia nipote studia danza.',exEn:'My niece studies dance.'},
    {it:'lo zio',en:'the uncle',cat:'Family',ipa:'/lo ˈdziː.o/',ex:'Mio zio vive in America.',exEn:'My uncle lives in America.'},
    {it:'la zia',en:'the aunt',cat:'Family',ipa:'/la ˈdziː.a/',ex:'Mia zia è molto divertente.',exEn:'My aunt is very funny.'},
    {it:'il cugino',en:'the cousin (m)',cat:'Family',ipa:'/il kuˈdʒiː.no/',ex:'Mio cugino gioca a calcio.',exEn:'My cousin plays football.'},
    {it:'la cugina',en:'the cousin (f)',cat:'Family',ipa:'/la kuˈdʒiː.na/',ex:'Mia cugina è molto simpatica.',exEn:'My cousin is very friendly.'},
    {it:'il marito',en:'the husband',cat:'Family',ipa:'/il maˈriː.to/',ex:'Mio marito è medico.',exEn:'My husband is a doctor.'},
    {it:'la moglie',en:'the wife',cat:'Family',ipa:'/la ˈmɔʎ.ʎe/',ex:'Mia moglie lavora in centro.',exEn:'My wife works in the centre.'},
    {it:'il fidanzato',en:'the boyfriend / fiancé',cat:'Family',ipa:'/il fidanˈtsaː.to/',ex:'Il mio fidanzato è italiano.',exEn:'My boyfriend is Italian.'},
    {it:'la fidanzata',en:'the girlfriend / fiancée',cat:'Family',ipa:'/la fidanˈtsaː.ta/',ex:'La mia fidanzata studia arte.',exEn:'My girlfriend studies art.'},
    {it:'il partner',en:'the partner',cat:'Family',ipa:'/il ˈpart.ner/',ex:'Il mio partner lavora a Roma.',exEn:'My partner works in Rome.'},
    {it:'i genitori',en:'the parents',cat:'Family',ipa:'/i dʒeniˈtoː.ri/',ex:'I miei genitori abitano a Napoli.',exEn:'My parents live in Naples.'},
    {it:'i figli',en:'the children',cat:'Family',ipa:'/i ˈfiʎ.ʎi/',ex:'Abbiamo due figli.',exEn:'We have two children.'},
    {it:'il bambino',en:'the child / boy',cat:'Family',ipa:'/il bamˈbiː.no/',ex:'Il bambino gioca in giardino.',exEn:'The child plays in the garden.'},
    {it:'la bambina',en:'the child / girl',cat:'Family',ipa:'/la bamˈbiː.na/',ex:'La bambina ride.',exEn:'The girl laughs.'},
    {it:'il ragazzo',en:'the boy / young man',cat:'Family',ipa:'/il raˈɡat.tso/',ex:'Il ragazzo studia all\'università.',exEn:'The young man studies at university.'},
    {it:'la ragazza',en:'the girl / young woman',cat:'Family',ipa:'/la raˈɡat.tsa/',ex:'La ragazza parla italiano.',exEn:'The young woman speaks Italian.'},
    {it:'l\'uomo',en:'the man',cat:'Family',ipa:'/ˈlwɔː.mo/',ex:'Quell\'uomo è mio padre.',exEn:'That man is my father.'},
    {it:'la donna',en:'the woman',cat:'Family',ipa:'/la ˈdɔn.na/',ex:'Quella donna è mia madre.',exEn:'That woman is my mother.'},
    {it:'il neonato',en:'the newborn / baby',cat:'Family',ipa:'/il neoˈnaː.to/',ex:'Il neonato dorme tutto il giorno.',exEn:'The baby sleeps all day.'},
    {it:'anziano',en:'elderly',cat:'Family',ipa:'/anˈtsjaː.no/',ex:'I miei nonni sono anziani.',exEn:'My grandparents are elderly.'},
    {it:'single',en:'single / unmarried',cat:'Family',ipa:'/ˈsiŋ.ɡol/',ex:'Sono single.',exEn:'I\'m single.'},
    {it:'sposato',en:'married',cat:'Family',ipa:'/spoˈzaː.to/',ex:'Siamo sposati da dieci anni.',exEn:'We\'ve been married for ten years.'},
    {it:'divorziato',en:'divorced',cat:'Family',ipa:'/divorˈtsjaː.to/',ex:'È divorziato.',exEn:'He is divorced.'},
    {it:'vedovo',en:'widowed',cat:'Family',ipa:'/ˈvɛː.do.vo/',ex:'È rimasto vedovo.',exEn:'He was left a widower.'},
    {it:'il matrimonio',en:'the marriage / wedding',cat:'Family',ipa:'/il matriˈmoː.njo/',ex:'Il matrimonio è in giugno.',exEn:'The wedding is in June.'},
    {it:'il divorzio',en:'the divorce',cat:'Family',ipa:'/il diˈvɔr.tsjo/',ex:'Hanno chiesto il divorzio.',exEn:'They asked for a divorce.'},
    {it:'l\'amico',en:'the friend (m)',cat:'Family',ipa:'/laˈmiː.ko/',ex:'Il mio migliore amico.',exEn:'My best friend.'},
    {it:'l\'amica',en:'the friend (f)',cat:'Family',ipa:'/laˈmiː.ka/',ex:'La mia amica si chiama Laura.',exEn:'My friend is called Laura.'},
    {it:'il collega',en:'the colleague',cat:'Family',ipa:'/il kolˈleː.ɡa/',ex:'Il mio collega è in riunione.',exEn:'My colleague is in a meeting.'},
    {it:'il vicino',en:'the neighbour',cat:'Family',ipa:'/il viˈtʃiː.no/',ex:'Il mio vicino è molto gentile.',exEn:'My neighbour is very kind.'},
    {it:'il conoscente',en:'the acquaintance',cat:'Family',ipa:'/il konoˈʃɛn.te/',ex:'È solo un conoscente.',exEn:'He\'s just an acquaintance.'},
    {it:'il suocero',en:'the father-in-law',cat:'Family',ipa:'/il ˈswɔː.tʃe.ro/',ex:'Mio suocero è pensionato.',exEn:'My father-in-law is retired.'},
    {it:'la suocera',en:'the mother-in-law',cat:'Family',ipa:'/la ˈswɔː.tʃe.ra/',ex:'Mia suocera cucina molto bene.',exEn:'My mother-in-law cooks very well.'},
    {it:'il cognato',en:'the brother-in-law',cat:'Family',ipa:'/il koɲˈɲaː.to/',ex:'Mio cognato è ingegnere.',exEn:'My brother-in-law is an engineer.'},
    {it:'la cognata',en:'the sister-in-law',cat:'Family',ipa:'/la koɲˈɲaː.ta/',ex:'Mia cognata viene a cena.',exEn:'My sister-in-law is coming for dinner.'},
    {it:'il padrino',en:'the godfather',cat:'Family',ipa:'/il paˈdriː.no/',ex:'Il mio padrino è mio zio.',exEn:'My godfather is my uncle.'},
    {it:'la madrina',en:'the godmother',cat:'Family',ipa:'/la maˈdriː.na/',ex:'La madrina è la mia zia.',exEn:'The godmother is my aunt.'},
    {it:'adottare',en:'to adopt',cat:'Family',ipa:'/adotˈtaː.re/',ex:'Hanno adottato un bambino.',exEn:'They adopted a child.'},
    {it:'crescere',en:'to grow up',cat:'Family',ipa:'/ˈkreʃ.ʃe.re/',ex:'Sono cresciuto a Firenze.',exEn:'I grew up in Florence.'},
    {it:'voler bene',en:'to love / care for',cat:'Family',ipa:'/voˈler ˈbɛː.ne/',ex:'Ti voglio bene.',exEn:'I love you (family/friends).'},
  ]
};

window.PACK_family.words.push(
  {it:'il gemello',en:'twin (m)',cat:'Family',ipa:'/il dʒeˈmɛl.lo/',ex:'Ho un fratello gemello.',exEn:'I have a twin brother.'},
  {it:'la gemella',en:'twin (f)',cat:'Family',ipa:'/la dʒeˈmɛl.la/',ex:'Sono gemelle identiche.',exEn:'They are identical twins.'},
  {it:'il figlio unico',en:'only child',cat:'Family',ipa:'/il ˈfiʎ.ʎo ˈuː.ni.ko/',ex:'È figlio unico.',exEn:'He\'s an only child.'},
  {it:'il maggiore',en:'the eldest',cat:'Family',ipa:'/il madˈdʒoː.re/',ex:'Il fratello maggiore.',exEn:'The eldest brother.'},
  {it:'il minore',en:'the youngest',cat:'Family',ipa:'/il miˈnoː.re/',ex:'Il fratello minore.',exEn:'The youngest brother.'},
  {it:'di mezza età',en:'middle-aged',cat:'Family',ipa:'/di ˈmɛdza eˈta/',ex:'È di mezza età.',exEn:'He\'s middle-aged.'},
  {it:'la tata',en:'the nanny / babysitter',cat:'Family',ipa:'/la ˈtaː.ta/',ex:'La tata porta i bambini a scuola.',exEn:'The nanny takes the children to school.'},
  {it:'il padrino',en:'godfather',cat:'Family',ipa:'/il paˈdriː.no/',ex:'Il mio padrino è mio zio.',exEn:'My godfather is my uncle.'},
  {it:'la famiglia allargata',en:'blended / extended family',cat:'Family',ipa:'/la faˈmiʎ.ʎa allarˈɡaː.ta/',ex:'Una famiglia allargata.',exEn:'A blended family.'},
  {it:'il parente',en:'the relative',cat:'Family',ipa:'/il paˈrɛn.te/',ex:'Viene tutta la parentela.',exEn:'All the relatives are coming.'},
  {it:'la parentela',en:'the relatives / kin',cat:'Family',ipa:'/la parenˈteː.la/',ex:'Ha una grande parentela.',exEn:'She has a large extended family.'},
  {it:'il capofamiglia',en:'the head of the family',cat:'Family',ipa:'/il kapoˈfamiʎʎa/',ex:'È il capofamiglia.',exEn:'He\'s the head of the family.'},
  {it:'l\'erede',en:'the heir',cat:'Family',ipa:'/leˈreː.de/',ex:'È l\'erede del nonno.',exEn:'He is the grandfather\'s heir.'},
  {it:'la discendenza',en:'descent / lineage',cat:'Family',ipa:'/la diʃʃenˈdɛn.tsa/',ex:'Di discendenza italiana.',exEn:'Of Italian descent.'},
  {it:'il clan',en:'the clan',cat:'Family',ipa:'/il klan/',ex:'Appartiene a un clan.',exEn:'He belongs to a clan.'},
  {it:'il compleanno',en:'the birthday',cat:'Family',ipa:'/il kompleˈan.no/',ex:'Buon compleanno!',exEn:'Happy birthday!'},
  {it:'l\'anniversario',en:'the anniversary',cat:'Family',ipa:'/lanniversˈaː.rjo/',ex:'Il nostro anniversario.',exEn:'Our anniversary.'},
  {it:'il Natale',en:'Christmas',cat:'Family',ipa:'/il naˈtaː.le/',ex:'A Natale siamo tutti insieme.',exEn:'At Christmas we\'re all together.'},
  {it:'la riunione di famiglia',en:'family reunion',cat:'Family',ipa:'/la rjuˈnjoː.ne di faˈmiʎ.ʎa/',ex:'Una riunione di famiglia.',exEn:'A family reunion.'},
  {it:'il cognome',en:'surname / family name',cat:'Family',ipa:'/il koɲˈɲoː.me/',ex:'Qual è il tuo cognome?',exEn:'What\'s your surname?'},
  {it:'il nome',en:'first name',cat:'Family',ipa:'/il ˈnoː.me/',ex:'Come ti chiami di nome?',exEn:'What\'s your first name?'},
  {it:'adottivo',en:'adopted',cat:'Family',ipa:'/adotˈtiː.vo/',ex:'È un figlio adottivo.',exEn:'He\'s an adopted child.'},
  {it:'convivere',en:'to live together / cohabit',cat:'Family',ipa:'/konˈviː.ve.re/',ex:'Convivono da due anni.',exEn:'They\'ve been living together for two years.'},
  {it:'separarsi',en:'to separate',cat:'Family',ipa:'/sepaˈrar.si/',ex:'Si sono separati.',exEn:'They separated.'},
  {it:'fidanzarsi',en:'to get engaged',cat:'Family',ipa:'/fidanˈtsar.si/',ex:'Si sono fidanzati.',exEn:'They got engaged.'},
  {it:'sposarsi',en:'to get married',cat:'Family',ipa:'/spoˈzar.si/',ex:'Si sono sposati in giugno.',exEn:'They got married in June.'},
  {it:'la promessa',en:'the promise / vow',cat:'Family',ipa:'/la proˈmɛs.sa/',ex:'Mantieni la promessa.',exEn:'Keep your promise.'},
  {it:'l\'affetto',en:'affection',cat:'Family',ipa:'/lafˈfɛt.to/',ex:'Provo molto affetto per lei.',exEn:'I feel great affection for her.'},
  {it:'il sostegno',en:'support',cat:'Family',ipa:'/il sosˈteɲ.ɲo/',ex:'La famiglia è il mio sostegno.',exEn:'Family is my support.'},
  {it:'educare',en:'to raise / educate',cat:'Family',ipa:'/eduˈkaː.re/',ex:'I genitori educano i figli.',exEn:'Parents raise their children.'},
  {it:'la cura',en:'care',cat:'Family',ipa:'/la ˈkuː.ra/',ex:'Prendersi cura degli anziani.',exEn:'Taking care of the elderly.'},
  {it:'il lutto',en:'mourning / bereavement',cat:'Family',ipa:'/il ˈlut.to/',ex:'È in lutto.',exEn:'He is in mourning.'},
  {it:'ereditare',en:'to inherit',cat:'Family',ipa:'/ereˈdiː.taː.re/',ex:'Ha ereditato la casa.',exEn:'She inherited the house.'},
  {it:'la dote',en:'dowry / talent',cat:'Family',ipa:'/la ˈdɔː.te/',ex:'Ha molte doti.',exEn:'She has many talents.'},
  {it:'custodire',en:'to look after / guard',cat:'Family',ipa:'/kustoˈdiː.re/',ex:'Custodisce i figli.',exEn:'She looks after the children.'},
  {it:'il battesimo',en:'christening / baptism',cat:'Family',ipa:'/il batˈteː.zi.mo/',ex:'Il battesimo del bambino.',exEn:'The baby\'s christening.'},
  {it:'la cerimonia',en:'the ceremony',cat:'Family',ipa:'/la tʃeriˈmoː.nja/',ex:'La cerimonia di matrimonio.',exEn:'The wedding ceremony.'},
  {it:'la luna di miele',en:'the honeymoon',cat:'Family',ipa:'/la ˈluː.na di ˈmjeː.le/',ex:'Vanno in luna di miele.',exEn:'They\'re going on their honeymoon.'},
  {it:'il fidanzamento',en:'the engagement',cat:'Family',ipa:'/il fidanˈtsaˈmɛn.to/',ex:'L\'anello di fidanzamento.',exEn:'The engagement ring.'},
  {it:'la proposta di matrimonio',en:'the marriage proposal',cat:'Family',ipa:'/la proˈpɔs.ta di matriˈmoː.njo/',ex:'Ha fatto la proposta di matrimonio.',exEn:'He made the marriage proposal.'},
  {it:'il tutore',en:'guardian',cat:'Family',ipa:'/il tuˈtoː.re/',ex:'Il tutore legale del bambino.',exEn:'The child\'s legal guardian.'},
  {it:'la custodia',en:'custody',cat:'Family',ipa:'/la kusˈtɔː.dja/',ex:'La custodia dei figli.',exEn:'Custody of the children.'},
  {it:'nascere',en:'to be born',cat:'Family',ipa:'/ˈnaʃ.ʃe.re/',ex:'Sono nato a Firenze.',exEn:'I was born in Florence.'},
  {it:'il nido',en:'nest / nursery',cat:'Family',ipa:'/il ˈniː.do/',ex:'Il bambino va al nido.',exEn:'The baby goes to nursery.'},
  {it:'la scuola materna',en:'kindergarten',cat:'Family',ipa:'/la ˈskwɔː.la maˈtɛr.na/',ex:'La scuola materna è vicina.',exEn:'The kindergarten is nearby.'},
  {it:'crescere insieme',en:'to grow up together',cat:'Family',ipa:'/ˈkreʃ.ʃe.re inˈsjeː.me/',ex:'Siamo cresciuti insieme.',exEn:'We grew up together.'},
  {it:'la lite',en:'the argument / quarrel',cat:'Family',ipa:'/la ˈliː.te/',ex:'Abbiamo avuto una lite.',exEn:'We had an argument.'},
  {it:'fare pace',en:'to make peace / make up',cat:'Family',ipa:'/ˈfaː.re ˈpaː.tʃe/',ex:'Abbiamo fatto pace.',exEn:'We made up.'},
  {it:'il perdono',en:'forgiveness',cat:'Family',ipa:'/il perˈdɔː.no/',ex:'Chiedo perdono.',exEn:'I ask for forgiveness.'},
  {it:'perdonare',en:'to forgive',cat:'Family',ipa:'/perdoˈnaː.re/',ex:'Ti perdono.',exEn:'I forgive you.'}
);
