window.PACK_travel = {
  id:'travel', name:'Getting Around', emoji:'🚂',
  words:[
    {it:'dove',en:'where',cat:'Travel',ipa:'/ˈdoː.ve/',ex:'Dove si trova la stazione?',exEn:'Where is the train station?'},
    {it:'la stazione',en:'the station',cat:'Travel',ipa:'/la statˈtsjoː.ne/',ex:'La stazione è vicina.',exEn:'The station is nearby.'},
    {it:'l\'aeroporto',en:'the airport',cat:'Travel',ipa:'/laeroˈpɔr.to/',ex:'Come arrivo all\'aeroporto?',exEn:'How do I get to the airport?'},
    {it:'il treno',en:'the train',cat:'Travel',ipa:'/il ˈtrɛː.no/',ex:'Il treno parte alle otto.',exEn:'The train leaves at eight.'},
    {it:'l\'autobus',en:'the bus',cat:'Travel',ipa:'/ˈlaw.to.bus/',ex:'Prendo l\'autobus ogni giorno.',exEn:'I take the bus every day.'},
    {it:'il biglietto',en:'the ticket',cat:'Travel',ipa:'/il biʎˈʎɛt.to/',ex:'Quanto costa il biglietto?',exEn:'How much does the ticket cost?'},
    {it:'l\'albergo',en:'the hotel',cat:'Travel',ipa:'/lalˈbɛr.ɡo/',ex:'L\'albergo è in centro.',exEn:'The hotel is in the city centre.'},
    {it:'la camera',en:'the room',cat:'Travel',ipa:'/la ˈkaː.me.ra/',ex:'La mia camera è al terzo piano.',exEn:'My room is on the third floor.'},
    {it:'destra',en:'right',cat:'Travel',ipa:'/ˈdɛs.tra/',ex:'Gira a destra.',exEn:'Turn right.'},
    {it:'sinistra',en:'left',cat:'Travel',ipa:'/siˈnis.tra/',ex:'È a sinistra della banca.',exEn:'It\'s to the left of the bank.'},
    {it:'dritto',en:'straight ahead',cat:'Travel',ipa:'/ˈdrit.to/',ex:'Vai sempre dritto.',exEn:'Go straight ahead.'},
    {it:'vicino',en:'near / close',cat:'Travel',ipa:'/viˈtʃiː.no/',ex:'È vicino alla piazza?',exEn:'Is it near the square?'},
    {it:'lontano',en:'far / distant',cat:'Travel',ipa:'/lonˈtaː.no/',ex:'No, non è lontano.',exEn:'No, it\'s not far.'},
    {it:'la mappa',en:'the map',cat:'Travel',ipa:'/la ˈmap.pa/',ex:'Hai una mappa della città?',exEn:'Do you have a city map?'},
    {it:'il passaporto',en:'the passport',cat:'Travel',ipa:'/il pasaˈpɔr.to/',ex:'Il passaporto è nella borsa.',exEn:'The passport is in the bag.'},
    {it:'il taxi',en:'the taxi',cat:'Travel',ipa:'/il ˈtak.si/',ex:'Chiamo un taxi.',exEn:'I\'ll call a taxi.'},
    {it:'la metropolitana',en:'the metro / subway',cat:'Travel',ipa:'/la metropoliˈtaː.na/',ex:'Prendo la metropolitana.',exEn:'I\'ll take the metro.'},
    {it:'il porto',en:'the port / harbour',cat:'Travel',ipa:'/il ˈpɔr.to/',ex:'Il porto è molto bello.',exEn:'The port is very beautiful.'},
    {it:'il traghetto',en:'the ferry',cat:'Travel',ipa:'/il traˈɡet.to/',ex:'Il traghetto parte alle dieci.',exEn:'The ferry leaves at ten.'},
    {it:'l\'aereo',en:'the plane',cat:'Travel',ipa:'/laˈɛː.re.o/',ex:'L\'aereo è in ritardo.',exEn:'The plane is delayed.'},
    {it:'la macchina',en:'the car',cat:'Travel',ipa:'/la ˈmak.ki.na/',ex:'Ho noleggiato una macchina.',exEn:'I have rented a car.'},
    {it:'la bicicletta',en:'the bicycle',cat:'Travel',ipa:'/la bitʃiˈklɛt.ta/',ex:'Vado in bicicletta.',exEn:'I\'m going by bicycle.'},
    {it:'a piedi',en:'on foot',cat:'Travel',ipa:'/a ˈpjɛː.di/',ex:'Andiamo a piedi.',exEn:'We\'re going on foot.'},
    {it:'il binario',en:'the platform / track',cat:'Travel',ipa:'/il biˈnaː.rjo/',ex:'Il treno è al binario tre.',exEn:'The train is at platform three.'},
    {it:'la partenza',en:'the departure',cat:'Travel',ipa:'/la parˈtɛn.tsa/',ex:'La partenza è alle quindici.',exEn:'The departure is at three.'},
    {it:'l\'arrivo',en:'the arrival',cat:'Travel',ipa:'/larˈriː.vo/',ex:'L\'arrivo è previsto alle sedici.',exEn:'Arrival is expected at four.'},
    {it:'il ritardo',en:'the delay',cat:'Travel',ipa:'/il riˈtar.do/',ex:'C\'è un ritardo di venti minuti.',exEn:'There is a twenty-minute delay.'},
    {it:'la prenotazione',en:'the reservation / booking',cat:'Travel',ipa:'/la prenotatˈtsjoː.ne/',ex:'Ho una prenotazione.',exEn:'I have a reservation.'},
    {it:'il check-in',en:'check-in',cat:'Travel',ipa:'/il ˈtʃɛk.in/',ex:'Il check-in è alle dodici.',exEn:'Check-in is at twelve.'},
    {it:'il check-out',en:'check-out',cat:'Travel',ipa:'/il ˈtʃɛk.awt/',ex:'Il check-out è alle undici.',exEn:'Check-out is at eleven.'},
    {it:'la reception',en:'reception / front desk',cat:'Travel',ipa:'/la reˈtsɛp.ʃon/',ex:'Vado alla reception.',exEn:'I\'m going to reception.'},
    {it:'il bagaglio',en:'luggage / baggage',cat:'Travel',ipa:'/il baˈɡaʎ.ʎo/',ex:'Ho perso il bagaglio.',exEn:'I\'ve lost my luggage.'},
    {it:'la valigia',en:'the suitcase',cat:'Travel',ipa:'/la vaˈliː.dʒa/',ex:'La mia valigia è pesante.',exEn:'My suitcase is heavy.'},
    {it:'lo zaino',en:'the backpack',cat:'Travel',ipa:'/lo ˈdzaː.i.no/',ex:'Ho tutto nello zaino.',exEn:'I have everything in the backpack.'},
    {it:'la carta di credito',en:'credit card',cat:'Travel',ipa:'/la ˈkar.ta di ˈkreː.di.to/',ex:'Accettate la carta di credito?',exEn:'Do you accept credit cards?'},
    {it:'il bancomat',en:'ATM / cash machine',cat:'Travel',ipa:'/il ˈbaŋ.ko.mat/',ex:'C\'è un bancomat qui vicino?',exEn:'Is there an ATM nearby?'},
    {it:'il cambio',en:'currency exchange',cat:'Travel',ipa:'/il ˈkam.bjo/',ex:'Dov\'è l\'ufficio di cambio?',exEn:'Where is the currency exchange?'},
    {it:'l\'ufficio turistico',en:'tourist office',cat:'Travel',ipa:'/lufˈfiː.tʃo tuˈris.ti.ko/',ex:'L\'ufficio turistico è in centro.',exEn:'The tourist office is in the centre.'},
    {it:'il museo',en:'the museum',cat:'Travel',ipa:'/il muˈzɛː.o/',ex:'Il museo apre alle nove.',exEn:'The museum opens at nine.'},
    {it:'la chiesa',en:'the church',cat:'Travel',ipa:'/la ˈkjeː.za/',ex:'La chiesa è bellissima.',exEn:'The church is very beautiful.'},
    {it:'il castello',en:'the castle',cat:'Travel',ipa:'/il kasˈtɛl.lo/',ex:'Il castello medievale è imponente.',exEn:'The medieval castle is imposing.'},
    {it:'la piazza',en:'the square',cat:'Travel',ipa:'/la ˈpjat.tsa/',ex:'Ci incontriamo in piazza.',exEn:'We\'ll meet in the square.'},
    {it:'la via',en:'the street / road',cat:'Travel',ipa:'/la ˈviː.a/',ex:'Via Roma è qui vicino.',exEn:'Via Roma is nearby.'},
    {it:'il semaforo',en:'the traffic light',cat:'Travel',ipa:'/il seˈmaː.fo.ro/',ex:'Gira al semaforo.',exEn:'Turn at the traffic light.'},
    {it:'l\'incrocio',en:'the crossroads',cat:'Travel',ipa:'/liŋˈkrɔː.tʃo/',ex:'Svolta all\'incrocio.',exEn:'Turn at the crossroads.'},
    {it:'il ponte',en:'the bridge',cat:'Travel',ipa:'/il ˈpɔn.te/',ex:'Attraversa il ponte.',exEn:'Cross the bridge.'},
    {it:'la farmacia',en:'the pharmacy',cat:'Travel',ipa:'/la farˈmaː.tʃa/',ex:'La farmacia è aperta?',exEn:'Is the pharmacy open?'},
    {it:'l\'ospedale',en:'the hospital',cat:'Travel',ipa:'/lospɛˈdaː.le/',ex:'Devo andare all\'ospedale.',exEn:'I need to go to the hospital.'},
    {it:'la polizia',en:'the police',cat:'Travel',ipa:'/la poˈliː.tsja/',ex:'Devo chiamare la polizia.',exEn:'I need to call the police.'},
    {it:'il vigile del fuoco',en:'firefighter',cat:'Travel',ipa:'/il ˈviː.dʒi.le del ˈfwɔː.ko/',ex:'I vigili del fuoco sono arrivati.',exEn:'The firefighters have arrived.'},
    {it:'il nord',en:'north',cat:'Travel',ipa:'/il nɔrd/',ex:'Milano è a nord.',exEn:'Milan is to the north.'},
    {it:'il sud',en:'south',cat:'Travel',ipa:'/il sud/',ex:'Napoli è a sud.',exEn:'Naples is to the south.'},
    {it:'l\'est',en:'east',cat:'Travel',ipa:'/lɛst/',ex:'Venezia è a est.',exEn:'Venice is to the east.'},
    {it:'l\'ovest',en:'west',cat:'Travel',ipa:'/ˈloː.vest/',ex:'Torino è a ovest.',exEn:'Turin is to the west.'},
    {it:'il centro',en:'the centre',cat:'Travel',ipa:'/il ˈtʃɛn.tro/',ex:'Abito in centro.',exEn:'I live in the centre.'},
    {it:'la periferia',en:'the suburbs / outskirts',cat:'Travel',ipa:'/la periˈfeː.rja/',ex:'Abito in periferia.',exEn:'I live in the suburbs.'},
    {it:'il quartiere',en:'the neighbourhood',cat:'Travel',ipa:'/il kwarˈtjeː.re/',ex:'È un bel quartiere.',exEn:'It\'s a nice neighbourhood.'},
    {it:'la frontiera',en:'the border / frontier',cat:'Travel',ipa:'/la fronˈtjeː.ra/',ex:'Siamo vicini alla frontiera.',exEn:'We are near the border.'},
    {it:'il volo',en:'the flight',cat:'Travel',ipa:'/il ˈvoː.lo/',ex:'Il volo è cancellato.',exEn:'The flight is cancelled.'},
    {it:'il gate',en:'the gate',cat:'Travel',ipa:'/il ɡeɪt/',ex:'Qual è il gate?',exEn:'What is the gate?'},
    {it:'l\'imbarco',en:'boarding',cat:'Travel',ipa:'/limˈbar.ko/',ex:'L\'imbarco inizia tra poco.',exEn:'Boarding begins shortly.'},
    {it:'il noleggio',en:'rental / hire',cat:'Travel',ipa:'/il noˈlɛdʒ.dʒo/',ex:'Il noleggio auto è vicino.',exEn:'The car hire is nearby.'},
    {it:'il parcheggio',en:'the car park / parking',cat:'Travel',ipa:'/il parˈkɛdʒ.dʒo/',ex:'C\'è un parcheggio qui?',exEn:'Is there parking here?'},
    {it:'la benzina',en:'petrol / gasoline',cat:'Travel',ipa:'/la benˈdziː.na/',ex:'Devo fare benzina.',exEn:'I need to get petrol.'},
    {it:'il distributore',en:'petrol station',cat:'Travel',ipa:'/il distribuˈtoː.re/',ex:'Il distributore è aperto.',exEn:'The petrol station is open.'},
    {it:'la dogana',en:'customs',cat:'Travel',ipa:'/la doˈɡaː.na/',ex:'Bisogna passare la dogana.',exEn:'You need to go through customs.'},
    {it:'il visto',en:'the visa',cat:'Travel',ipa:'/il ˈvis.to/',ex:'Ho bisogno del visto.',exEn:'I need a visa.'},
    {it:'assicurazione',en:'insurance',cat:'Travel',ipa:'/assikuratˈtsjoː.ne/',ex:'Ho l\'assicurazione di viaggio.',exEn:'I have travel insurance.'},
    {it:'la guida',en:'the guide / guidebook',cat:'Travel',ipa:'/la ˈɡwiː.da/',ex:'Ho comprato una guida di Roma.',exEn:'I bought a Rome guidebook.'},
    {it:'il souvenir',en:'souvenir',cat:'Travel',ipa:'/il suveˈniːr/',ex:'Compro un souvenir per la famiglia.',exEn:'I\'m buying a souvenir for my family.'},
  ]
};

window.PACK_travel.words.push(
  {it:'il treno ad alta velocità',en:'high-speed train',cat:'Travel',ipa:'/il ˈtrɛː.no ad ˈal.ta velotʃiˈta/',ex:'Il Frecciarossa è un treno ad alta velocità.',exEn:'The Frecciarossa is a high-speed train.'},
  {it:'la coincidenza',en:'connection / coincidence',cat:'Travel',ipa:'/la kointʃiˈdɛn.tsa/',ex:'Ho perso la coincidenza.',exEn:'I missed my connection.'},
  {it:'la sala d\'aspetto',en:'waiting room',cat:'Travel',ipa:'/la ˈsaː.la dasˈpɛt.to/',ex:'Aspetto nella sala d\'aspetto.',exEn:'I wait in the waiting room.'},
  {it:'il capolinea',en:'terminus / end of the line',cat:'Travel',ipa:'/il kapoˈliː.nea/',ex:'Il capolinea è al centro.',exEn:'The terminus is in the centre.'},
  {it:'la fermata',en:'stop (bus/tram)',cat:'Travel',ipa:'/la ferˈmaː.ta/',ex:'Scendo alla prossima fermata.',exEn:'I get off at the next stop.'},
  {it:'il tram',en:'tram',cat:'Travel',ipa:'/il tram/',ex:'Prendo il tram.',exEn:'I take the tram.'},
  {it:'il motorino',en:'scooter / moped',cat:'Travel',ipa:'/il motoˈriː.no/',ex:'Vado in motorino.',exEn:'I go by scooter.'},
  {it:'il monolocale',en:'studio flat',cat:'Travel',ipa:'/il monoloˈkaː.le/',ex:'Ho affittato un monolocale.',exEn:'I rented a studio flat.'},
  {it:'l\'ostello',en:'hostel',cat:'Travel',ipa:'/losˈtɛl.lo/',ex:'Dormo in ostello.',exEn:'I\'m staying in a hostel.'},
  {it:'il bed and breakfast',en:'bed and breakfast',cat:'Travel',ipa:'/il bɛd and ˈbrɛk.fəst/',ex:'Ho prenotato un B&B.',exEn:'I booked a B&B.'},
  {it:'la pensione',en:'guesthouse / pension',cat:'Travel',ipa:'/la penˈsjoː.ne/',ex:'Una pensione familiare.',exEn:'A family guesthouse.'},
  {it:'l\'agriturismo',en:'farm stay',cat:'Travel',ipa:'/laɡrituˈriz.mo/',ex:'Un agriturismo in Toscana.',exEn:'A farm stay in Tuscany.'},
  {it:'l\'escursione',en:'excursion / day trip',cat:'Travel',ipa:'/leskurˈsjoː.ne/',ex:'Una escursione in montagna.',exEn:'A mountain excursion.'},
  {it:'la guida turistica',en:'tour guide',cat:'Travel',ipa:'/la ˈɡwiː.da tuˈris.ti.ka/',ex:'La guida turistica parla italiano.',exEn:'The tour guide speaks Italian.'},
  {it:'il giro turistico',en:'sightseeing tour',cat:'Travel',ipa:'/il ˈdʒiː.ro tuˈris.ti.ko/',ex:'Facciamo un giro turistico.',exEn:'Let\'s go on a sightseeing tour.'},
  {it:'il monumento',en:'monument',cat:'Travel',ipa:'/il monuˈmɛn.to/',ex:'Un monumento storico.',exEn:'A historic monument.'},
  {it:'il sito archeologico',en:'archaeological site',cat:'Travel',ipa:'/il ˈsiː.to arkeolˈoː.dʒi.ko/',ex:'Un sito archeologico romano.',exEn:'A Roman archaeological site.'},
  {it:'il centro storico',en:'historic centre',cat:'Travel',ipa:'/il ˈtʃɛn.tro ˈstoː.ri.ko/',ex:'Il centro storico di Firenze.',exEn:'Florence\'s historic centre.'},
  {it:'la cartolina',en:'postcard',cat:'Travel',ipa:'/la kartoˈliː.na/',ex:'Mando una cartolina.',exEn:'I send a postcard.'},
  {it:'il francobollo',en:'stamp',cat:'Travel',ipa:'/il fraŋkoˈbɔl.lo/',ex:'Ho bisogno di un francobollo.',exEn:'I need a stamp.'},
  {it:'il cambiavalute',en:'currency exchange',cat:'Travel',ipa:'/il kambjaˈvaː.lu.te/',ex:'Dov\'è il cambiavalute?',exEn:'Where is the currency exchange?'},
  {it:'il portamonete',en:'purse / coin purse',cat:'Travel',ipa:'/il portamoˈneː.te/',ex:'Ho il portamonete.',exEn:'I have my purse.'},
  {it:'l\'itinerario',en:'itinerary',cat:'Travel',ipa:'/litiˈneː.raː.rjo/',ex:'L\'itinerario del viaggio.',exEn:'The travel itinerary.'},
  {it:'la meta',en:'destination',cat:'Travel',ipa:'/la ˈmeː.ta/',ex:'La meta del viaggio è Roma.',exEn:'The destination of the trip is Rome.'},
  {it:'il viaggio organizzato',en:'package tour',cat:'Travel',ipa:'/il ˈvjadʒ.dʒo organiˈddzaː.to/',ex:'Un viaggio organizzato in Sicilia.',exEn:'A package tour to Sicily.'},
  {it:'l\'agenzia di viaggi',en:'travel agency',cat:'Travel',ipa:'/ladʒenˈdziː.a di ˈvjadʒ.dʒi/',ex:'Vado all\'agenzia di viaggi.',exEn:'I go to the travel agency.'},
  {it:'il tour operator',en:'tour operator',cat:'Travel',ipa:'/il ˈtʊər ˈɒp.ər.eɪ.tər/',ex:'Il tour operator organizza tutto.',exEn:'The tour operator organises everything.'},
  {it:'il jet lag',en:'jet lag',cat:'Travel',ipa:'/il dʒɛt læɡ/',ex:'Ho il jet lag.',exEn:'I have jet lag.'},
  {it:'il fuso orario',en:'time zone',cat:'Travel',ipa:'/il ˈfuː.zo oˈraː.rjo/',ex:'Il fuso orario è diverso.',exEn:'The time zone is different.'},
  {it:'la dogana',en:'customs',cat:'Travel',ipa:'/la doˈɡaː.na/',ex:'Bisogna passare la dogana.',exEn:'You need to go through customs.'}
);
