window.PACK_numbers = {
  id:'numbers', name:'Numbers & Time', emoji:'🔢',
  words:[
    {it:'uno',en:'one',cat:'Number',ipa:'/ˈuː.no/',ex:'Ho un fratello.',exEn:'I have one brother.'},
    {it:'due',en:'two',cat:'Number',ipa:'/ˈduː.e/',ex:'Due caffè, per favore.',exEn:'Two coffees, please.'},
    {it:'tre',en:'three',cat:'Number',ipa:'/ˈtrɛ/',ex:'Ho tre sorelle.',exEn:'I have three sisters.'},
    {it:'quattro',en:'four',cat:'Number',ipa:'/ˈkwat.tro/',ex:'Ci sono quattro stagioni.',exEn:'There are four seasons.'},
    {it:'cinque',en:'five',cat:'Number',ipa:'/ˈtʃiŋ.kwe/',ex:'Costa cinque euro.',exEn:'It costs five euros.'},
    {it:'sei',en:'six',cat:'Number',ipa:'/sɛi/',ex:'Il negozio apre alle sei.',exEn:'The shop opens at six.'},
    {it:'sette',en:'seven',cat:'Number',ipa:'/ˈsɛt.te/',ex:'Una settimana ha sette giorni.',exEn:'A week has seven days.'},
    {it:'otto',en:'eight',cat:'Number',ipa:'/ˈɔt.to/',ex:'Sono le otto di mattina.',exEn:'It\'s eight in the morning.'},
    {it:'nove',en:'nine',cat:'Number',ipa:'/ˈnɔː.ve/',ex:'Il negozio chiude alle nove.',exEn:'The shop closes at nine.'},
    {it:'dieci',en:'ten',cat:'Number',ipa:'/ˈdjɛː.tʃi/',ex:'Sono le dieci di mattina.',exEn:'It\'s ten in the morning.'},
    {it:'undici',en:'eleven',cat:'Number',ipa:'/ˈun.di.tʃi/',ex:'Arriverò alle undici.',exEn:'I\'ll arrive at eleven.'},
    {it:'dodici',en:'twelve',cat:'Number',ipa:'/ˈdɔː.di.tʃi/',ex:'Sono le dodici, è mezzogiorno.',exEn:'It\'s twelve, it\'s noon.'},
    {it:'venti',en:'twenty',cat:'Number',ipa:'/ˈvɛn.ti/',ex:'Ho vent\'anni.',exEn:'I am twenty years old.'},
    {it:'trenta',en:'thirty',cat:'Number',ipa:'/ˈtrɛn.ta/',ex:'Sono le trenta.',exEn:'It\'s thirty past.'},
    {it:'quaranta',en:'forty',cat:'Number',ipa:'/kwaˈran.ta/',ex:'Ha quarant\'anni.',exEn:'He is forty years old.'},
    {it:'cinquanta',en:'fifty',cat:'Number',ipa:'/tʃiŋˈkwan.ta/',ex:'Costa cinquanta euro.',exEn:'It costs fifty euros.'},
    {it:'cento',en:'one hundred',cat:'Number',ipa:'/ˈtʃɛn.to/',ex:'Cento persone erano presenti.',exEn:'A hundred people were present.'},
    {it:'mille',en:'one thousand',cat:'Number',ipa:'/ˈmil.le/',ex:'Costa mille euro.',exEn:'It costs a thousand euros.'},
    {it:'primo',en:'first',cat:'Number',ipa:'/ˈpriː.mo/',ex:'Il primo piano.',exEn:'The first floor.'},
    {it:'secondo',en:'second',cat:'Number',ipa:'/seˈkɔn.do/',ex:'Secondo me è bello.',exEn:'In my opinion it\'s beautiful.'},
    {it:'terzo',en:'third',cat:'Number',ipa:'/ˈtɛr.tso/',ex:'Abito al terzo piano.',exEn:'I live on the third floor.'},
    {it:'ultimo',en:'last',cat:'Number',ipa:'/ˈul.ti.mo/',ex:'È l\'ultimo treno.',exEn:'It\'s the last train.'},
    {it:'oggi',en:'today',cat:'Time',ipa:'/ˈɔd.dʒi/',ex:'Oggi è lunedì.',exEn:'Today is Monday.'},
    {it:'domani',en:'tomorrow',cat:'Time',ipa:'/doˈmaː.ni/',ex:'A domani!',exEn:'See you tomorrow!'},
    {it:'ieri',en:'yesterday',cat:'Time',ipa:'/ˈjɛː.ri/',ex:'Ieri ho mangiato la pizza.',exEn:'Yesterday I ate pizza.'},
    {it:'adesso',en:'now',cat:'Time',ipa:'/aˈdɛs.so/',ex:'Vieni adesso, per favore.',exEn:'Come now, please.'},
    {it:'presto',en:'soon / early',cat:'Time',ipa:'/ˈprɛs.to/',ex:'A presto!',exEn:'See you soon!'},
    {it:'tardi',en:'late',cat:'Time',ipa:'/ˈtar.di/',ex:'Scusa, sono in ritardo.',exEn:'Sorry, I\'m late.'},
    {it:'mattina',en:'morning',cat:'Time',ipa:'/matˈtiː.na/',ex:'La mattina bevo il caffè.',exEn:'In the morning I drink coffee.'},
    {it:'sera',en:'evening',cat:'Time',ipa:'/ˈseː.ra/',ex:'Ci vediamo di sera.',exEn:'We\'ll see each other in the evening.'},
    {it:'notte',en:'night',cat:'Time',ipa:'/ˈnɔt.te/',ex:'Buona notte!',exEn:'Good night!'},
    {it:'pomeriggio',en:'afternoon',cat:'Time',ipa:'/pomeˈrid.dʒo/',ex:'Nel pomeriggio vado al bar.',exEn:'In the afternoon I go to the bar.'},
    {it:'mezzogiorno',en:'midday / noon',cat:'Time',ipa:'/ˌmɛdzoˈdʒor.no/',ex:'Pranzo a mezzogiorno.',exEn:'I have lunch at noon.'},
    {it:'mezzanotte',en:'midnight',cat:'Time',ipa:'/ˌmɛdzaˈnɔt.te/',ex:'Sono tornato a mezzanotte.',exEn:'I came back at midnight.'},
    {it:'lunedì',en:'Monday',cat:'Time',ipa:'/luneˈdiː/',ex:'Lunedì vado in ufficio.',exEn:'On Monday I go to the office.'},
    {it:'martedì',en:'Tuesday',cat:'Time',ipa:'/marteˈdiː/',ex:'Ci vediamo martedì.',exEn:'We\'ll see each other on Tuesday.'},
    {it:'mercoledì',en:'Wednesday',cat:'Time',ipa:'/merkoˈleː.di/',ex:'Il mercato è il mercoledì.',exEn:'The market is on Wednesday.'},
    {it:'giovedì',en:'Thursday',cat:'Time',ipa:'/dʒoˈveː.di/',ex:'Giovedì sera andiamo al cinema.',exEn:'Thursday evening we\'re going to the cinema.'},
    {it:'venerdì',en:'Friday',cat:'Time',ipa:'/venerˈdiː/',ex:'Il venerdì esci?',exEn:'Do you go out on Fridays?'},
    {it:'sabato',en:'Saturday',cat:'Time',ipa:'/ˈsaː.ba.to/',ex:'Il sabato faccio sport.',exEn:'On Saturdays I do sport.'},
    {it:'domenica',en:'Sunday',cat:'Time',ipa:'/doˈmɛː.ni.ka/',ex:'La domenica riposo.',exEn:'On Sundays I rest.'},
    {it:'gennaio',en:'January',cat:'Time',ipa:'/dʒenˈnaː.jo/',ex:'Fa freddo in gennaio.',exEn:'It\'s cold in January.'},
    {it:'febbraio',en:'February',cat:'Time',ipa:'/febˈbraː.jo/',ex:'San Valentino è in febbraio.',exEn:'Valentine\'s Day is in February.'},
    {it:'marzo',en:'March',cat:'Time',ipa:'/ˈmar.tso/',ex:'In marzo comincia la primavera.',exEn:'In March spring begins.'},
    {it:'aprile',en:'April',cat:'Time',ipa:'/aˈpriː.le/',ex:'Aprile è un bel mese.',exEn:'April is a beautiful month.'},
    {it:'maggio',en:'May',cat:'Time',ipa:'/ˈmad.dʒo/',ex:'Maggio è il mese dei fiori.',exEn:'May is the month of flowers.'},
    {it:'giugno',en:'June',cat:'Time',ipa:'/ˈdʒuɲ.ɲo/',ex:'Le vacanze iniziano in giugno.',exEn:'Holidays begin in June.'},
    {it:'luglio',en:'July',cat:'Time',ipa:'/ˈluʎ.ʎo/',ex:'Luglio è il mese più caldo.',exEn:'July is the hottest month.'},
    {it:'agosto',en:'August',cat:'Time',ipa:'/aˈɡos.to/',ex:'In agosto siamo chiusi.',exEn:'In August we are closed.'},
    {it:'settembre',en:'September',cat:'Time',ipa:'/setˈtɛm.bre/',ex:'Le scuole riaprono in settembre.',exEn:'Schools reopen in September.'},
    {it:'ottobre',en:'October',cat:'Time',ipa:'/otˈtoː.bre/',ex:'I colori dell\'ottobre.',exEn:'The colours of October.'},
    {it:'novembre',en:'November',cat:'Time',ipa:'/noˈvɛm.bre/',ex:'In novembre fa già freddo.',exEn:'In November it\'s already cold.'},
    {it:'dicembre',en:'December',cat:'Time',ipa:'/diˈtʃɛm.bre/',ex:'Natale è in dicembre.',exEn:'Christmas is in December.'},
    {it:'la settimana',en:'the week',cat:'Time',ipa:'/la settiˈmaː.na/',ex:'La settimana prossima.',exEn:'Next week.'},
    {it:'il mese',en:'the month',cat:'Time',ipa:'/il ˈmeː.ze/',ex:'Il mese scorso ero a Roma.',exEn:'Last month I was in Rome.'},
    {it:'l\'anno',en:'the year',cat:'Time',ipa:'/ˈlan.no/',ex:'Quest\'anno vado in Italia.',exEn:'This year I\'m going to Italy.'},
    {it:'il minuto',en:'the minute',cat:'Time',ipa:'/il miˈnuː.to/',ex:'Aspetta cinque minuti.',exEn:'Wait five minutes.'},
    {it:'l\'ora',en:'the hour / time',cat:'Time',ipa:'/ˈloː.ra/',ex:'Che ora è?',exEn:'What time is it?'},
    {it:'il secondo',en:'the second',cat:'Time',ipa:'/il seˈkɔn.do/',ex:'Un secondo, per favore.',exEn:'One second, please.'},
    {it:'il futuro',en:'the future',cat:'Time',ipa:'/il fuˈtuː.ro/',ex:'Pensiamo al futuro.',exEn:'Let\'s think about the future.'},
    {it:'il passato',en:'the past',cat:'Time',ipa:'/il pasˈsaː.to/',ex:'Il passato è passato.',exEn:'The past is the past.'},
    {it:'il presente',en:'the present',cat:'Time',ipa:'/il preˈzɛn.te/',ex:'Vivi nel presente.',exEn:'Live in the present.'},
    {it:'scorso',en:'last (past)',cat:'Time',ipa:'/ˈskor.so/',ex:'L\'anno scorso.',exEn:'Last year.'},
    {it:'prossimo',en:'next',cat:'Time',ipa:'/ˈprɔs.si.mo/',ex:'La prossima settimana.',exEn:'Next week.'},
    {it:'spesso',en:'often',cat:'Time',ipa:'/ˈspɛs.so/',ex:'Vengo qui spesso.',exEn:'I come here often.'},
    {it:'raramente',en:'rarely',cat:'Time',ipa:'/raraˈmɛn.te/',ex:'Raramente mangio carne.',exEn:'I rarely eat meat.'},
    {it:'sempre',en:'always',cat:'Time',ipa:'/ˈsɛm.pre/',ex:'Arrivo sempre in orario.',exEn:'I always arrive on time.'},
    {it:'mai',en:'never',cat:'Time',ipa:'/maɪ/',ex:'Non sono mai stato a Venezia.',exEn:'I\'ve never been to Venice.'},
    {it:'di solito',en:'usually',cat:'Time',ipa:'/di ˈsoː.li.to/',ex:'Di solito mangio alle otto.',exEn:'I usually eat at eight.'},
    {it:'qualche volta',en:'sometimes',cat:'Time',ipa:'/ˈkwal.ke ˈvol.ta/',ex:'Qualche volta vado al cinema.',exEn:'Sometimes I go to the cinema.'},
    {it:'quanto tempo',en:'how long',cat:'Time',ipa:'/ˈkwan.to ˈtɛm.po/',ex:'Quanto tempo ci vuole?',exEn:'How long does it take?'},
    {it:'in anticipo',en:'early / ahead of time',cat:'Time',ipa:'/in anˈtiː.tʃi.po/',ex:'Sono arrivato in anticipo.',exEn:'I arrived early.'},
    {it:'in ritardo',en:'late / behind time',cat:'Time',ipa:'/in riˈtar.do/',ex:'Il treno è in ritardo.',exEn:'The train is late.'},
    {it:'in orario',en:'on time',cat:'Time',ipa:'/in oˈraː.rjo/',ex:'Il volo è arrivato in orario.',exEn:'The flight arrived on time.'},
  ]
};

window.PACK_numbers.words.push(
  {it:'tredici',en:'thirteen',cat:'Number',ipa:'/ˈtrɛː.di.tʃi/',ex:'Ho tredici anni.',exEn:'I am thirteen years old.'},
  {it:'quattordici',en:'fourteen',cat:'Number',ipa:'/kwatˈtor.di.tʃi/',ex:'Sono le quattordici.',exEn:'It is fourteen hundred.'},
  {it:'quindici',en:'fifteen',cat:'Number',ipa:'/ˈkwin.di.tʃi/',ex:'Aspetta quindici minuti.',exEn:'Wait fifteen minutes.'},
  {it:'sedici',en:'sixteen',cat:'Number',ipa:'/ˈseː.di.tʃi/',ex:'Ho sedici anni.',exEn:'I am sixteen years old.'},
  {it:'diciassette',en:'seventeen',cat:'Number',ipa:'/ditʃasˈsɛt.te/',ex:'Sono le diciassette.',exEn:'It is seventeen hundred.'},
  {it:'diciotto',en:'eighteen',cat:'Number',ipa:'/ditˈʃɔt.to/',ex:'Ha diciotto anni.',exEn:'He is eighteen.'},
  {it:'diciannove',en:'nineteen',cat:'Number',ipa:'/ditʃanˈnɔː.ve/',ex:'Sono le diciannove.',exEn:'It is nineteen hundred.'},
  {it:'sessanta',en:'sixty',cat:'Number',ipa:'/sesˈsan.ta/',ex:'Ha sessant\'anni.',exEn:'She is sixty years old.'},
  {it:'settanta',en:'seventy',cat:'Number',ipa:'/setˈtan.ta/',ex:'Costa settanta euro.',exEn:'It costs seventy euros.'},
  {it:'ottanta',en:'eighty',cat:'Number',ipa:'/otˈtan.ta/',ex:'Ha ottant\'anni.',exEn:'He is eighty.'},
  {it:'novanta',en:'ninety',cat:'Number',ipa:'/noˈvan.ta/',ex:'Novanta percento.',exEn:'Ninety percent.'},
  {it:'duecento',en:'two hundred',cat:'Number',ipa:'/dweˈtʃɛn.to/',ex:'Duecento persone.',exEn:'Two hundred people.'},
  {it:'cinquecento',en:'five hundred',cat:'Number',ipa:'/tʃiŋkweˈtʃɛn.to/',ex:'Cinquecento anni fa.',exEn:'Five hundred years ago.'},
  {it:'un milione',en:'one million',cat:'Number',ipa:'/un miˈljoː.ne/',ex:'Un milione di euro.',exEn:'One million euros.'},
  {it:'mezzo',en:'half',cat:'Number',ipa:'/ˈmɛd.dzo/',ex:'Mezzo litro d\'acqua.',exEn:'Half a litre of water.'},
  {it:'un quarto',en:'a quarter',cat:'Number',ipa:'/un ˈkwar.to/',ex:'Un quarto d\'ora.',exEn:'A quarter of an hour.'},
  {it:'il doppio',en:'double',cat:'Number',ipa:'/il ˈdɔp.pjo/',ex:'Il doppio del prezzo.',exEn:'Double the price.'},
  {it:'la metà',en:'half',cat:'Number',ipa:'/la meˈta/',ex:'La metà del costo.',exEn:'Half the cost.'},
  {it:'per cento',en:'percent',cat:'Number',ipa:'/per ˈtʃɛn.to/',ex:'Il venti per cento.',exEn:'Twenty percent.'},
  {it:'pari',en:'even (number)',cat:'Number',ipa:'/ˈpaː.ri/',ex:'Un numero pari.',exEn:'An even number.'},
  {it:'dispari',en:'odd (number)',cat:'Number',ipa:'/ˈdis.pa.ri/',ex:'Un numero dispari.',exEn:'An odd number.'},
  {it:'il numero',en:'number',cat:'Number',ipa:'/il ˈnuː.me.ro/',ex:'Qual è il numero?',exEn:'What is the number?'},
  {it:'la cifra',en:'figure / digit',cat:'Number',ipa:'/la ˈtʃiː.fra/',ex:'Una cifra enorme.',exEn:'An enormous figure.'},
  {it:'calcolare',en:'to calculate',cat:'Number',ipa:'/kalkoˈlaː.re/',ex:'Calcola il totale.',exEn:'Calculate the total.'},
  {it:'il totale',en:'total',cat:'Number',ipa:'/il toˈtaː.le/',ex:'Qual è il totale?',exEn:'What is the total?'},
  {it:'la somma',en:'sum / total',cat:'Number',ipa:'/la ˈsɔm.ma/',ex:'La somma di tutti i costi.',exEn:'The sum of all the costs.'}
);
