window.PACK_greet = {
  id:'greet', name:'Greetings & Basics', emoji:'👋',
  words:[
    {it:'ciao',en:'hello / bye',cat:'Greeting',ipa:'/ˈtʃaː.o/',ex:'Ciao, come stai?',exEn:'Hello, how are you?'},
    {it:'buongiorno',en:'good morning',cat:'Greeting',ipa:'/ˌbwɔnˈdʒɔr.no/',ex:'Buongiorno! Come va?',exEn:'Good morning! How\'s it going?'},
    {it:'buonasera',en:'good evening',cat:'Greeting',ipa:'/ˌbwɔnaˈseː.ra/',ex:'Buonasera a tutti!',exEn:'Good evening, everyone!'},
    {it:'buonanotte',en:'good night',cat:'Greeting',ipa:'/ˌbwɔnaˈnɔt.te/',ex:'Buonanotte, dormi bene!',exEn:'Good night, sleep well!'},
    {it:'grazie',en:'thank you',cat:'Greeting',ipa:'/ˈɡrat.tsje/',ex:'Grazie mille!',exEn:'Thank you very much!'},
    {it:'prego',en:'you\'re welcome',cat:'Greeting',ipa:'/ˈpɾɛ.ɡo/',ex:'Grazie! — Prego!',exEn:'Thank you! — You\'re welcome!'},
    {it:'scusa',en:'excuse me / sorry',cat:'Greeting',ipa:'/ˈskuː.za/',ex:'Scusa, dov\'è il bagno?',exEn:'Excuse me, where is the bathroom?'},
    {it:'per favore',en:'please',cat:'Basics',ipa:'/per faˈvoː.re/',ex:'Un caffè, per favore.',exEn:'A coffee, please.'},
    {it:'sì',en:'yes',cat:'Basics',ipa:'/siː/',ex:'Sì, capisco.',exEn:'Yes, I understand.'},
    {it:'no',en:'no',cat:'Basics',ipa:'/nɔ/',ex:'No, grazie.',exEn:'No, thank you.'},
    {it:'arrivederci',en:'goodbye',cat:'Greeting',ipa:'/arˌriːveˈdɛr.tʃi/',ex:'Arrivederci a presto!',exEn:'Goodbye, see you soon!'},
    {it:'come stai?',en:'how are you?',cat:'Greeting',ipa:'/ˈkoː.me ˈstaː.i/',ex:'Ciao! Come stai oggi?',exEn:'Hi! How are you today?'},
    {it:'bene',en:'well / fine',cat:'Basics',ipa:'/ˈbeː.ne/',ex:'Sto bene, grazie.',exEn:'I\'m well, thank you.'},
    {it:'male',en:'badly / not well',cat:'Basics',ipa:'/ˈmaː.le/',ex:'Non sto molto bene.',exEn:'I\'m not very well.'},
    {it:'così così',en:'so-so',cat:'Basics',ipa:'/koˈziː koˈziː/',ex:'Come stai? — Così così.',exEn:'How are you? — So-so.'},
    {it:'mi chiamo',en:'my name is',cat:'Basics',ipa:'/mi ˈkjaː.mo/',ex:'Mi chiamo Marco.',exEn:'My name is Marco.'},
    {it:'come ti chiami?',en:'what\'s your name?',cat:'Basics',ipa:'/ˈkoː.me ti ˈkjaː.mi/',ex:'Come ti chiami?',exEn:'What\'s your name?'},
    {it:'piacere',en:'nice to meet you',cat:'Greeting',ipa:'/pjaˈtʃeː.re/',ex:'Piacere di conoscerti!',exEn:'Nice to meet you!'},
    {it:'di dove sei?',en:'where are you from?',cat:'Basics',ipa:'/di ˈdoː.ve ˈsɛi/',ex:'Di dove sei?',exEn:'Where are you from?'},
    {it:'sono di',en:'I am from',cat:'Basics',ipa:'/ˈsoː.no di/',ex:'Sono di Londra.',exEn:'I am from London.'},
    {it:'parli inglese?',en:'do you speak English?',cat:'Basics',ipa:'/ˈpar.li iŋˈɡleː.ze/',ex:'Parli inglese, per favore?',exEn:'Do you speak English, please?'},
    {it:'non capisco',en:'I don\'t understand',cat:'Basics',ipa:'/non kaˈpis.ko/',ex:'Scusa, non capisco.',exEn:'Sorry, I don\'t understand.'},
    {it:'puoi ripetere?',en:'can you repeat?',cat:'Basics',ipa:'/ˈpwɔi riˈpeː.te.re/',ex:'Puoi ripetere, per favore?',exEn:'Can you repeat, please?'},
    {it:'più lentamente',en:'more slowly',cat:'Basics',ipa:'/pjuː lenˈta.men.te/',ex:'Parla più lentamente, grazie.',exEn:'Speak more slowly, thank you.'},
    {it:'come si dice?',en:'how do you say?',cat:'Basics',ipa:'/ˈkoː.me si ˈdiː.tʃe/',ex:'Come si dice \'hello\' in italiano?',exEn:'How do you say \'hello\' in Italian?'},
    {it:'cosa significa?',en:'what does it mean?',cat:'Basics',ipa:'/ˈkoː.za siɡˈɲiː.fi.ka/',ex:'Cosa significa questa parola?',exEn:'What does this word mean?'},
    {it:'non lo so',en:'I don\'t know',cat:'Basics',ipa:'/non lo sɔ/',ex:'Non lo so, mi dispiace.',exEn:'I don\'t know, I\'m sorry.'},
    {it:'forse',en:'maybe / perhaps',cat:'Basics',ipa:'/ˈfor.se/',ex:'Forse domani.',exEn:'Maybe tomorrow.'},
    {it:'certo',en:'certainly / of course',cat:'Basics',ipa:'/ˈtʃɛr.to/',ex:'Certo, con piacere!',exEn:'Of course, with pleasure!'},
    {it:'davvero?',en:'really?',cat:'Basics',ipa:'/davˈvɛː.ro/',ex:'Davvero? Non ci credo!',exEn:'Really? I can\'t believe it!'},
    {it:'che cosa?',en:'what?',cat:'Basics',ipa:'/ke ˈkoː.za/',ex:'Che cosa hai detto?',exEn:'What did you say?'},
    {it:'chi?',en:'who?',cat:'Basics',ipa:'/kiː/',ex:'Chi è quella persona?',exEn:'Who is that person?'},
    {it:'quando?',en:'when?',cat:'Basics',ipa:'/ˈkwan.do/',ex:'Quando arrivi?',exEn:'When do you arrive?'},
    {it:'perché?',en:'why? / because',cat:'Basics',ipa:'/perˈkeː/',ex:'Perché studi l\'italiano?',exEn:'Why are you studying Italian?'},
    {it:'come?',en:'how?',cat:'Basics',ipa:'/ˈkoː.me/',ex:'Come funziona?',exEn:'How does it work?'},
    {it:'quanto?',en:'how much?',cat:'Basics',ipa:'/ˈkwan.to/',ex:'Quanto costa?',exEn:'How much does it cost?'},
    {it:'quanti?',en:'how many?',cat:'Basics',ipa:'/ˈkwan.ti/',ex:'Quanti anni hai?',exEn:'How old are you?'},
    {it:'aiuto!',en:'help!',cat:'Basics',ipa:'/aˈjuː.to/',ex:'Aiuto! Ho perso il portafoglio.',exEn:'Help! I\'ve lost my wallet.'},
    {it:'attenzione!',en:'attention! / watch out!',cat:'Basics',ipa:'/attenˈtsjoː.ne/',ex:'Attenzione! Il pavimento è bagnato.',exEn:'Watch out! The floor is wet.'},
    {it:'aspetta',en:'wait',cat:'Basics',ipa:'/aˈspet.ta/',ex:'Aspetta un momento!',exEn:'Wait a moment!'},
    {it:'subito',en:'immediately / right away',cat:'Basics',ipa:'/ˈsuː.bi.to/',ex:'Arrivo subito!',exEn:'I\'ll be right there!'},
    {it:'ancora',en:'still / again / yet',cat:'Basics',ipa:'/aŋˈkoː.ra/',ex:'Ancora una volta, per favore.',exEn:'Once more, please.'},
    {it:'già',en:'already',cat:'Basics',ipa:'/dʒaː/',ex:'Ho già mangiato.',exEn:'I\'ve already eaten.'},
    {it:'anche',en:'also / too',cat:'Basics',ipa:'/ˈaŋ.ke/',ex:'Anch\'io parlo italiano.',exEn:'I also speak Italian.'},
    {it:'però',en:'but / however',cat:'Basics',ipa:'/peˈrɔ/',ex:'Mi piace, però è caro.',exEn:'I like it, but it\'s expensive.'},
    {it:'allora',en:'so / then / well',cat:'Basics',ipa:'/alˈloː.ra/',ex:'Allora, andiamo!',exEn:'So, let\'s go!'},
    {it:'qui',en:'here',cat:'Basics',ipa:'/kwi/',ex:'Sono qui.',exEn:'I am here.'},
    {it:'là',en:'there',cat:'Basics',ipa:'/laː/',ex:'È là, sul tavolo.',exEn:'It\'s there, on the table.'},
    {it:'tutto',en:'everything / all',cat:'Basics',ipa:'/ˈtut.to/',ex:'Tutto bene!',exEn:'All good!'},
    {it:'niente',en:'nothing',cat:'Basics',ipa:'/ˈnjɛn.te/',ex:'Non c\'è niente da fare.',exEn:'There\'s nothing to do.'},
  ]
};

// ── expansion ──
window.PACK_greet.words.push(
  {it:'qualcuno',en:'someone',cat:'Basics',ipa:'/kwalˈkuː.no/',ex:'C\'è qualcuno?',exEn:'Is anyone there?'},
  {it:'nessuno',en:'no one / nobody',cat:'Basics',ipa:'/nesˈsuː.no/',ex:'Non c\'è nessuno.',exEn:'There\'s nobody here.'},
  {it:'qualcosa',en:'something',cat:'Basics',ipa:'/kwalˈkoː.za/',ex:'Vuoi qualcosa da bere?',exEn:'Would you like something to drink?'},
  {it:'molto',en:'very / a lot',cat:'Basics',ipa:'/ˈmɔl.to/',ex:'Grazie molto!',exEn:'Thank you very much!'},
  {it:'poco',en:'a little / few',cat:'Basics',ipa:'/ˈpoː.ko/',ex:'Un poco d\'acqua, grazie.',exEn:'A little water, please.'},
  {it:'troppo',en:'too much',cat:'Basics',ipa:'/ˈtrɔp.po/',ex:'È troppo caldo.',exEn:'It\'s too hot.'},
  {it:'abbastanza',en:'enough',cat:'Basics',ipa:'/abbasˈtan.tsa/',ex:'Ho mangiato abbastanza.',exEn:'I\'ve eaten enough.'},
  {it:'insieme',en:'together',cat:'Basics',ipa:'/inˈsjeː.me/',ex:'Usciamo insieme!',exEn:'Let\'s go out together!'},
  {it:'soltanto',en:'only / just',cat:'Basics',ipa:'/solˈtan.to/',ex:'Soltanto un momento.',exEn:'Just a moment.'},
  {it:'veramente',en:'really / truly',cat:'Basics',ipa:'/veraˈmɛn.te/',ex:'Veramente bellissimo!',exEn:'Truly beautiful!'},
  {it:'comunque',en:'anyway / however',cat:'Basics',ipa:'/koˈmuŋ.kwe/',ex:'Comunque, grazie.',exEn:'Anyway, thank you.'},
  {it:'finalmente',en:'finally / at last',cat:'Basics',ipa:'/finalˈmɛn.te/',ex:'Finalmente sei qui!',exEn:'You\'re finally here!'},
  {it:'purtroppo',en:'unfortunately',cat:'Basics',ipa:'/purˈtrɔp.po/',ex:'Purtroppo non posso venire.',exEn:'Unfortunately I can\'t come.'},
  {it:'per fortuna',en:'fortunately / luckily',cat:'Basics',ipa:'/per forˈtuː.na/',ex:'Per fortuna stai bene!',exEn:'Fortunately you\'re OK!'},
  {it:'di niente',en:'don\'t mention it',cat:'Greeting',ipa:'/di ˈnjɛn.te/',ex:'Grazie! — Di niente!',exEn:'Thank you! — Don\'t mention it!'},
  {it:'mi dispiace',en:'I\'m sorry',cat:'Greeting',ipa:'/mi disˈpjaː.tʃe/',ex:'Mi dispiace molto.',exEn:'I\'m very sorry.'},
  {it:'in bocca al lupo',en:'good luck (lit: in the wolf\'s mouth)',cat:'Greeting',ipa:'/in ˈbɔk.ka al ˈluː.po/',ex:'In bocca al lupo per l\'esame!',exEn:'Good luck with the exam!'},
  {it:'crepi',en:'thanks (response to in bocca al lupo)',cat:'Greeting',ipa:'/ˈkrɛː.pi/',ex:'In bocca al lupo! — Crepi!',exEn:'Good luck! — Thanks!'},
  {it:'a presto',en:'see you soon',cat:'Greeting',ipa:'/a ˈprɛs.to/',ex:'Ciao, a presto!',exEn:'Bye, see you soon!'},
  {it:'a dopo',en:'see you later',cat:'Greeting',ipa:'/a ˈdoː.po/',ex:'A dopo!',exEn:'See you later!'},
  {it:'a domani',en:'see you tomorrow',cat:'Greeting',ipa:'/a doˈmaː.ni/',ex:'A domani!',exEn:'See you tomorrow!'},
  {it:'benvenuto',en:'welcome',cat:'Greeting',ipa:'/benveˈnuː.to/',ex:'Benvenuto in Italia!',exEn:'Welcome to Italy!'},
  {it:'salve',en:'hello (formal)',cat:'Greeting',ipa:'/ˈsal.ve/',ex:'Salve, come sta?',exEn:'Hello, how are you? (formal)'},
  {it:'buon pomeriggio',en:'good afternoon',cat:'Greeting',ipa:'/bwɔn pomeˈridʒ.dʒo/',ex:'Buon pomeriggio!',exEn:'Good afternoon!'},
  {it:'con permesso',en:'excuse me (to pass)',cat:'Greeting',ipa:'/kon perˈmɛs.so/',ex:'Con permesso, devo passare.',exEn:'Excuse me, I need to pass.'},
  {it:'figurati',en:'don\'t worry about it',cat:'Greeting',ipa:'/fiˈɡuː.ra.ti/',ex:'Grazie mille! — Figurati!',exEn:'Thanks so much! — Don\'t worry about it!'},
  {it:'ma va\'!',en:'no way! / get out of here!',cat:'Basics',ipa:'/ma ˈvaː/',ex:'Ho vinto! — Ma va\'!',exEn:'I won! — No way!'},
  {it:'meno male',en:'thank goodness',cat:'Basics',ipa:'/ˈmeː.no ˈmaː.le/',ex:'Meno male che sei arrivato!',exEn:'Thank goodness you arrived!'},
  {it:'magari',en:'if only / maybe / I wish',cat:'Basics',ipa:'/maˈɡaː.ri/',ex:'Magari potessi venire.',exEn:'If only I could come.'},
  {it:'dai',en:'come on!',cat:'Basics',ipa:'/daɪ/',ex:'Dai, andiamo!',exEn:'Come on, let\'s go!'},
  {it:'ecco',en:'here is / there you go',cat:'Basics',ipa:'/ˈɛk.ko/',ex:'Ecco il tuo caffè.',exEn:'Here is your coffee.'},
  {it:'eh',en:'huh / well / right',cat:'Basics',ipa:'/ɛ/',ex:'Eh, che vuoi fare?',exEn:'Well, what can you do?'},
  {it:'boh',en:'I don\'t know (shrug)',cat:'Basics',ipa:'/bɔ/',ex:'Boh, non lo so.',exEn:'Dunno, I don\'t know.'},
  {it:'mah',en:'hmm / I\'m not sure',cat:'Basics',ipa:'/ma/',ex:'Mah, vedremo.',exEn:'Hmm, we\'ll see.'},
  {it:'uffa',en:'ugh / how annoying',cat:'Basics',ipa:'/ˈuf.fa/',ex:'Uffa, piove ancora!',exEn:'Ugh, it\'s raining again!'},
  {it:'peccato',en:'what a shame / pity',cat:'Basics',ipa:'/pekˈkaː.to/',ex:'Peccato che non puoi venire.',exEn:'What a shame you can\'t come.'},
  {it:'che bello',en:'how lovely / great',cat:'Basics',ipa:'/ke ˈbɛl.lo/',ex:'Che bello! Grazie!',exEn:'How lovely! Thank you!'},
  {it:'accidenti',en:'damn / wow',cat:'Basics',ipa:'/attʃiˈdɛn.ti/',ex:'Accidenti, che veloce!',exEn:'Wow, how fast!'},
  {it:'che peccato',en:'what a pity',cat:'Basics',ipa:'/ke pekˈkaː.to/',ex:'Che peccato non esserci.',exEn:'What a pity not to be there.'},
  {it:'evviva',en:'hurray / long live',cat:'Basics',ipa:'/evˈviː.va/',ex:'Evviva! Abbiamo vinto!',exEn:'Hurray! We won!'},
  {it:'bravo',en:'well done / bravo',cat:'Basics',ipa:'/ˈbraː.vo/',ex:'Bravo! Ottimo lavoro!',exEn:'Well done! Excellent work!'},
  {it:'mannaggia',en:'damn it',cat:'Basics',ipa:'/manˈnadʒ.dʒa/',ex:'Mannaggia! Ho dimenticato!',exEn:'Damn it! I forgot!'},
  {it:'macché',en:'no way / of course not',cat:'Basics',ipa:'/makˈke/',ex:'Macché! Non ci credo!',exEn:'No way! I don\'t believe it!'},
  {it:'insomma',en:'in short / well / so-so',cat:'Basics',ipa:'/inˈsom.ma/',ex:'Insomma, non è male.',exEn:'Well, it\'s not bad.'},
  {it:'appunto',en:'exactly / precisely',cat:'Basics',ipa:'/apˈpun.to/',ex:'Appunto, è quello che intendo.',exEn:'Exactly, that\'s what I mean.'},
  {it:'dunque',en:'so / therefore',cat:'Basics',ipa:'/ˈduŋ.kwe/',ex:'Dunque, cosa facciamo?',exEn:'So, what shall we do?'},
  {it:'mica',en:'not at all (emphatic)',cat:'Basics',ipa:'/ˈmiː.ka/',ex:'Non è mica difficile.',exEn:'It\'s not difficult at all.'},
  {it:'a tal punto',en:'to such an extent',cat:'Basics',ipa:'/a tal ˈpun.to/',ex:'Non immaginavo fosse a tal punto serio.',exEn:'I didn\'t realise it was that serious.'},
  {it:'comunque sia',en:'be that as it may',cat:'Basics',ipa:'/koˈmuŋ.kwe ˈsiː.a/',ex:'Comunque sia, grazie.',exEn:'Be that as it may, thank you.'},
  {it:'neanche',en:'not even',cat:'Basics',ipa:'/neˈaŋ.ke/',ex:'Non l\'ho neanche visto.',exEn:'I didn\'t even see it.'}
);
