window.PACK_animals = {
  id:'animals', name:'Animals', emoji:'🐾',
  words:[
    {it:'il cane',en:'the dog',cat:'Animal',ipa:'/il ˈkaː.ne/',ex:'Il cane è il migliore amico dell\'uomo.',exEn:'The dog is man\'s best friend.'},
    {it:'il gatto',en:'the cat',cat:'Animal',ipa:'/il ˈɡat.to/',ex:'Il gatto dorme sul divano.',exEn:'The cat sleeps on the sofa.'},
    {it:'il cavallo',en:'the horse',cat:'Animal',ipa:'/il kaˈval.lo/',ex:'Il cavallo è un animale nobile.',exEn:'The horse is a noble animal.'},
    {it:'la mucca',en:'the cow',cat:'Animal',ipa:'/la ˈmuk.ka/',ex:'La mucca dà il latte.',exEn:'The cow gives milk.'},
    {it:'il toro',en:'the bull',cat:'Animal',ipa:'/il ˈtoː.ro/',ex:'Il toro è aggressivo.',exEn:'The bull is aggressive.'},
    {it:'il maiale',en:'the pig',cat:'Animal',ipa:'/il maˈjaː.le/',ex:'Il maiale oink.',exEn:'The pig oinks.'},
    {it:'la pecora',en:'the sheep',cat:'Animal',ipa:'/la ˈpɛː.ko.ra/',ex:'Le pecore pascolano.',exEn:'The sheep graze.'},
    {it:'la capra',en:'the goat',cat:'Animal',ipa:'/la ˈkaː.pra/',ex:'La capra mangia tutto.',exEn:'The goat eats everything.'},
    {it:'il pollo',en:'the chicken',cat:'Animal',ipa:'/il ˈpɔl.lo/',ex:'I polli nel cortile.',exEn:'The chickens in the yard.'},
    {it:'il coniglio',en:'the rabbit',cat:'Animal',ipa:'/il koˈniʎ.ʎo/',ex:'Il coniglio è bianco.',exEn:'The rabbit is white.'},
    {it:'il leone',en:'the lion',cat:'Animal',ipa:'/il leˈoː.ne/',ex:'Il leone è il re degli animali.',exEn:'The lion is the king of animals.'},
    {it:'la tigre',en:'the tiger',cat:'Animal',ipa:'/la ˈtiː.ɡre/',ex:'La tigre è in pericolo.',exEn:'The tiger is endangered.'},
    {it:'l\'elefante',en:'the elephant',cat:'Animal',ipa:'/leˈle.fan.te/',ex:'L\'elefante ha una buona memoria.',exEn:'The elephant has a good memory.'},
    {it:'la giraffa',en:'the giraffe',cat:'Animal',ipa:'/la dʒiˈraf.fa/',ex:'La giraffa ha il collo lungo.',exEn:'The giraffe has a long neck.'},
    {it:'il gorilla',en:'the gorilla',cat:'Animal',ipa:'/il ɡoˈril.la/',ex:'Il gorilla è intelligente.',exEn:'The gorilla is intelligent.'},
    {it:'la scimmia',en:'the monkey',cat:'Animal',ipa:'/la ˈʃim.mja/',ex:'Le scimmie si arrampicano.',exEn:'Monkeys climb.'},
    {it:'l\'orso',en:'the bear',cat:'Animal',ipa:'/ˈlor.so/',ex:'L\'orso mangia il miele.',exEn:'The bear eats honey.'},
    {it:'il lupo',en:'the wolf',cat:'Animal',ipa:'/il ˈluː.po/',ex:'Il lupo ulula alla luna.',exEn:'The wolf howls at the moon.'},
    {it:'la volpe',en:'the fox',cat:'Animal',ipa:'/la ˈvol.pe/',ex:'La volpe è astuta.',exEn:'The fox is cunning.'},
    {it:'il cervo',en:'the deer / stag',cat:'Animal',ipa:'/il ˈtʃɛr.vo/',ex:'Il cervo nel bosco.',exEn:'The deer in the woods.'},
    {it:'il cinghiale',en:'the wild boar',cat:'Animal',ipa:'/il tʃiŋˈɡjaː.le/',ex:'Il cinghiale è selvatico.',exEn:'The wild boar is wild.'},
    {it:'la volpe rossa',en:'the red fox',cat:'Animal',ipa:'/la ˈvol.pe ˈrɔs.sa/',ex:'La volpe rossa è comune.',exEn:'The red fox is common.'},
    {it:'l\'uccello',en:'the bird',cat:'Animal',ipa:'/lutˈtʃɛl.lo/',ex:'L\'uccello canta.',exEn:'The bird sings.'},
    {it:'il passero',en:'the sparrow',cat:'Animal',ipa:'/il ˈpas.se.ro/',ex:'I passeri in piazza.',exEn:'Sparrows in the square.'},
    {it:'il piccione',en:'the pigeon',cat:'Animal',ipa:'/il pitˈtʃoː.ne/',ex:'I piccioni di Venezia.',exEn:'The pigeons of Venice.'},
    {it:'l\'aquila',en:'the eagle',cat:'Animal',ipa:'/ˈlaː.kwi.la/',ex:'L\'aquila vola in alto.',exEn:'The eagle flies high.'},
    {it:'il pappagallo',en:'the parrot',cat:'Animal',ipa:'/il pappaˈɡal.lo/',ex:'Il pappagallo parla.',exEn:'The parrot talks.'},
    {it:'il gufo',en:'the owl',cat:'Animal',ipa:'/il ˈɡuː.fo/',ex:'Il gufo è un uccello notturno.',exEn:'The owl is a nocturnal bird.'},
    {it:'la rondine',en:'the swallow',cat:'Animal',ipa:'/la ˈron.di.ne/',ex:'Le rondini tornano in primavera.',exEn:'Swallows return in spring.'},
    {it:'il pesce',en:'the fish',cat:'Animal',ipa:'/il ˈpeʃ.ʃe/',ex:'Il pesce nuota.',exEn:'The fish swims.'},
    {it:'il tonno',en:'the tuna',cat:'Animal',ipa:'/il ˈton.no/',ex:'Il tonno fresco.',exEn:'Fresh tuna.'},
    {it:'il salmone',en:'the salmon',cat:'Animal',ipa:'/il salˈmoː.ne/',ex:'Salmone affumicato.',exEn:'Smoked salmon.'},
    {it:'il polpo',en:'the octopus',cat:'Animal',ipa:'/il ˈpɔl.po/',ex:'Polpo alla griglia.',exEn:'Grilled octopus.'},
    {it:'il granchio',en:'the crab',cat:'Animal',ipa:'/il ˈɡran.kjo/',ex:'Il granchio cammina di lato.',exEn:'The crab walks sideways.'},
    {it:'la tartaruga',en:'the tortoise / turtle',cat:'Animal',ipa:'/la tartaˈruː.ɡa/',ex:'La tartaruga è lenta.',exEn:'The tortoise is slow.'},
    {it:'il serpente',en:'the snake',cat:'Animal',ipa:'/il serˈpɛn.te/',ex:'Il serpente è velenoso.',exEn:'The snake is venomous.'},
    {it:'il coccodrillo',en:'the crocodile',cat:'Animal',ipa:'/il kokkodˈril.lo/',ex:'Il coccodrillo è pericoloso.',exEn:'The crocodile is dangerous.'},
    {it:'la rana',en:'the frog',cat:'Animal',ipa:'/la ˈraː.na/',ex:'La rana gracchia.',exEn:'The frog croaks.'},
    {it:'la lucertola',en:'the lizard',cat:'Animal',ipa:'/la luˈtʃɛr.to.la/',ex:'La lucertola prende il sole.',exEn:'The lizard sunbathes.'},
    {it:'il topo',en:'the mouse / rat',cat:'Animal',ipa:'/il ˈtoː.po/',ex:'Il topo mangia il formaggio.',exEn:'The mouse eats cheese.'},
    {it:'il riccio',en:'the hedgehog',cat:'Animal',ipa:'/il ˈrit.tʃo/',ex:'Il riccio ha le spine.',exEn:'The hedgehog has spines.'},
    {it:'il delfino',en:'the dolphin',cat:'Animal',ipa:'/il delˈfiː.no/',ex:'Il delfino è intelligente.',exEn:'The dolphin is intelligent.'},
    {it:'la balena',en:'the whale',cat:'Animal',ipa:'/la baˈleː.na/',ex:'La balena è enorme.',exEn:'The whale is enormous.'},
    {it:'lo squalo',en:'the shark',cat:'Animal',ipa:'/lo ˈskwaː.lo/',ex:'Lo squalo è un predatore.',exEn:'The shark is a predator.'},
    {it:'il pinguino',en:'the penguin',cat:'Animal',ipa:'/il piŋˈɡwiː.no/',ex:'Il pinguino non vola.',exEn:'The penguin doesn\'t fly.'},
    {it:'il coccodrillo',en:'the crocodile',cat:'Animal',ipa:'/il kokkodˈril.lo/',ex:'Il coccodrillo è rettile.',exEn:'The crocodile is a reptile.'},
    {it:'la farfalla',en:'the butterfly',cat:'Animal',ipa:'/la farˈfal.la/',ex:'La farfalla è colorata.',exEn:'The butterfly is colourful.'},
    {it:'l\'ape',en:'the bee',cat:'Animal',ipa:'/ˈlaː.pe/',ex:'L\'ape produce il miele.',exEn:'The bee produces honey.'},
    {it:'la zanzara',en:'the mosquito',cat:'Animal',ipa:'/la dzanˈdzaː.ra/',ex:'La zanzara punge.',exEn:'The mosquito bites.'},
    {it:'il ragno',en:'the spider',cat:'Animal',ipa:'/il ˈraɲ.ɲo/',ex:'Il ragno tesse la tela.',exEn:'The spider spins a web.'},
    {it:'l\'animale domestico',en:'pet',cat:'Animal',ipa:'/laniˈmaː.le doˈmɛs.ti.ko/',ex:'Hai un animale domestico?',exEn:'Do you have a pet?'},
  ]
};

window.PACK_animals.words.push(
  {it:'il bisonte',en:'bison',cat:'Animal',ipa:'/il biˈzoː.ne/',ex:'Il bisonte americano.',exEn:'The American bison.'},
  {it:'il giaguaro',en:'jaguar',cat:'Animal',ipa:'/il dʒaˈɡwaː.ro/',ex:'Il giaguaro è veloce.',exEn:'The jaguar is fast.'},
  {it:'il ghepardo',en:'cheetah',cat:'Animal',ipa:'/il ɡeˈpar.do/',ex:'Il ghepardo corre a 120 km/h.',exEn:'The cheetah runs at 120 km/h.'},
  {it:'la iena',en:'hyena',cat:'Animal',ipa:'/la ˈjeː.na/',ex:'La iena ride.',exEn:'The hyena laughs.'},
  {it:'il rinoceronte',en:'rhinoceros',cat:'Animal',ipa:'/il rinotʃeˈron.te/',ex:'Il rinoceronte è in pericolo.',exEn:'The rhinoceros is endangered.'},
  {it:'l\'ippopotamo',en:'hippopotamus',cat:'Animal',ipa:'/lippoˈpɔː.ta.mo/',ex:'L\'ippopotamo è pericoloso.',exEn:'The hippopotamus is dangerous.'},
  {it:'il cammello',en:'camel',cat:'Animal',ipa:'/il kamˈmɛl.lo/',ex:'Il cammello attraversa il deserto.',exEn:'The camel crosses the desert.'},
  {it:'il dromedario',en:'dromedary',cat:'Animal',ipa:'/il dromeˈdaː.rjo/',ex:'Il dromedario ha una gobba.',exEn:'The dromedary has one hump.'},
  {it:'il lama',en:'llama',cat:'Animal',ipa:'/il ˈlaː.ma/',ex:'Il lama peruviano.',exEn:'The Peruvian llama.'},
  {it:'il koala',en:'koala',cat:'Animal',ipa:'/il koˈaː.la/',ex:'Il koala dorme molto.',exEn:'The koala sleeps a lot.'},
  {it:'il canguro',en:'kangaroo',cat:'Animal',ipa:'/il kaŋˈɡuː.ro/',ex:'Il canguro salta lontano.',exEn:'The kangaroo jumps far.'},
  {it:'il panda',en:'panda',cat:'Animal',ipa:'/il ˈpan.da/',ex:'Il panda gigante.',exEn:'The giant panda.'},
  {it:'il fenicottero',en:'flamingo',cat:'Animal',ipa:'/il feniˈkɔt.te.ro/',ex:'Il fenicottero è rosa.',exEn:'The flamingo is pink.'},
  {it:'il pellicano',en:'pelican',cat:'Animal',ipa:'/il pelˈliː.ka.no/',ex:'Il pellicano pesca.',exEn:'The pelican fishes.'},
  {it:'il cigno',en:'swan',cat:'Animal',ipa:'/il ˈtʃiɲ.ɲo/',ex:'Il cigno è elegante.',exEn:'The swan is elegant.'},
  {it:'l\'anatra',en:'duck',cat:'Animal',ipa:'/ˈlaː.na.tra/',ex:'L\'anatra nuota nel lago.',exEn:'The duck swims in the lake.'},
  {it:'l\'oca',en:'goose',cat:'Animal',ipa:'/ˈloː.ka/',ex:'Le oche fanno rumore.',exEn:'The geese make noise.'},
  {it:'il tacchino',en:'turkey',cat:'Animal',ipa:'/il takˈkiː.no/',ex:'Il tacchino del Ringraziamento.',exEn:'The Thanksgiving turkey.'},
  {it:'il pavone',en:'peacock',cat:'Animal',ipa:'/il paˈvoː.ne/',ex:'Il pavone fa la ruota.',exEn:'The peacock fans its tail.'},
  {it:'il corvo',en:'crow / raven',cat:'Animal',ipa:'/il ˈkor.vo/',ex:'Il corvo è intelligente.',exEn:'The crow is intelligent.'},
  {it:'la cicogna',en:'stork',cat:'Animal',ipa:'/la tʃiˈkoɲ.ɲa/',ex:'La cicogna porta i bambini.',exEn:'The stork brings babies.'},
  {it:'il fenicottero',en:'flamingo',cat:'Animal',ipa:'/il feniˈkɔt.te.ro/',ex:'I fenicotteri rosa.',exEn:'The pink flamingos.'},
  {it:'il porcospino',en:'porcupine',cat:'Animal',ipa:'/il porkosˈpiː.no/',ex:'Il porcospino ha le spine.',exEn:'The porcupine has spines.'},
  {it:'la donnola',en:'weasel',cat:'Animal',ipa:'/la donˈnɔː.la/',ex:'La donnola è agile.',exEn:'The weasel is agile.'},
  {it:'il tasso',en:'badger / rate',cat:'Animal',ipa:'/il ˈtas.so/',ex:'Il tasso notturno.',exEn:'The nocturnal badger.'},
  {it:'la marmotta',en:'marmot',cat:'Animal',ipa:'/la marˈmɔt.ta/',ex:'La marmotta dorme d\'inverno.',exEn:'The marmot hibernates.'},
  {it:'lo stambecco',en:'ibex',cat:'Animal',ipa:'/lo stamˈbɛk.ko/',ex:'Lo stambecco sulle Alpi.',exEn:'The ibex on the Alps.'},
  {it:'il camoscio',en:'chamois',cat:'Animal',ipa:'/il kaˈmɔʃ.ʃo/',ex:'Il camoscio è agile.',exEn:'The chamois is agile.'},
  {it:'il capriolo',en:'roe deer',cat:'Animal',ipa:'/il kaˈprjoː.lo/',ex:'Il capriolo nel bosco.',exEn:'The roe deer in the woods.'},
  {it:'la lepre',en:'hare',cat:'Animal',ipa:'/la ˈleː.pre/',ex:'La lepre corre veloce.',exEn:'The hare runs fast.'},
  {it:'il ghiro',en:'dormouse',cat:'Animal',ipa:'/il ˈɡiː.ro/',ex:'Il ghiro dorme d\'inverno.',exEn:'The dormouse hibernates.'},
  {it:'la talpa',en:'mole',cat:'Animal',ipa:'/la ˈtal.pa/',ex:'La talpa scava gallerie.',exEn:'The mole digs tunnels.'},
  {it:'la lontra',en:'otter',cat:'Animal',ipa:'/la ˈlon.tra/',ex:'La lontra nuota bene.',exEn:'The otter swims well.'},
  {it:'il castoro',en:'beaver',cat:'Animal',ipa:'/il kasˈtoː.ro/',ex:'Il castoro costruisce dighe.',exEn:'The beaver builds dams.'},
  {it:'la foca',en:'seal',cat:'Animal',ipa:'/la ˈfoː.ka/',ex:'La foca suona il corno.',exEn:'The seal balances the ball.'},
  {it:'il tricheco',en:'walrus',cat:'Animal',ipa:'/il triˈkeː.ko/',ex:'Il tricheco ha le zanne.',exEn:'The walrus has tusks.'},
  {it:'l\'orso polare',en:'polar bear',cat:'Animal',ipa:'/ˈlor.so poˈlaː.re/',ex:'L\'orso polare caccia le foche.',exEn:'The polar bear hunts seals.'},
  {it:'la renna',en:'reindeer',cat:'Animal',ipa:'/la ˈrɛn.na/',ex:'La renna di Babbo Natale.',exEn:'Santa\'s reindeer.'},
  {it:'l\'alce',en:'moose / elk',cat:'Animal',ipa:'/ˈlal.tʃe/',ex:'L\'alce è enorme.',exEn:'The moose is enormous.'},
  {it:'il muflone',en:'mouflon',cat:'Animal',ipa:'/il muˈfloː.ne/',ex:'Il muflone sardo.',exEn:'The Sardinian mouflon.'},
  {it:'il cobra',en:'cobra',cat:'Animal',ipa:'/il ˈkoː.bra/',ex:'Il cobra è velenoso.',exEn:'The cobra is venomous.'},
  {it:'il pitone',en:'python',cat:'Animal',ipa:'/il piˈtoː.ne/',ex:'Il pitone stritola le prede.',exEn:'The python constricts its prey.'},
  {it:'il coccodrillo',en:'crocodile',cat:'Animal',ipa:'/il kokkodˈril.lo/',ex:'Il coccodrillo del Nilo.',exEn:'The Nile crocodile.'},
  {it:'il camaleonte',en:'chameleon',cat:'Animal',ipa:'/il kamaleˈɔn.te/',ex:'Il camaleonte cambia colore.',exEn:'The chameleon changes colour.'},
  {it:'la salamandra',en:'salamander',cat:'Animal',ipa:'/la salamˈan.dra/',ex:'La salamandra è anfibia.',exEn:'The salamander is amphibious.'},
  {it:'il rospo',en:'toad',cat:'Animal',ipa:'/il ˈrɔs.po/',ex:'Il rospo gracchia di notte.',exEn:'The toad croaks at night.'},
  {it:'la medusa',en:'jellyfish',cat:'Animal',ipa:'/la meˈduː.za/',ex:'La medusa brucia.',exEn:'The jellyfish stings.'},
  {it:'il calamaro',en:'squid',cat:'Animal',ipa:'/il kalaˈmaː.ro/',ex:'Il calamaro fritto.',exEn:'Fried squid.'},
  {it:'la seppia',en:'cuttlefish',cat:'Animal',ipa:'/la ˈsɛp.pja/',ex:'La seppia in nero.',exEn:'Cuttlefish in its ink.'}
);
