window.PACK_verbs = {
  id:'verbs', name:'Everyday Verbs', emoji:'⚡',
  words:[
    {it:'essere',en:'to be',cat:'Verb',ipa:'/ˈɛs.se.re/',ex:'Sono italiano.',exEn:'I am Italian.'},
    {it:'avere',en:'to have',cat:'Verb',ipa:'/aˈveː.re/',ex:'Ho fame.',exEn:'I am hungry.'},
    {it:'fare',en:'to do / make',cat:'Verb',ipa:'/ˈfaː.re/',ex:'Cosa fai stasera?',exEn:'What are you doing tonight?'},
    {it:'andare',en:'to go',cat:'Verb',ipa:'/anˈdaː.re/',ex:'Andiamo al cinema!',exEn:'Let\'s go to the cinema!'},
    {it:'venire',en:'to come',cat:'Verb',ipa:'/veˈniː.re/',ex:'Vieni con noi?',exEn:'Are you coming with us?'},
    {it:'parlare',en:'to speak / talk',cat:'Verb',ipa:'/parˈlaː.re/',ex:'Parli italiano?',exEn:'Do you speak Italian?'},
    {it:'mangiare',en:'to eat',cat:'Verb',ipa:'/manˈdʒaː.re/',ex:'Mangiamo insieme.',exEn:'Let\'s eat together.'},
    {it:'bere',en:'to drink',cat:'Verb',ipa:'/ˈbeː.re/',ex:'Vuoi bere qualcosa?',exEn:'Do you want to drink something?'},
    {it:'dormire',en:'to sleep',cat:'Verb',ipa:'/dorˈmiː.re/',ex:'Dormo otto ore per notte.',exEn:'I sleep eight hours a night.'},
    {it:'capire',en:'to understand',cat:'Verb',ipa:'/kaˈpiː.re/',ex:'Non capisco bene.',exEn:'I don\'t understand well.'},
    {it:'volere',en:'to want',cat:'Verb',ipa:'/voˈleː.re/',ex:'Voglio imparare l\'italiano.',exEn:'I want to learn Italian.'},
    {it:'potere',en:'to be able / can',cat:'Verb',ipa:'/poˈteː.re/',ex:'Puoi aiutarmi?',exEn:'Can you help me?'},
    {it:'sapere',en:'to know (a fact)',cat:'Verb',ipa:'/saˈpeː.re/',ex:'Sai dov\'è il museo?',exEn:'Do you know where the museum is?'},
    {it:'vedere',en:'to see',cat:'Verb',ipa:'/veˈdeː.re/',ex:'Ci vediamo domani!',exEn:'See you tomorrow!'},
    {it:'comprare',en:'to buy',cat:'Verb',ipa:'/komˈpraː.re/',ex:'Voglio comprare dei souvenir.',exEn:'I want to buy some souvenirs.'},
    {it:'leggere',en:'to read',cat:'Verb',ipa:'/ˈlɛd.dʒe.re/',ex:'Leggo ogni sera.',exEn:'I read every evening.'},
    {it:'scrivere',en:'to write',cat:'Verb',ipa:'/ˈskriː.ve.re/',ex:'Scrivo una lettera.',exEn:'I\'m writing a letter.'},
    {it:'ascoltare',en:'to listen',cat:'Verb',ipa:'/askolˈtaː.re/',ex:'Ascolto la musica.',exEn:'I listen to music.'},
    {it:'guardare',en:'to watch / look at',cat:'Verb',ipa:'/ɡwarˈdaː.re/',ex:'Guardo la televisione.',exEn:'I watch television.'},
    {it:'giocare',en:'to play',cat:'Verb',ipa:'/dʒoˈkaː.re/',ex:'Gioco a calcio.',exEn:'I play football.'},
    {it:'lavorare',en:'to work',cat:'Verb',ipa:'/lavoˈraː.re/',ex:'Lavoro in un ufficio.',exEn:'I work in an office.'},
    {it:'studiare',en:'to study',cat:'Verb',ipa:'/stuˈdjaː.re/',ex:'Studio italiano ogni giorno.',exEn:'I study Italian every day.'},
    {it:'imparare',en:'to learn',cat:'Verb',ipa:'/impaˈraː.re/',ex:'Voglio imparare a cucinare.',exEn:'I want to learn to cook.'},
    {it:'insegnare',en:'to teach',cat:'Verb',ipa:'/inseɲˈɲaː.re/',ex:'Insegno l\'inglese.',exEn:'I teach English.'},
    {it:'abitare',en:'to live / reside',cat:'Verb',ipa:'/abiˈtaː.re/',ex:'Abito a Roma.',exEn:'I live in Rome.'},
    {it:'camminare',en:'to walk',cat:'Verb',ipa:'/kammiˈnaː.re/',ex:'Cammino per un\'ora.',exEn:'I walk for an hour.'},
    {it:'correre',en:'to run',cat:'Verb',ipa:'/ˈkor.re.re/',ex:'Corro ogni mattina.',exEn:'I run every morning.'},
    {it:'nuotare',en:'to swim',cat:'Verb',ipa:'/nwoˈtaː.re/',ex:'Nuoto in piscina.',exEn:'I swim in the pool.'},
    {it:'cucinare',en:'to cook',cat:'Verb',ipa:'/kutʃiˈnaː.re/',ex:'Mi piace cucinare.',exEn:'I like to cook.'},
    {it:'pulire',en:'to clean',cat:'Verb',ipa:'/puˈliː.re/',ex:'Pulisco la casa il sabato.',exEn:'I clean the house on Saturdays.'},
    {it:'aprire',en:'to open',cat:'Verb',ipa:'/aˈpriː.re/',ex:'Apri la finestra, per favore.',exEn:'Open the window, please.'},
    {it:'chiudere',en:'to close',cat:'Verb',ipa:'/ˈkjuː.de.re/',ex:'Chiudi la porta.',exEn:'Close the door.'},
    {it:'cercare',en:'to look for / search',cat:'Verb',ipa:'/tʃerˈkaː.re/',ex:'Cerco il mio telefono.',exEn:'I\'m looking for my phone.'},
    {it:'trovare',en:'to find',cat:'Verb',ipa:'/troˈvaː.re/',ex:'Ho trovato le chiavi!',exEn:'I found the keys!'},
    {it:'portare',en:'to bring / carry / wear',cat:'Verb',ipa:'/porˈtaː.re/',ex:'Porto il mio ombrello.',exEn:'I\'m bringing my umbrella.'},
    {it:'dare',en:'to give',cat:'Verb',ipa:'/ˈdaː.re/',ex:'Dammi la mano.',exEn:'Give me your hand.'},
    {it:'prendere',en:'to take / get',cat:'Verb',ipa:'/ˈprɛn.de.re/',ex:'Prendo il treno.',exEn:'I\'ll take the train.'},
    {it:'mettere',en:'to put / place',cat:'Verb',ipa:'/ˈmet.te.re/',ex:'Metto le chiavi sul tavolo.',exEn:'I put the keys on the table.'},
    {it:'sentire',en:'to hear / feel',cat:'Verb',ipa:'/senˈtiː.re/',ex:'Senti questa canzone?',exEn:'Can you hear this song?'},
    {it:'pensare',en:'to think',cat:'Verb',ipa:'/penˈsaː.re/',ex:'Penso che sia bello.',exEn:'I think it\'s beautiful.'},
    {it:'credere',en:'to believe',cat:'Verb',ipa:'/ˈkreː.de.re/',ex:'Non ci credo!',exEn:'I can\'t believe it!'},
    {it:'sperare',en:'to hope',cat:'Verb',ipa:'/speˈraː.re/',ex:'Spero che venga.',exEn:'I hope he comes.'},
    {it:'dimenticare',en:'to forget',cat:'Verb',ipa:'/dimentiˈkaː.re/',ex:'Ho dimenticato l\'ombrello.',exEn:'I forgot my umbrella.'},
    {it:'ricordare',en:'to remember',cat:'Verb',ipa:'/rikordaˈre/',ex:'Non ricordo il suo nome.',exEn:'I don\'t remember his name.'},
    {it:'aspettare',en:'to wait',cat:'Verb',ipa:'/aspetˈtaː.re/',ex:'Aspetto qui.',exEn:'I\'ll wait here.'},
    {it:'incontrare',en:'to meet',cat:'Verb',ipa:'/inkonˈtraː.re/',ex:'Ci incontriamo alle otto.',exEn:'We\'ll meet at eight.'},
    {it:'conoscere',en:'to know (a person)',cat:'Verb',ipa:'/koˈnoʃ.ʃe.re/',ex:'Conosco Roma bene.',exEn:'I know Rome well.'},
    {it:'aiutare',en:'to help',cat:'Verb',ipa:'/ajuˈtaː.re/',ex:'Puoi aiutarmi?',exEn:'Can you help me?'},
    {it:'cominciare',en:'to begin / start',cat:'Verb',ipa:'/kominˈtʃaː.re/',ex:'Il film comincia alle otto.',exEn:'The film starts at eight.'},
    {it:'finire',en:'to finish / end',cat:'Verb',ipa:'/fiˈniː.re/',ex:'Ho finito il libro.',exEn:'I finished the book.'},
    {it:'tornare',en:'to return / come back',cat:'Verb',ipa:'/torˈnaː.re/',ex:'Torno a casa alle sei.',exEn:'I return home at six.'},
    {it:'partire',en:'to leave / depart',cat:'Verb',ipa:'/parˈtiː.re/',ex:'Partiamo domani mattina.',exEn:'We leave tomorrow morning.'},
    {it:'arrivare',en:'to arrive',cat:'Verb',ipa:'/arriˈvaː.re/',ex:'Arriviamo alle tre.',exEn:'We arrive at three.'},
    {it:'entrare',en:'to enter',cat:'Verb',ipa:'/enˈtraː.re/',ex:'Entra pure!',exEn:'Please come in!'},
    {it:'uscire',en:'to go out / exit',cat:'Verb',ipa:'/uˈʃiː.re/',ex:'Usciamo stasera?',exEn:'Shall we go out tonight?'},
    {it:'salire',en:'to go up / get on',cat:'Verb',ipa:'/saˈliː.re/',ex:'Salgo al piano di sopra.',exEn:'I\'m going up to the floor above.'},
    {it:'scendere',en:'to go down / get off',cat:'Verb',ipa:'/ˈʃɛn.de.re/',ex:'Scendo alla prossima fermata.',exEn:'I\'m getting off at the next stop.'},
    {it:'pagare',en:'to pay',cat:'Verb',ipa:'/paˈɡaː.re/',ex:'Posso pagare con carta?',exEn:'Can I pay by card?'},
    {it:'spendere',en:'to spend',cat:'Verb',ipa:'/ˈspɛn.de.re/',ex:'Ho speso troppo.',exEn:'I\'ve spent too much.'},
    {it:'vendere',en:'to sell',cat:'Verb',ipa:'/ˈvɛn.de.re/',ex:'Vendono scarpe.',exEn:'They sell shoes.'},
    {it:'cambiare',en:'to change',cat:'Verb',ipa:'/kamˈbjaː.re/',ex:'Voglio cambiare la prenotazione.',exEn:'I want to change the booking.'},
    {it:'scegliere',en:'to choose',cat:'Verb',ipa:'/ˈʃeʎ.ʎe.re/',ex:'Ho scelto il risotto.',exEn:'I chose the risotto.'},
    {it:'preferire',en:'to prefer',cat:'Verb',ipa:'/preferiˈre/',ex:'Preferisco il tè al caffè.',exEn:'I prefer tea to coffee.'},
    {it:'piacere',en:'to like / please',cat:'Verb',ipa:'/pjaˈtʃeː.re/',ex:'Mi piace Roma.',exEn:'I like Rome.'},
    {it:'amare',en:'to love',cat:'Verb',ipa:'/aˈmaː.re/',ex:'Amo la cucina italiana.',exEn:'I love Italian cuisine.'},
    {it:'odiare',en:'to hate',cat:'Verb',ipa:'/oˈdjaː.re/',ex:'Odio aspettare.',exEn:'I hate waiting.'},
    {it:'ridere',en:'to laugh',cat:'Verb',ipa:'/ˈriː.de.re/',ex:'Ridi sempre.',exEn:'You always laugh.'},
    {it:'piangere',en:'to cry',cat:'Verb',ipa:'/ˈpjan.dʒe.re/',ex:'Non piangere!',exEn:'Don\'t cry!'},
    {it:'sorridere',en:'to smile',cat:'Verb',ipa:'/sorˈriː.de.re/',ex:'Sorridi!',exEn:'Smile!'},
    {it:'chiamare',en:'to call',cat:'Verb',ipa:'/kjaˈmaː.re/',ex:'Ti chiamo dopo.',exEn:'I\'ll call you later.'},
    {it:'rispondere',en:'to answer / reply',cat:'Verb',ipa:'/risˈpɔn.de.re/',ex:'Non risponde al telefono.',exEn:'He doesn\'t answer the phone.'},
    {it:'chiedere',en:'to ask',cat:'Verb',ipa:'/ˈkjeː.de.re/',ex:'Posso chiederti una cosa?',exEn:'Can I ask you something?'},
    {it:'spiegare',en:'to explain',cat:'Verb',ipa:'/spjeˈɡaː.re/',ex:'Puoi spiegarmelo?',exEn:'Can you explain it to me?'},
    {it:'capire',en:'to understand',cat:'Verb',ipa:'/kaˈpiː.re/',ex:'Hai capito?',exEn:'Did you understand?'},
    {it:'viaggiare',en:'to travel',cat:'Verb',ipa:'/vjadˈdʒaː.re/',ex:'Mi piace viaggiare.',exEn:'I like to travel.'},
    {it:'visitare',en:'to visit',cat:'Verb',ipa:'/viziˈtaː.re/',ex:'Voglio visitare Firenze.',exEn:'I want to visit Florence.'},
    {it:'prenotare',en:'to book / reserve',cat:'Verb',ipa:'/prenoˈtaː.re/',ex:'Ho prenotato un tavolo.',exEn:'I\'ve booked a table.'},
    {it:'guidare',en:'to drive',cat:'Verb',ipa:'/ɡwiˈdaː.re/',ex:'Sai guidare?',exEn:'Can you drive?'},
    {it:'parcheggiare',en:'to park',cat:'Verb',ipa:'/parkɛdˈdʒaː.re/',ex:'Dove posso parcheggiare?',exEn:'Where can I park?'},
    {it:'perdere',en:'to lose',cat:'Verb',ipa:'/ˈpɛr.de.re/',ex:'Ho perso le chiavi.',exEn:'I\'ve lost the keys.'},
    {it:'rompere',en:'to break',cat:'Verb',ipa:'/ˈrom.pe.re/',ex:'Ho rotto il bicchiere.',exEn:'I broke the glass.'},
    {it:'costruire',en:'to build',cat:'Verb',ipa:'/kostruˈiː.re/',ex:'Costruiscono un palazzo nuovo.',exEn:'They\'re building a new building.'},
    {it:'nascere',en:'to be born',cat:'Verb',ipa:'/ˈnaʃ.ʃe.re/',ex:'Sono nato a Milano.',exEn:'I was born in Milan.'},
    {it:'morire',en:'to die',cat:'Verb',ipa:'/moˈriː.re/',ex:'Dante morì nel 1321.',exEn:'Dante died in 1321.'},
    {it:'vivere',en:'to live',cat:'Verb',ipa:'/ˈviː.ve.re/',ex:'Vivo a Londra.',exEn:'I live in London.'},
    {it:'passare',en:'to pass / spend (time)',cat:'Verb',ipa:'/pasˈsaː.re/',ex:'Ho passato le vacanze in Sicilia.',exEn:'I spent the holidays in Sicily.'},
    {it:'restare',en:'to stay / remain',cat:'Verb',ipa:'/resˈtaː.re/',ex:'Resto qui stanotte.',exEn:'I\'m staying here tonight.'},
    {it:'diventare',en:'to become',cat:'Verb',ipa:'/divenˈtaː.re/',ex:'Vuole diventare medico.',exEn:'He wants to become a doctor.'},
    {it:'sembrare',en:'to seem / appear',cat:'Verb',ipa:'/semˈbraː.re/',ex:'Sembra stanco.',exEn:'He seems tired.'},
    {it:'succedere',en:'to happen',cat:'Verb',ipa:'/sutˈtʃeː.de.re/',ex:'Cosa è successo?',exEn:'What happened?'},
    {it:'accadere',en:'to occur / take place',cat:'Verb',ipa:'/akkaˈdeː.re/',ex:'Quando è accaduto?',exEn:'When did it occur?'},
    {it:'continuare',en:'to continue',cat:'Verb',ipa:'/kontiˈnwaː.re/',ex:'Continua a destra.',exEn:'Continue to the right.'},
    {it:'smettere',en:'to stop / quit',cat:'Verb',ipa:'/ˈzmɛt.te.re/',ex:'Ho smesso di fumare.',exEn:'I stopped smoking.'},
    {it:'ricevere',en:'to receive',cat:'Verb',ipa:'/riˈtʃeː.ve.re/',ex:'Ho ricevuto una lettera.',exEn:'I received a letter.'},
    {it:'mandare',en:'to send',cat:'Verb',ipa:'/manˈdaː.re/',ex:'Manda un messaggio.',exEn:'Send a message.'},
    {it:'incontrare',en:'to meet / encounter',cat:'Verb',ipa:'/inkonˈtraː.re/',ex:'Ho incontrato un amico.',exEn:'I met a friend.'},
  ]
};

window.PACK_verbs.words.push(
  {it:'traslocare',en:'to move house',cat:'Verb',ipa:'/trazloˈkaː.re/',ex:'Abbiamo trasloccato.',exEn:'We moved house.'},
  {it:'lamentarsi',en:'to complain',cat:'Verb',ipa:'/lamenˈtar.si/',ex:'Smetti di lamentarti!',exEn:'Stop complaining!'},
  {it:'innamorarsi',en:'to fall in love',cat:'Verb',ipa:'/innamoˈrar.si/',ex:'Mi sono innamorato.',exEn:'I fell in love.'},
  {it:'sbagliarsi',en:'to be wrong',cat:'Verb',ipa:'/sbaʎˈʎar.si/',ex:'Mi sono sbagliato.',exEn:'I was wrong.'}
);
