window.PACK_home = {
  id:'home', name:'Home & Furniture', emoji:'🏠',
  words:[
    {it:'la casa',en:'the house / home',cat:'Home',ipa:'/la ˈkaː.za/',ex:'Abito in una casa grande.',exEn:'I live in a big house.'},
    {it:'l\'appartamento',en:'the apartment / flat',cat:'Home',ipa:'/lappartaˈmɛn.to/',ex:'Ho un appartamento in centro.',exEn:'I have a flat in the centre.'},
    {it:'la stanza',en:'the room',cat:'Home',ipa:'/la ˈstan.tsa/',ex:'L\'appartamento ha tre stanze.',exEn:'The flat has three rooms.'},
    {it:'il salotto',en:'the living room',cat:'Home',ipa:'/il saˈlɔt.to/',ex:'Guardiamo la TV in salotto.',exEn:'We watch TV in the living room.'},
    {it:'la cucina',en:'the kitchen',cat:'Home',ipa:'/la kuˈtʃiː.na/',ex:'La cucina è moderna.',exEn:'The kitchen is modern.'},
    {it:'la camera da letto',en:'the bedroom',cat:'Home',ipa:'/la ˈkaː.me.ra da ˈlɛt.to/',ex:'La camera da letto è al piano di sopra.',exEn:'The bedroom is upstairs.'},
    {it:'il bagno',en:'the bathroom',cat:'Home',ipa:'/il ˈbaɲ.ɲo/',ex:'Il bagno è in fondo al corridoio.',exEn:'The bathroom is at the end of the corridor.'},
    {it:'il corridoio',en:'the hallway / corridor',cat:'Home',ipa:'/il korriˈdoː.jo/',ex:'Il corridoio è stretto.',exEn:'The hallway is narrow.'},
    {it:'il giardino',en:'the garden',cat:'Home',ipa:'/il dʒarˈdiː.no/',ex:'Ho un piccolo giardino.',exEn:'I have a small garden.'},
    {it:'il balcone',en:'the balcony',cat:'Home',ipa:'/il balˈkoː.ne/',ex:'Il balcone dà sul mare.',exEn:'The balcony faces the sea.'},
    {it:'il piano',en:'the floor / storey',cat:'Home',ipa:'/il ˈpjaː.no/',ex:'Abito al secondo piano.',exEn:'I live on the second floor.'},
    {it:'le scale',en:'the stairs',cat:'Home',ipa:'/le ˈskaː.le/',ex:'Prendo le scale.',exEn:'I\'ll take the stairs.'},
    {it:'l\'ascensore',en:'the lift / elevator',cat:'Home',ipa:'/laʃʃenˈsoː.re/',ex:'L\'ascensore è rotto.',exEn:'The lift is broken.'},
    {it:'la porta',en:'the door',cat:'Home',ipa:'/la ˈpɔr.ta/',ex:'Chiudi la porta.',exEn:'Close the door.'},
    {it:'la finestra',en:'the window',cat:'Home',ipa:'/la fiˈnɛs.tra/',ex:'Apri la finestra.',exEn:'Open the window.'},
    {it:'il letto',en:'the bed',cat:'Home',ipa:'/il ˈlɛt.to/',ex:'Il letto è comodo.',exEn:'The bed is comfortable.'},
    {it:'il divano',en:'the sofa / couch',cat:'Home',ipa:'/il diˈvaː.no/',ex:'Mi siedo sul divano.',exEn:'I sit on the sofa.'},
    {it:'la sedia',en:'the chair',cat:'Home',ipa:'/la ˈseː.dja/',ex:'Siediti su questa sedia.',exEn:'Sit on this chair.'},
    {it:'il tavolo',en:'the table',cat:'Home',ipa:'/il ˈtaː.vo.lo/',ex:'Il tavolo è rotondo.',exEn:'The table is round.'},
    {it:'l\'armadio',en:'the wardrobe / cupboard',cat:'Home',ipa:'/larˈmaː.djo/',ex:'L\'armadio è pieno.',exEn:'The wardrobe is full.'},
    {it:'il cassetto',en:'the drawer',cat:'Home',ipa:'/il kasˈsɛt.to/',ex:'È nel cassetto.',exEn:'It\'s in the drawer.'},
    {it:'il frigorifero',en:'the fridge',cat:'Home',ipa:'/il friɡoˈriː.fe.ro/',ex:'Il frigo è vuoto.',exEn:'The fridge is empty.'},
    {it:'il forno',en:'the oven',cat:'Home',ipa:'/il ˈfor.no/',ex:'Il pane è nel forno.',exEn:'The bread is in the oven.'},
    {it:'la lavastoviglie',en:'the dishwasher',cat:'Home',ipa:'/la lavastovˈiʎ.ʎe/',ex:'Metto i piatti nella lavastoviglie.',exEn:'I put the plates in the dishwasher.'},
    {it:'la lavatrice',en:'the washing machine',cat:'Home',ipa:'/la lavaˈtriː.tʃe/',ex:'Metto i vestiti in lavatrice.',exEn:'I put the clothes in the washing machine.'},
    {it:'il microonde',en:'the microwave',cat:'Home',ipa:'/il mikroˈɔn.de/',ex:'Scaldo nel microonde.',exEn:'I heat it in the microwave.'},
    {it:'la lampada',en:'the lamp',cat:'Home',ipa:'/la ˈlam.pa.da/',ex:'Accendi la lampada.',exEn:'Turn on the lamp.'},
    {it:'lo specchio',en:'the mirror',cat:'Home',ipa:'/lo ˈspɛk.kjo/',ex:'Mi guardo nello specchio.',exEn:'I look at myself in the mirror.'},
    {it:'il tappeto',en:'the carpet / rug',cat:'Home',ipa:'/il tapˈpeː.to/',ex:'Il tappeto è persiano.',exEn:'The carpet is Persian.'},
    {it:'le tende',en:'the curtains',cat:'Home',ipa:'/le ˈtɛn.de/',ex:'Chiudi le tende.',exEn:'Close the curtains.'},
    {it:'il cuscino',en:'the cushion / pillow',cat:'Home',ipa:'/il kuˈʃiː.no/',ex:'Il cuscino è morbido.',exEn:'The cushion is soft.'},
    {it:'la coperta',en:'the blanket',cat:'Home',ipa:'/la koˈpɛr.ta/',ex:'Prendo la coperta.',exEn:'I\'ll get the blanket.'},
    {it:'il lenzuolo',en:'the bed sheet',cat:'Home',ipa:'/il lenˈtswɔː.lo/',ex:'Cambio le lenzuola.',exEn:'I\'m changing the sheets.'},
    {it:'il lavandino',en:'the sink / washbasin',cat:'Home',ipa:'/il lavanˈdiː.no/',ex:'Il lavandino è intasato.',exEn:'The sink is blocked.'},
    {it:'il rubinetto',en:'the tap / faucet',cat:'Home',ipa:'/il rubiˈnɛt.to/',ex:'Il rubinetto perde.',exEn:'The tap is dripping.'},
    {it:'la doccia',en:'the shower',cat:'Home',ipa:'/la ˈdɔt.tʃa/',ex:'Faccio la doccia ogni mattina.',exEn:'I have a shower every morning.'},
    {it:'la vasca da bagno',en:'the bath / bathtub',cat:'Home',ipa:'/la ˈvas.ka da ˈbaɲ.ɲo/',ex:'Mi faccio un bagno caldo.',exEn:'I\'m having a hot bath.'},
    {it:'la spazzatura',en:'the rubbish / garbage',cat:'Home',ipa:'/la spattsaˈtuː.ra/',ex:'Porto fuori la spazzatura.',exEn:'I\'m taking out the rubbish.'},
    {it:'la chiave',en:'the key',cat:'Home',ipa:'/la ˈkjaː.ve/',ex:'Ho perso la chiave.',exEn:'I lost the key.'},
    {it:'il campanello',en:'the doorbell',cat:'Home',ipa:'/il kampaˈnɛl.lo/',ex:'Suona il campanello.',exEn:'Ring the doorbell.'},
    {it:'il citofono',en:'the intercom',cat:'Home',ipa:'/il ˈtʃiː.to.fo.no/',ex:'Rispondo al citofono.',exEn:'I\'ll answer the intercom.'},
    {it:'il garage',en:'the garage',cat:'Home',ipa:'/il ɡaˈraːʒ/',ex:'La macchina è nel garage.',exEn:'The car is in the garage.'},
    {it:'la cantina',en:'the cellar',cat:'Home',ipa:'/la kanˈtiː.na/',ex:'Il vino è in cantina.',exEn:'The wine is in the cellar.'},
    {it:'il soffitta',en:'the attic',cat:'Home',ipa:'/il sofˈfit.ta/',ex:'Ho molte cose in soffitta.',exEn:'I have many things in the attic.'},
    {it:'il riscaldamento',en:'heating',cat:'Home',ipa:'/il riscaldaˈmɛn.to/',ex:'Il riscaldamento è rotto.',exEn:'The heating is broken.'},
    {it:'l\'aria condizionata',en:'air conditioning',cat:'Home',ipa:'/ˈlaː.rja konditsjoˈnaː.ta/',ex:'L\'aria condizionata non funziona.',exEn:'The air conditioning doesn\'t work.'},
    {it:'affittare',en:'to rent',cat:'Home',ipa:'/afitˈtaː.re/',ex:'Affitto un appartamento.',exEn:'I rent a flat.'},
    {it:'comprare casa',en:'to buy a house',cat:'Home',ipa:'/komˈpraː.re ˈkaː.za/',ex:'Vogliamo comprare casa.',exEn:'We want to buy a house.'},
    {it:'il mutuo',en:'the mortgage',cat:'Home',ipa:'/il ˈmuː.two/',ex:'Ho un mutuo.',exEn:'I have a mortgage.'},
    {it:'il condominio',en:'the block of flats',cat:'Home',ipa:'/il kondoˈmiː.njo/',ex:'Abito in un condominio.',exEn:'I live in a block of flats.'},
    {it:'il proprietario',en:'the landlord / owner',cat:'Home',ipa:'/il proprjeˈtaː.rjo/',ex:'Il proprietario è gentile.',exEn:'The landlord is kind.'},
  ]
};

window.PACK_home.words.push(
  {it:'il tetto',en:'roof',cat:'Home',ipa:'/il ˈtɛt.to/',ex:'Il tetto perde.',exEn:'The roof leaks.'},
  {it:'il pavimento',en:'floor',cat:'Home',ipa:'/il paviˈmɛn.to/',ex:'Il pavimento è in marmo.',exEn:'The floor is marble.'},
  {it:'il soffitto',en:'ceiling',cat:'Home',ipa:'/il sofˈfit.to/',ex:'Il soffitto è alto.',exEn:'The ceiling is high.'},
  {it:'il muro',en:'wall',cat:'Home',ipa:'/il ˈmuː.ro/',ex:'Il muro è spesso.',exEn:'The wall is thick.'},
  {it:'l\'ingresso',en:'entrance hall',cat:'Home',ipa:'/linˈɡrɛs.so/',ex:'L\'ingresso è piccolo.',exEn:'The entrance hall is small.'},
  {it:'lo studio',en:'study / home office',cat:'Home',ipa:'/lo ˈstuː.djo/',ex:'Lavoro nello studio.',exEn:'I work in the study.'},
  {it:'la sala da pranzo',en:'dining room',cat:'Home',ipa:'/la ˈsaː.la da ˈpran.dzo/',ex:'La sala da pranzo è grande.',exEn:'The dining room is big.'},
  {it:'il ripostiglio',en:'storage room',cat:'Home',ipa:'/il riposˈtiʎ.ʎo/',ex:'Il ripostiglio è pieno.',exEn:'The storage room is full.'},
  {it:'il terrazzo',en:'terrace',cat:'Home',ipa:'/il terˈrat.tso/',ex:'Ceno in terrazzo.',exEn:'I dine on the terrace.'},
  {it:'il patio',en:'patio',cat:'Home',ipa:'/il ˈpaː.tjo/',ex:'Il patio è soleggiato.',exEn:'The patio is sunny.'},
  {it:'il vialetto',en:'driveway',cat:'Home',ipa:'/il vjaˈlɛt.to/',ex:'Il vialetto in ghiaia.',exEn:'The gravel driveway.'},
  {it:'il cancello',en:'gate',cat:'Home',ipa:'/il kanˈtʃɛl.lo/',ex:'Il cancello è chiuso.',exEn:'The gate is closed.'},
  {it:'il recinto',en:'fence',cat:'Home',ipa:'/il reˈtʃin.to/',ex:'Il recinto del giardino.',exEn:'The garden fence.'},
  {it:'la piscina',en:'swimming pool',cat:'Home',ipa:'/la piˈʃiː.na/',ex:'Abbiamo una piscina.',exEn:'We have a swimming pool.'},
  {it:'il barbecue',en:'barbecue',cat:'Home',ipa:'/il ˈbɑːr.bɪ.kjuː/',ex:'Facciamo il barbecue!',exEn:'Let\'s have a barbecue!'},
  {it:'la mensola',en:'shelf',cat:'Home',ipa:'/la ˈmɛn.so.la/',ex:'I libri sulla mensola.',exEn:'The books on the shelf.'},
  {it:'il comodino',en:'bedside table',cat:'Home',ipa:'/il komoˈdiː.no/',ex:'Il comodino accanto al letto.',exEn:'The bedside table next to the bed.'},
  {it:'il letto matrimoniale',en:'double bed',cat:'Home',ipa:'/il ˈlɛt.to matrimoˈnjaː.le/',ex:'Un letto matrimoniale grande.',exEn:'A large double bed.'},
  {it:'il letto singolo',en:'single bed',cat:'Home',ipa:'/il ˈlɛt.to ˈsiŋ.ɡo.lo/',ex:'Un letto singolo.',exEn:'A single bed.'},
  {it:'il lettino',en:'cot / small bed',cat:'Home',ipa:'/il letˈtiː.no/',ex:'Il lettino del bambino.',exEn:'The baby\'s cot.'},
  {it:'il divano letto',en:'sofa bed',cat:'Home',ipa:'/il diˈvaː.no ˈlɛt.to/',ex:'Il divano letto per gli ospiti.',exEn:'The sofa bed for guests.'},
  {it:'la poltrona',en:'armchair',cat:'Home',ipa:'/la polˈtroː.na/',ex:'Mi siedo in poltrona.',exEn:'I sit in the armchair.'},
  {it:'il pouf',en:'pouffe / ottoman',cat:'Home',ipa:'/il puf/',ex:'Un pouf comodo.',exEn:'A comfortable pouffe.'},
  {it:'il tavolino',en:'coffee table',cat:'Home',ipa:'/il tavoˈliː.no/',ex:'Il tavolino del salotto.',exEn:'The living room coffee table.'},
  {it:'la libreria',en:'bookcase',cat:'Home',ipa:'/la libreˈriː.a/',ex:'La libreria è piena di libri.',exEn:'The bookcase is full of books.'},
  {it:'la cornice',en:'picture frame',cat:'Home',ipa:'/la korˈniː.tʃe/',ex:'Una cornice dorata.',exEn:'A golden frame.'},
  {it:'il quadro',en:'painting',cat:'Home',ipa:'/il ˈkwaː.dro/',ex:'Un quadro sul muro.',exEn:'A painting on the wall.'},
  {it:'lo zerbino',en:'doormat',cat:'Home',ipa:'/lo dzerˈbiː.no/',ex:'Pulisciti i piedi sullo zerbino.',exEn:'Wipe your feet on the doormat.'},
  {it:'la moquette',en:'carpet (fitted)',cat:'Home',ipa:'/la moˈkɛt/',ex:'La moquette in camera da letto.',exEn:'Fitted carpet in the bedroom.'},
  {it:'le veneziane',en:'venetian blinds',cat:'Home',ipa:'/le venetˈsjaː.ne/',ex:'Chiudo le veneziane.',exEn:'I close the blinds.'},
  {it:'i doppi vetri',en:'double glazing',cat:'Home',ipa:'/i ˈdɔp.pi ˈveː.tri/',ex:'I doppi vetri isolano bene.',exEn:'Double glazing insulates well.'},
  {it:'il termosifone',en:'radiator',cat:'Home',ipa:'/il termosi.foˈne/',ex:'Il termosifone è caldo.',exEn:'The radiator is warm.'},
  {it:'il condizionatore',en:'air conditioner',cat:'Home',ipa:'/il konditsjonaˈtoː.re/',ex:'Accendo il condizionatore.',exEn:'I turn on the air conditioner.'},
  {it:'il citofono',en:'intercom',cat:'Home',ipa:'/il ˈtʃiː.to.fo.no/',ex:'Rispondo al citofono.',exEn:'I answer the intercom.'},
  {it:'la cassetta delle lettere',en:'letterbox',cat:'Home',ipa:'/la kasˈsɛt.ta ˈdɛl.le ˈlɛt.te.re/',ex:'La posta nella cassetta.',exEn:'The post in the letterbox.'},
  {it:'l\'interruttore',en:'light switch',cat:'Home',ipa:'/linterrutˈtoː.re/',ex:'Accendi l\'interruttore.',exEn:'Switch on the light.'},
  {it:'la presa elettrica',en:'electric socket',cat:'Home',ipa:'/la ˈpreː.za eletˈtriː.ka/',ex:'La presa è rotta.',exEn:'The socket is broken.'},
  {it:'il contatore',en:'electricity / water meter',cat:'Home',ipa:'/il kontaˈtoː.re/',ex:'Leggo il contatore.',exEn:'I read the meter.'},
  {it:'la bolletta',en:'utility bill',cat:'Home',ipa:'/la bolˈlɛt.ta/',ex:'La bolletta del gas.',exEn:'The gas bill.'},
  {it:'le spese condominiali',en:'service charge / maintenance fees',cat:'Home',ipa:'/le ˈspeː.ze kondomiˈnjaː.li/',ex:'Le spese condominiali mensili.',exEn:'Monthly service charges.'},
  {it:'il piano terra',en:'ground floor',cat:'Home',ipa:'/il ˈpjaː.no ˈtɛr.ra/',ex:'Abito al piano terra.',exEn:'I live on the ground floor.'},
  {it:'il seminterrato',en:'basement',cat:'Home',ipa:'/il seminteˈraː.to/',ex:'La cantina al seminterrato.',exEn:'The cellar in the basement.'},
  {it:'il sottotetto',en:'attic / loft',cat:'Home',ipa:'/il sottoˈtɛt.to/',ex:'Ho trasformato il sottotetto.',exEn:'I converted the attic.'},
  {it:'il box auto',en:'garage / parking space',cat:'Home',ipa:'/il bɔks ˈaʊ.to/',ex:'Ho un box auto.',exEn:'I have a parking space.'},
  {it:'la domotica',en:'home automation',cat:'Home',ipa:'/la doˈmɔː.ti.ka/',ex:'La domotica controlla tutto.',exEn:'Home automation controls everything.'},
  {it:'l\'impianto elettrico',en:'electrical system',cat:'Home',ipa:'/limˈpjan.to eletˈtriː.ko/',ex:'L\'impianto elettrico è nuovo.',exEn:'The electrical system is new.'},
  {it:'l\'impianto idraulico',en:'plumbing',cat:'Home',ipa:'/limˈpjan.to idˈraʊ.li.ko/',ex:'L\'impianto idraulico perde.',exEn:'The plumbing is leaking.'},
  {it:'ristrutturare',en:'to renovate',cat:'Home',ipa:'/ristruttuˈraː.re/',ex:'Voglio ristrutturare casa.',exEn:'I want to renovate the house.'},
  {it:'i lavori di ristrutturazione',en:'renovation works',cat:'Home',ipa:'/i laˈvoː.ri di ristrutturatˈtsjoː.ne/',ex:'I lavori sono in corso.',exEn:'The renovation works are ongoing.'}
);
