window.PACK_nature = {
  id:'nature', name:'Nature & Weather', emoji:'🌿',
  words:[
    {it:'il tempo',en:'the weather',cat:'Nature',ipa:'/il ˈtɛm.po/',ex:'Che tempo fa oggi?',exEn:'What\'s the weather like today?'},
    {it:'il sole',en:'the sun',cat:'Nature',ipa:'/il ˈsoː.le/',ex:'C\'è il sole.',exEn:'It\'s sunny.'},
    {it:'la pioggia',en:'the rain',cat:'Nature',ipa:'/la ˈpjɔdʒ.dʒa/',ex:'Sta piovendo.',exEn:'It\'s raining.'},
    {it:'la neve',en:'the snow',cat:'Nature',ipa:'/la ˈneː.ve/',ex:'Sta nevicando.',exEn:'It\'s snowing.'},
    {it:'il vento',en:'the wind',cat:'Nature',ipa:'/il ˈvɛn.to/',ex:'C\'è molto vento.',exEn:'It\'s very windy.'},
    {it:'la nuvola',en:'the cloud',cat:'Nature',ipa:'/la ˈnuː.vo.la/',ex:'Il cielo è nuvoloso.',exEn:'The sky is cloudy.'},
    {it:'il fulmine',en:'lightning',cat:'Nature',ipa:'/il ˈful.mi.ne/',ex:'I fulmini sono pericolosi.',exEn:'Lightning is dangerous.'},
    {it:'il tuono',en:'thunder',cat:'Nature',ipa:'/il ˈtwɔː.no/',ex:'Ho sentito un tuono.',exEn:'I heard thunder.'},
    {it:'la nebbia',en:'the fog / mist',cat:'Nature',ipa:'/la ˈnɛb.bja/',ex:'C\'è molta nebbia.',exEn:'There\'s a lot of fog.'},
    {it:'la grandine',en:'hail',cat:'Nature',ipa:'/la ˈɡran.di.ne/',ex:'È caduta la grandine.',exEn:'There was hail.'},
    {it:'il ghiaccio',en:'ice',cat:'Nature',ipa:'/il ˈɡjat.tʃo/',ex:'Attenzione al ghiaccio!',exEn:'Watch out for ice!'},
    {it:'il caldo',en:'heat / hot weather',cat:'Nature',ipa:'/il ˈkal.do/',ex:'Fa molto caldo.',exEn:'It\'s very hot.'},
    {it:'il freddo',en:'cold / cold weather',cat:'Nature',ipa:'/il ˈfrɛd.do/',ex:'Fa freddo oggi.',exEn:'It\'s cold today.'},
    {it:'la primavera',en:'spring',cat:'Nature',ipa:'/la primaˈveː.ra/',ex:'In primavera i fiori sbocciano.',exEn:'In spring the flowers bloom.'},
    {it:'l\'estate',en:'summer',cat:'Nature',ipa:'/leˈstaː.te/',ex:'D\'estate vado al mare.',exEn:'In summer I go to the sea.'},
    {it:'l\'autunno',en:'autumn',cat:'Nature',ipa:'/lawˈtun.no/',ex:'In autunno le foglie cadono.',exEn:'In autumn the leaves fall.'},
    {it:'l\'inverno',en:'winter',cat:'Nature',ipa:'/linˈvɛr.no/',ex:'D\'inverno fa freddo.',exEn:'In winter it\'s cold.'},
    {it:'la montagna',en:'the mountain',cat:'Nature',ipa:'/la monˈtaɲ.ɲa/',ex:'Le montagne sono bellissime.',exEn:'The mountains are very beautiful.'},
    {it:'il mare',en:'the sea',cat:'Nature',ipa:'/il ˈmaː.re/',ex:'Vado al mare in estate.',exEn:'I go to the sea in summer.'},
    {it:'il lago',en:'the lake',cat:'Nature',ipa:'/il ˈlaː.ɡo/',ex:'Il Lago di Garda è bellissimo.',exEn:'Lake Garda is very beautiful.'},
    {it:'il fiume',en:'the river',cat:'Nature',ipa:'/il ˈfjuː.me/',ex:'Il Tevere scorre a Roma.',exEn:'The Tiber flows through Rome.'},
    {it:'la collina',en:'the hill',cat:'Nature',ipa:'/la kolˈliː.na/',ex:'La collina è coperta di vigneti.',exEn:'The hill is covered in vineyards.'},
    {it:'la pianura',en:'the plain',cat:'Nature',ipa:'/la pjaˈnuː.ra/',ex:'La pianura Padana è fertile.',exEn:'The Po Valley is fertile.'},
    {it:'la campagna',en:'the countryside',cat:'Nature',ipa:'/la kamˈpaɲ.ɲa/',ex:'Mi piace la campagna toscana.',exEn:'I like the Tuscan countryside.'},
    {it:'la spiaggia',en:'the beach',cat:'Nature',ipa:'/la ˈspjaˈdʒa/',ex:'Andiamo in spiaggia!',exEn:'Let\'s go to the beach!'},
    {it:'la foresta',en:'the forest',cat:'Nature',ipa:'/la foˈrɛs.ta/',ex:'La foresta amazzonica.',exEn:'The Amazon forest.'},
    {it:'il bosco',en:'the wood / woodland',cat:'Nature',ipa:'/il ˈbɔs.ko/',ex:'Facciamo una passeggiata nel bosco.',exEn:'Let\'s take a walk in the woods.'},
    {it:'il vulcano',en:'the volcano',cat:'Nature',ipa:'/il vulˈkaː.no/',ex:'Il Vesuvio è un vulcano.',exEn:'Vesuvius is a volcano.'},
    {it:'il terremoto',en:'the earthquake',cat:'Nature',ipa:'/il terreˈmɔː.to/',ex:'C\'è stato un terremoto.',exEn:'There was an earthquake.'},
    {it:'l\'inondazione',en:'the flood',cat:'Nature',ipa:'/linondatˈtsjoː.ne/',ex:'L\'inondazione ha causato danni.',exEn:'The flood caused damage.'},
    {it:'l\'incendio',en:'the fire',cat:'Nature',ipa:'/linˈtʃɛn.djo/',ex:'C\'è un incendio nel bosco.',exEn:'There\'s a fire in the woods.'},
    {it:'il tramonto',en:'the sunset',cat:'Nature',ipa:'/il traˈmɔn.to/',ex:'Il tramonto è bellissimo.',exEn:'The sunset is very beautiful.'},
    {it:'l\'alba',en:'dawn / sunrise',cat:'Nature',ipa:'/ˈlal.ba/',ex:'Mi sveglio all\'alba.',exEn:'I wake up at dawn.'},
    {it:'il cielo',en:'the sky',cat:'Nature',ipa:'/il ˈtʃjeː.lo/',ex:'Il cielo è azzurro.',exEn:'The sky is blue.'},
    {it:'le stelle',en:'the stars',cat:'Nature',ipa:'/le ˈstɛl.le/',ex:'Le stelle brillano stanotte.',exEn:'The stars shine tonight.'},
    {it:'la luna',en:'the moon',cat:'Nature',ipa:'/la ˈluː.na/',ex:'La luna piena è bellissima.',exEn:'The full moon is beautiful.'},
    {it:'il fiore',en:'the flower',cat:'Nature',ipa:'/il ˈfjoː.re/',ex:'I fiori del giardino.',exEn:'The flowers in the garden.'},
    {it:'l\'albero',en:'the tree',cat:'Nature',ipa:'/ˈlal.be.ro/',ex:'L\'albero è molto alto.',exEn:'The tree is very tall.'},
    {it:'l\'erba',en:'the grass',cat:'Nature',ipa:'/ˈlɛr.ba/',ex:'L\'erba è verde.',exEn:'The grass is green.'},
    {it:'la foglia',en:'the leaf',cat:'Nature',ipa:'/la ˈfɔʎ.ʎa/',ex:'Le foglie cadono in autunno.',exEn:'The leaves fall in autumn.'},
    {it:'il ramo',en:'the branch',cat:'Nature',ipa:'/il ˈraː.mo/',ex:'Il ramo è spezzato.',exEn:'The branch is broken.'},
    {it:'la radice',en:'the root',cat:'Nature',ipa:'/la raˈdiː.tʃe/',ex:'Le radici dell\'albero.',exEn:'The roots of the tree.'},
    {it:'la pietra',en:'the stone / rock',cat:'Nature',ipa:'/la ˈpjeː.tra/',ex:'Una pietra nel fiume.',exEn:'A stone in the river.'},
    {it:'la sabbia',en:'the sand',cat:'Nature',ipa:'/la ˈsab.bja/',ex:'La sabbia è calda.',exEn:'The sand is hot.'},
    {it:'l\'onda',en:'the wave',cat:'Nature',ipa:'/ˈlɔn.da/',ex:'Le onde sono alte.',exEn:'The waves are high.'},
    {it:'la costa',en:'the coast',cat:'Nature',ipa:'/la ˈkɔs.ta/',ex:'La costa amalfitana è stupenda.',exEn:'The Amalfi coast is stunning.'},
    {it:'l\'isola',en:'the island',cat:'Nature',ipa:'/ˈliː.zo.la/',ex:'La Sicilia è un\'isola.',exEn:'Sicily is an island.'},
    {it:'la penisola',en:'the peninsula',cat:'Nature',ipa:'/la peˈniː.zo.la/',ex:'L\'Italia è una penisola.',exEn:'Italy is a peninsula.'},
    {it:'il paesaggio',en:'the landscape / scenery',cat:'Nature',ipa:'/il paeˈzadʒ.dʒo/',ex:'Un paesaggio mozzafiato.',exEn:'A breathtaking landscape.'},
    {it:'l\'ambiente',en:'the environment',cat:'Nature',ipa:'/lamˈbjen.te/',ex:'Rispettiamo l\'ambiente.',exEn:'Let\'s respect the environment.'},
    {it:'inquinamento',en:'pollution',cat:'Nature',ipa:'/inkwinaˈmɛn.to/',ex:'L\'inquinamento è un problema.',exEn:'Pollution is a problem.'},
  ]
};

window.PACK_nature.words.push(
  {it:'il terremoto',en:'earthquake',cat:'Nature',ipa:'/il terreˈmɔː.to/',ex:'C\'è stato un terremoto.',exEn:'There was an earthquake.'},
  {it:'l\'alluvione',en:'flood',cat:'Nature',ipa:'/lalluˈvjoː.ne/',ex:'L\'alluvione ha causato danni.',exEn:'The flood caused damage.'},
  {it:'la siccità',en:'drought',cat:'Nature',ipa:'/la sittʃiˈta/',ex:'La siccità è grave.',exEn:'The drought is severe.'},
  {it:'l\'uragano',en:'hurricane',cat:'Nature',ipa:'/luraˈɡaː.no/',ex:'Un uragano devastante.',exEn:'A devastating hurricane.'},
  {it:'la valanga',en:'avalanche',cat:'Nature',ipa:'/la vaˈlaŋ.ɡa/',ex:'Una valanga di neve.',exEn:'A snow avalanche.'},
  {it:'la frana',en:'landslide',cat:'Nature',ipa:'/la ˈfraː.na/',ex:'Una frana ha bloccato la strada.',exEn:'A landslide blocked the road.'},
  {it:'la cascata',en:'waterfall',cat:'Nature',ipa:'/la kasˈkaː.ta/',ex:'Una cascata imponente.',exEn:'An imposing waterfall.'},
  {it:'il ghiacciaio',en:'glacier',cat:'Nature',ipa:'/il ɡjatˈtʃaː.jo/',ex:'Il ghiacciaio si scioglie.',exEn:'The glacier is melting.'},
  {it:'il deserto',en:'desert',cat:'Nature',ipa:'/il deˈzɛr.to/',ex:'Il deserto del Sahara.',exEn:'The Sahara desert.'},
  {it:'la giungla',en:'jungle',cat:'Nature',ipa:'/la ˈdʒuŋ.ɡla/',ex:'La giungla amazzonica.',exEn:'The Amazon jungle.'},
  {it:'la barriera corallina',en:'coral reef',cat:'Nature',ipa:'/la barˈrjeː.ra korallˈiː.na/',ex:'La Grande Barriera Corallina.',exEn:'The Great Barrier Reef.'},
  {it:'la migrazione',en:'migration',cat:'Nature',ipa:'/la miɡraˈtsjoː.ne/',ex:'La migrazione degli uccelli.',exEn:'Bird migration.'},
  {it:'l\'estinzione',en:'extinction',cat:'Nature',ipa:'/lestinˈtsjoː.ne/',ex:'L\'estinzione delle specie.',exEn:'Species extinction.'},
  {it:'la biodiversità',en:'biodiversity',cat:'Nature',ipa:'/la biodiversiˈta/',ex:'La biodiversità è in pericolo.',exEn:'Biodiversity is in danger.'},
  {it:'l\'ecosistema',en:'ecosystem',cat:'Nature',ipa:'/lekosisˈteː.ma/',ex:'L\'ecosistema è fragile.',exEn:'The ecosystem is fragile.'},
  {it:'il cambiamento climatico',en:'climate change',cat:'Nature',ipa:'/il kamˈbjaˈmɛn.to kliˈmaː.ti.ko/',ex:'Il cambiamento climatico è urgente.',exEn:'Climate change is urgent.'},
  {it:'la deforestazione',en:'deforestation',cat:'Nature',ipa:'/la deforestatˈtsjoː.ne/',ex:'La deforestazione è un problema.',exEn:'Deforestation is a problem.'},
  {it:'il riciclaggio',en:'recycling',cat:'Nature',ipa:'/il ritʃiˈklaˈdʒo/',ex:'Il riciclaggio è importante.',exEn:'Recycling is important.'},
  {it:'l\'energia rinnovabile',en:'renewable energy',cat:'Nature',ipa:'/lenerˈdʒiː.a rinnoˈvaː.bi.le/',ex:'L\'energia rinnovabile è il futuro.',exEn:'Renewable energy is the future.'},
  {it:'la riserva naturale',en:'nature reserve',cat:'Nature',ipa:'/la riˈzɛr.va natuˈraː.le/',ex:'Una riserva protetta.',exEn:'A protected reserve.'},
  {it:'il parco nazionale',en:'national park',cat:'Nature',ipa:'/il ˈpar.ko natsjoˈnaː.le/',ex:'Il Parco Nazionale d\'Abruzzo.',exEn:'The Abruzzo National Park.'},
  {it:'l\'orizzonte',en:'horizon',cat:'Nature',ipa:'/loritˈtson.te/',ex:'L\'orizzonte è lontano.',exEn:'The horizon is far.'},
  {it:'il crepuscolo',en:'twilight',cat:'Nature',ipa:'/il kreˈpus.ko.lo/',ex:'Il crepuscolo è romantico.',exEn:'Twilight is romantic.'},
  {it:'la brezza',en:'breeze',cat:'Nature',ipa:'/la ˈbrɛt.tsa/',ex:'Una brezza leggera.',exEn:'A light breeze.'},
  {it:'la tempesta',en:'storm',cat:'Nature',ipa:'/la temˈpɛs.ta/',ex:'Una tempesta in mare.',exEn:'A storm at sea.'},
  {it:'il temporale',en:'thunderstorm',cat:'Nature',ipa:'/il temporˈaː.le/',ex:'Un temporale estivo.',exEn:'A summer thunderstorm.'},
  {it:'il diluvio',en:'downpour / deluge',cat:'Nature',ipa:'/il diˈluː.vjo/',ex:'Un vero diluvio!',exEn:'A real downpour!'},
  {it:'il vortice',en:'vortex',cat:'Nature',ipa:'/il ˈvɔr.ti.tʃe/',ex:'Un vortice d\'acqua.',exEn:'A water vortex.'},
  {it:'la grotta',en:'cave',cat:'Nature',ipa:'/la ˈɡrɔt.ta/',ex:'Una grotta misteriosa.',exEn:'A mysterious cave.'},
  {it:'la penisola',en:'peninsula',cat:'Nature',ipa:'/la peˈniː.zo.la/',ex:'L\'Italia è una penisola.',exEn:'Italy is a peninsula.'},
  {it:'il paesaggio',en:'landscape',cat:'Nature',ipa:'/il paeˈzadʒ.dʒo/',ex:'Un paesaggio mozzafiato.',exEn:'A breathtaking landscape.'},
  {it:'l\'ambiente',en:'environment',cat:'Nature',ipa:'/lamˈbjen.te/',ex:'Rispettiamo l\'ambiente.',exEn:'Let\'s respect the environment.'},
  {it:'l\'inquinamento',en:'pollution',cat:'Nature',ipa:'/linkwinaˈmɛn.to/',ex:'L\'inquinamento è un problema.',exEn:'Pollution is a problem.'},
  {it:'la flora',en:'flora',cat:'Nature',ipa:'/la ˈfloː.ra/',ex:'La flora mediterranea.',exEn:'Mediterranean flora.'},
  {it:'la fauna',en:'fauna',cat:'Nature',ipa:'/la ˈfaʊ.na/',ex:'La fauna alpina.',exEn:'Alpine fauna.'},
  {it:'la rupe',en:'cliff / rock face',cat:'Nature',ipa:'/la ˈruː.pe/',ex:'Le rupi a picco sul mare.',exEn:'Cliffs plunging into the sea.'},
  {it:'la scogliera',en:'reef / rocky coast',cat:'Nature',ipa:'/la skoʎˈʎeː.ra/',ex:'La scogliera rocciosa.',exEn:'The rocky coast.'},
  {it:'il promontorio',en:'promontory',cat:'Nature',ipa:'/il promonˈtoː.rjo/',ex:'Il promontorio del Gargano.',exEn:'The Gargano promontory.'},
  {it:'il golfo',en:'gulf / bay',cat:'Nature',ipa:'/il ˈɡɔl.fo/',ex:'Il Golfo di Napoli.',exEn:'The Gulf of Naples.'},
  {it:'il fiordo',en:'fjord',cat:'Nature',ipa:'/il ˈfjor.do/',ex:'I fiordi norvegesi.',exEn:'The Norwegian fjords.'},
  {it:'il canyon',en:'canyon',cat:'Nature',ipa:'/il ˈkæn.jən/',ex:'Il Grand Canyon.',exEn:'The Grand Canyon.'},
  {it:'la steppe',en:'steppe',cat:'Nature',ipa:'/la ˈstɛp.pe/',ex:'Le steppe dell\'Asia centrale.',exEn:'The steppes of Central Asia.'},
  {it:'la tundra',en:'tundra',cat:'Nature',ipa:'/la ˈtun.dra/',ex:'La tundra artica.',exEn:'The Arctic tundra.'},
  {it:'il permafrost',en:'permafrost',cat:'Nature',ipa:'/il ˈpɜːr.mə.frɒst/',ex:'Il permafrost si scioglie.',exEn:'The permafrost is melting.'},
  {it:'l\'atmosfera',en:'atmosphere',cat:'Nature',ipa:'/latmoˈsfeː.ra/',ex:'L\'atmosfera terrestre.',exEn:'The Earth\'s atmosphere.'},
  {it:'lo strato di ozono',en:'ozone layer',cat:'Nature',ipa:'/lo ˈstraː.to di oˈdzoː.no/',ex:'Il buco dello strato di ozono.',exEn:'The hole in the ozone layer.'},
  {it:'l\'effetto serra',en:'greenhouse effect',cat:'Nature',ipa:'/lefˈfɛt.to ˈsɛr.ra/',ex:'L\'effetto serra si intensifica.',exEn:'The greenhouse effect intensifies.'},
  {it:'il sismografo',en:'seismograph',cat:'Nature',ipa:'/il sizˈmoː.ɡra.fo/',ex:'Il sismografo registra i movimenti.',exEn:'The seismograph records movements.'},
  {it:'la magnitudo',en:'magnitude',cat:'Nature',ipa:'/la maɲˈniː.tu.do/',ex:'Un terremoto di magnitudo 6.',exEn:'A magnitude 6 earthquake.'}
);
